package com.company.skillplatform.skill.interfaces;
import com.company.skillplatform.common.interfaces.PageResponse;import com.company.skillplatform.skill.application.SkillService;import com.company.skillplatform.version.application.SkillFileService;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.List;import org.springframework.data.domain.Pageable;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController@RequestMapping("/api/v1/skills")public class SkillController{
 private final SkillService service;private final SkillFileService files;public SkillController(SkillService s,SkillFileService f){service=s;files=f;}
 @GetMapping public PageResponse<SkillService.SkillView> search(@RequestParam(required=false)String keyword,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)String tag,@RequestParam(required=false)String platform,@RequestParam(required=false)String osType,@RequestParam(required=false)String lifecycleStatus,@RequestParam(required=false)Long ownerId,Pageable pageable){return PageResponse.from(service.search(keyword,categoryId,tag,platform,osType,lifecycleStatus,ownerId,pageable),v->v);}
 @PostMapping public SkillService.SkillView create(@Valid@RequestBody CreateRequest r,Authentication a,HttpServletRequest h){return service.create(new SkillService.CreateCommand(r.skillKey,r.displayName,r.description,r.categoryId,r.ownerUserIds,r.tagIds),(Long)a.getPrincipal(),h.getRequestId());}
 @GetMapping("/{key}")public SkillService.SkillView get(@PathVariable String key){return service.get(key);}
 @PatchMapping("/{key}")public SkillService.SkillView update(@PathVariable String key,@Valid@RequestBody UpdateRequest r,Authentication a,HttpServletRequest h){return service.update(key,new SkillService.UpdateCommand(r.displayName,r.description,r.categoryId,r.tagIds,r.versionNo),(Long)a.getPrincipal(),h.getRequestId());}
 @PutMapping("/{key}/owners")public SkillService.SkillView owners(@PathVariable String key,@Valid@RequestBody OwnersRequest r,Authentication a,HttpServletRequest h){return service.replaceOwners(key,r.ownerUserIds,r.primaryOwnerUserId,r.versionNo,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/{key}:archive")public SkillService.SkillView archive(@PathVariable String key,@Valid@RequestBody StatusAction r,Authentication a,HttpServletRequest h){return service.archive(key,r.versionNo,r.reason,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/{key}:unarchive")public SkillService.SkillView unarchive(@PathVariable String key,@Valid@RequestBody StatusAction r,Authentication a,HttpServletRequest h){return service.unarchive(key,r.versionNo,r.reason,(Long)a.getPrincipal(),h.getRequestId());}
 @GetMapping("/{key}/versions")public List<SkillService.VersionView> versions(@PathVariable String key){return service.versions(key);}
 @GetMapping("/versions/{versionId}")public SkillService.VersionView version(@PathVariable Long versionId){return service.getVersion(versionId);}
 @PostMapping("/{key}/draft:open")public SkillService.VersionView open(@PathVariable String key,Authentication a,HttpServletRequest h){return service.openDraft(key,(Long)a.getPrincipal(),h.getRequestId());}
 @GetMapping("/{key}/draft")public SkillService.VersionView draft(@PathVariable String key){return service.draft(key);}
 @PostMapping(value="/{key}/draft:upload",consumes="multipart/form-data")public SkillFileService.UploadView upload(@PathVariable String key,@RequestPart(required=false)MultipartFile file,@RequestParam(required=false)String changeLog,Authentication a,HttpServletRequest h){return files.upload(key,file,changeLog,(Long)a.getPrincipal(),h.getRequestId());}
 @GetMapping("/versions/{versionId}/files")public List<SkillFileService.FileView> fileTree(@PathVariable Long versionId){return files.files(versionId);}
 @DeleteMapping("/{key}/draft")public void cancel(@PathVariable String key,@RequestParam int versionNo,Authentication a,HttpServletRequest h){service.cancelDraft(key,versionNo,(Long)a.getPrincipal(),h.getRequestId());}
 public record CreateRequest(@NotBlank@Pattern(regexp="^[a-z0-9]+(-[a-z0-9]+)*$")String skillKey,@NotBlank String displayName,@NotBlank String description,Long categoryId,List<Long>ownerUserIds,List<Long>tagIds){}public record UpdateRequest(@NotBlank String displayName,@NotBlank String description,Long categoryId,List<Long>tagIds,@NotNull Integer versionNo){}public record OwnersRequest(@NotEmpty List<@NotNull Long>ownerUserIds,@NotNull Long primaryOwnerUserId,@NotNull Integer versionNo){}public record StatusAction(@NotNull Integer versionNo,@NotBlank String reason){}
}
