package com.company.skillplatform.user.interfaces;
import com.company.skillplatform.user.application.ScopedRoleService;
import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.constraints.NotBlank;
import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/admin") @PreAuthorize("hasAuthority('admin:identity') or hasAuthority('skill:review')")
public class ScopedRoleController {private final ScopedRoleService service;public ScopedRoleController(ScopedRoleService s){service=s;}
 @GetMapping("/teams/tree") List<ScopedRoleService.TeamView> tree(Authentication a){return service.tree((Long)a.getPrincipal(),isGlobalAdmin(a));}
 @GetMapping("/teams/{teamId}/members") List<ScopedRoleService.MemberView> members(@PathVariable Long teamId,Authentication a){return service.members(teamId,(Long)a.getPrincipal(),isGlobalAdmin(a));}
 @GetMapping("/users/{userId}/scoped-roles") List<ScopedRoleService.AssignmentView> assignments(@PathVariable Long userId){return service.assignments(userId);}
 @PostMapping("/teams/{teamId}/members/{userId}/roles") ScopedRoleService.AssignmentView grant(@PathVariable Long teamId,@PathVariable Long userId,@RequestParam @NotBlank String roleKey,Authentication a,HttpServletRequest h){Long operator=(Long)a.getPrincipal();boolean global=isGlobalAdmin(a);if(!global&&!service.isTeamAdmin(teamId,operator))throw new org.springframework.security.access.AccessDeniedException("Team administrator permission required");if(!global&&!Set.of("TEAM_MAINTAINER","PROJECT_MANAGER").contains(roleKey))throw new org.springframework.security.access.AccessDeniedException("Team administrators may only manage maintainers and project managers");return service.grant(teamId,userId,roleKey,operator,h.getRequestId());}
 @DeleteMapping("/teams/{teamId}/members/{userId}/roles/{roleKey}") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) void revoke(@PathVariable Long teamId,@PathVariable Long userId,@PathVariable String roleKey,Authentication a,HttpServletRequest h){Long operator=(Long)a.getPrincipal();boolean global=isGlobalAdmin(a);if(!global&&!service.isTeamAdmin(teamId,operator))throw new org.springframework.security.access.AccessDeniedException("Team administrator permission required");if(!global&&!Set.of("TEAM_MAINTAINER","PROJECT_MANAGER").contains(roleKey))throw new org.springframework.security.access.AccessDeniedException("Team administrators may only manage maintainers and project managers");service.revoke(teamId,userId,roleKey,operator,h.getRequestId());}
 @PostMapping("/platform-maintainers/{userId}") @PreAuthorize("hasAuthority('admin:identity')") ScopedRoleService.AssignmentView grantPlatform(@PathVariable Long userId,Authentication a,HttpServletRequest h){return service.grantPlatform(userId,"PLATFORM_MAINTAINER",(Long)a.getPrincipal(),h.getRequestId());}
 @DeleteMapping("/platform-maintainers/{userId}") @PreAuthorize("hasAuthority('admin:identity')") @ResponseStatus(org.springframework.http.HttpStatus.NO_CONTENT) void revokePlatform(@PathVariable Long userId,Authentication a,HttpServletRequest h){service.revokePlatform(userId,"PLATFORM_MAINTAINER",(Long)a.getPrincipal(),h.getRequestId());}
 private boolean isGlobalAdmin(Authentication a){return a.getAuthorities().stream().anyMatch(x->"admin:identity".equals(x.getAuthority()));}
}
