package com.company.skillplatform.agentworkflow.application;

import com.company.skillplatform.agentworkflow.infrastructure.entity.AgentProfileEntity;
import com.company.skillplatform.agentworkflow.infrastructure.repository.AgentProfileRepository;
import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.project.infrastructure.repository.VirtualProjectRepository;
import java.time.Instant;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AgentWorkflowService {
    private final JdbcTemplate jdbc; private final AgentProfileRepository profiles; private final VirtualProjectRepository projects;
    public AgentWorkflowService(JdbcTemplate jdbc,AgentProfileRepository profiles,VirtualProjectRepository projects){this.jdbc=jdbc;this.profiles=profiles;this.projects=projects;}
    @Transactional(readOnly=true) public List<ProfileView> profiles(){return profiles.findAll().stream().map(p->new ProfileView(p.getId(),p.getCode(),p.getName(),p.getCategory(),p.getDescription(),p.getStatus(),p.getMaintainer(),versions(p.getId()))).toList();}
    @Transactional(readOnly=true) public ProfileView profile(String code){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND));return new ProfileView(p.getId(),p.getCode(),p.getName(),p.getCategory(),p.getDescription(),p.getStatus(),p.getMaintainer(),versions(p.getId()));}
    @Transactional public ProfileView createProfile(ProfileCommand c,String actor){if(profiles.findByCode(c.code()).isPresent()) throw error("AGENT_PROFILE_EXISTS","Profile code already exists",HttpStatus.CONFLICT); AgentProfileEntity p=profiles.save(new AgentProfileEntity(c.code(),c.name(),c.category(),c.description(),actor)); return new ProfileView(p.getId(),p.getCode(),p.getName(),p.getCategory(),p.getDescription(),p.getStatus(),p.getMaintainer(),List.of());}
    @Transactional public VersionView createVersion(String code,VersionCommand c,String actor){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND)); Integer n=jdbc.queryForObject("select coalesce(max(version_no),0)+1 from agent_profile_version where agent_profile_id=?",Integer.class,p.getId()); jdbc.update("insert into agent_profile_version(time_created,time_updated,agent_profile_id,version_no,system_prompt,model_code,temperature,max_iteration_per_run,timeout_seconds,output_schema_json,runtime_config_json,status,changelog) values(now(3),now(3),?,?,?,?,?,?,?,?,?,'DRAFT',?)",p.getId(),n,c.systemPrompt(),c.modelCode(),c.temperature(),c.maxIterationPerRun(),c.timeoutSeconds(),c.outputSchemaJson(),c.runtimeConfigJson(),c.changelog()); Long v=jdbc.queryForObject("select id from agent_profile_version where agent_profile_id=? and version_no=?",Long.class,p.getId(),n); if(c.skillIds()!=null) for(int i=0;i<c.skillIds().size();i++) jdbc.update("insert into agent_profile_version_skill(time_created,time_updated,agent_profile_version_id,skill_id,sort_order) values(now(3),now(3),?,?,?)",v,c.skillIds().get(i),i); if(c.tools()!=null) for(ToolBinding t:c.tools()) jdbc.update("insert into agent_profile_version_tool(time_created,time_updated,agent_profile_version_id,tool_code,enabled,permission_mode,config_json) values(now(3),now(3),?,?,?,?,?)",v,t.toolCode(),t.enabled(),t.permissionMode(),t.configJson()); return version(p.getId(),n);}
    @Transactional public VersionView publish(String code,int no,String actor){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND)); int n=jdbc.update("update agent_profile_version set status='PUBLISHED',published_by=?,published_at=now(3),time_updated=now(3) where agent_profile_id=? and version_no=? and status='DRAFT'",actor,p.getId(),no); if(n==0)throw error("AGENT_VERSION_IMMUTABLE","Only a DRAFT version can be published",HttpStatus.CONFLICT); return version(p.getId(),no);}
    @Transactional public RunView start(String projectKey,Long actor,RunCommand c){Long projectId=projectId(projectKey); assertMember(projectId,actor); String commandId=UUID.randomUUID().toString(); jdbc.update("insert into workflow_run(time_created,time_updated,project_id,workflow_code,workflow_version,status,started_by,started_at) values(now(3),now(3),?,?,?,'RUNNING',?,now(3))",projectId,c.workflowCode(),c.workflowVersion(),actor); Long runId=jdbc.queryForObject("select id from workflow_run where project_id=? and started_by=? order by id desc limit 1",Long.class,projectId,actor); jdbc.update("insert into stage_run(time_created,time_updated,workflow_run_id,stage_key,status,run_no) values(now(3),now(3),?,?,'RUNNING',1)",runId,"REQUIREMENT"); Long stageId=jdbc.queryForObject("select id from stage_run where workflow_run_id=?",Long.class,runId); List<String> nodes=jdbc.query("select n.node_key from stage_agent_node_def n join workflow_stage_def d on d.id=n.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' order by n.sort_order",(rs,n)->rs.getString(1),c.workflowCode(),c.workflowVersion()); if(nodes.isEmpty()) throw error("WORKFLOW_DEFINITION_EMPTY","Published workflow has no Requirement nodes",HttpStatus.CONFLICT); for(int i=0;i<nodes.size();i++){Long profileVersion=i<c.profileVersionIds().size()?c.profileVersionIds().get(i):jdbc.queryForObject("select n.agent_profile_version_id from stage_agent_node_def n join workflow_stage_def d on d.id=n.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' and n.node_key=?",Long.class,c.workflowCode(),c.workflowVersion(),nodes.get(i)); jdbc.update("insert into agent_workflow_session(time_created,time_updated,stage_run_id,node_key,profile_version_id,status) values(now(3),now(3),?,?,?,'ACTIVE')",stageId,nodes.get(i),profileVersion); if(i==0) enqueue(runId,stageId,nodes.get(i),profileVersion,commandId); } return run(runId,actor);}

    private void enqueue(Long workflowId,Long stageId,String node,Long profileVersion,String commandId){Long session=jdbc.queryForObject("select id from agent_workflow_session where stage_run_id=? and node_key=?",Long.class,stageId,node); Integer next=jdbc.queryForObject("select coalesce(max(execution_no),0)+1 from agent_workflow_run where session_id=?",Integer.class,session); jdbc.update("insert into agent_workflow_run(time_created,time_updated,stage_run_id,session_id,node_key,profile_version_id,status,execution_no) values(now(3),?,?,?,?,?,'QUEUED',?)",stageId,session,node,profileVersion,next); Long ar=jdbc.queryForObject("select id from agent_workflow_run where session_id=? and execution_no=?",Long.class,session,next); jdbc.update("insert into runtime_command(time_created,time_updated,command_id,command_type,aggregate_type,aggregate_id,payload_json,status) values(now(3),now(3),?,'START_AGENT','AGENT_RUN',?,'{}','PENDING')",commandId+"-"+node+"-"+next,ar);}

    @Transactional public RunView ingestEvent(Long runId, String eventId, String node, String executionStatus, String resultCode, String resultJson, Long actor){return ingestEvent0(runId,eventId,node,executionStatus,resultCode,resultJson,actor);}
    @Transactional public void ingestEventInternal(Long runId, String eventId, String node, String executionStatus, String resultCode, String resultJson){ingestEvent0(runId,eventId,node,executionStatus,resultCode,resultJson,null);}
    private RunView ingestEvent0(Long runId,String eventId,String node,String executionStatus,String resultCode,String resultJson,Long actor){
        Map<String,Object> base=jdbc.queryForMap("select project_id,workflow_code,workflow_version from workflow_run where id=?",runId);
        if(actor!=null)assertMember(((Number)base.get("project_id")).longValue(),actor);
        if(eventId==null||eventId.isBlank())throw error("RUNTIME_EVENT_ID_REQUIRED","Runtime event id is required",HttpStatus.BAD_REQUEST);
        if(jdbc.update("insert ignore into runtime_event_index(time_created,time_updated,provider,event_id,workflow_run_id,event_type) values(now(3),now(3),'OPENHANDS',?,?,?)",eventId,runId,"AGENT_RUN_COMPLETED")==0)return actor==null?null:run(runId,actor);
        Map<String,Object> stage=jdbc.queryForMap("select id,loop_count from stage_run where workflow_run_id=? and stage_key='REQUIREMENT' and status in ('RUNNING','PROVISIONING') order by run_no desc limit 1",runId);
        Long stageId=((Number)stage.get("id")).longValue();
        Long agentRunId=jdbc.queryForObject("select id from agent_workflow_run where stage_run_id=? and node_key=? and status in ('QUEUED','STARTING','RUNNING') order by execution_no desc limit 1",Long.class,stageId,node);
        String finalStatus="SUCCESS".equals(executionStatus)?"SUCCEEDED":"FAILED";
        jdbc.update("update agent_workflow_run set status=?,result_code=?,result_json=?,completed_at=now(3),time_updated=now(3) where id=?",finalStatus,resultCode,resultJson,agentRunId);
        if(!"SUCCESS".equals(executionStatus)){requireHuman(stageId);return actor==null?null:run(runId,actor);}
        List<EdgeView> edges=jdbc.query("select target.node_key,e.increments_loop,json_unquote(json_extract(e.condition_json,'$.type')),json_unquote(json_extract(e.condition_json,'$.field')),coalesce(json_unquote(json_extract(e.condition_json,'$.operator')),'EQ'),json_unquote(json_extract(e.condition_json,'$.value')) from stage_agent_edge_def e join stage_agent_node_def source on source.id=e.from_node_id left join stage_agent_node_def target on target.id=e.to_node_id join workflow_stage_def d on d.id=e.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' and source.node_key=? order by e.priority",(rs,n)->new EdgeView(rs.getString(1),rs.getBoolean(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)),base.get("workflow_code"),base.get("workflow_version"),node);
        EdgeView matched=edges.stream().filter(e->StructuredEdgeEvaluator.matches(e.type(),e.field(),e.operator(),e.value(),resultCode,finalStatus)).findFirst().orElse(null);
        if(matched==null){requireHuman(stageId);return actor==null?null:run(runId,actor);}
        int loopCount=((Number)stage.get("loop_count")).intValue()+(matched.incrementsLoop()?1:0);
        Integer maxLoop=jdbc.queryForObject("select d.max_loop_count from workflow_stage_def d join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT'",Integer.class,base.get("workflow_code"),base.get("workflow_version"));
        if(matched.incrementsLoop()&&loopCount>(maxLoop==null?0:maxLoop)){jdbc.update("update stage_run set loop_count=?,status='HUMAN_REQUIRED',time_updated=now(3) where id=?",loopCount,stageId);return actor==null?null:run(runId,actor);}
        if(matched.nextNode()==null){jdbc.update("update stage_run set loop_count=?,status='COMPLETED',completed_at=now(3),time_updated=now(3) where id=?",loopCount,stageId);jdbc.update("update workflow_run set status='WAITING_FINAL_ACCEPTANCE',time_updated=now(3) where id=?",runId);}
        else {jdbc.update("update stage_run set loop_count=?,status='RUNNING',time_updated=now(3) where id=?",loopCount,stageId);Long pv=jdbc.queryForObject("select profile_version_id from agent_workflow_session where stage_run_id=? and node_key=?",Long.class,stageId,matched.nextNode());enqueue(runId,stageId,matched.nextNode(),pv,UUID.randomUUID().toString());}
        return actor==null?null:run(runId,actor);
    }
    private void requireHuman(Long stageId){jdbc.update("update stage_run set status='HUMAN_REQUIRED',time_updated=now(3) where id=?",stageId);}
    @Transactional(readOnly=true) public RunView run(Long id,Long actor){Map<String,Object> r=jdbc.queryForMap("select id,project_id,workflow_code,workflow_version,status,started_at,completed_at from workflow_run where id=?",id);Long projectId=((Number)r.get("project_id")).longValue();assertMember(projectId,actor);String workflowCode=String.valueOf(r.get("workflow_code"));int workflowVersion=((Number)r.get("workflow_version")).intValue();List<StageView> stages=jdbc.query("select sr.id,sr.stage_key,coalesce(d.name,sr.stage_key),sr.status,sr.loop_count,coalesce(d.max_loop_count,0) from stage_run sr left join workflow_template t on t.code=? left join workflow_template_version v on v.workflow_template_id=t.id and v.version_no=? left join workflow_stage_def d on d.workflow_version_id=v.id and d.stage_key=sr.stage_key where sr.workflow_run_id=? order by sr.id",(rs,n)->stage(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6)),workflowCode,workflowVersion,id);return new RunView(id,projectId,workflowCode,workflowVersion,String.valueOf(r.get("status")),r.get("started_at"),r.get("completed_at"),stages);}
    private StageView stage(Long id,String key,String name,String status,int loopCount,int maxLoopCount){List<AgentNodeView> agents=jdbc.query("select s.id,s.node_key,coalesce(n.name,s.node_key),coalesce((select r.status from agent_workflow_run r where r.session_id=s.id order by r.execution_no desc limit 1),s.status),n.node_type,p.code from agent_workflow_session s left join stage_agent_node_def n on n.node_key=s.node_key left join agent_profile_version v on v.id=s.profile_version_id left join agent_profile p on p.id=v.agent_profile_id where s.stage_run_id=? order by n.sort_order",(rs,n)->new AgentNodeView(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)),id);String current=agents.stream().filter(a->Set.of("QUEUED","STARTING","RUNNING","WAITING_HUMAN","PAUSED").contains(a.status())).map(AgentNodeView::name).findFirst().orElse(null);return new StageView(id,key,name,status,current,loopCount,maxLoopCount,"HUMAN_REQUIRED".equals(status),agents);}
    @Transactional public InterventionView intervene(Long runId,Long actor,InterventionCommand c){Map<String,Object> r=jdbc.queryForMap("select project_id from workflow_run where id=?",runId);assertMember(((Number)r.get("project_id")).longValue(),actor);jdbc.update("insert into human_intervention(time_created,time_updated,workflow_run_id,user_id,intervention_type,content,status) values(now(3),now(3),?,?,?,?,'CREATED')",runId,actor,c.type(),c.content());Long id=jdbc.queryForObject("select id from human_intervention where workflow_run_id=? and user_id=? order by id desc limit 1",Long.class,runId,actor);return new InterventionView(id,c.type(),"CREATED");}
    @Transactional public RunView accept(Long runId,Long actor,String decision,String comment){Map<String,Object> r=jdbc.queryForMap("select project_id from workflow_run where id=?",runId);assertMember(((Number)r.get("project_id")).longValue(),actor); if(!Set.of("ACCEPTED","REJECTED").contains(decision))throw error("ACCEPTANCE_DECISION_INVALID","Decision must be ACCEPTED or REJECTED",HttpStatus.BAD_REQUEST);jdbc.update("insert into workflow_final_acceptance(time_created,time_updated,workflow_run_id,accepted_by,decision,comment) values(now(3),now(3),?,?,?,?) on duplicate key update accepted_by=values(accepted_by),decision=values(decision),comment=values(comment),time_updated=now(3)",runId,actor,decision,comment);jdbc.update("update workflow_run set status=?,completed_at=now(3),time_updated=now(3) where id=?", "ACCEPTED".equals(decision)?"COMPLETED":"WAITING_FINAL_ACCEPTANCE",runId);return run(runId,actor);}
    private List<VersionView> versions(Long id){return jdbc.query("select id,version_no,status,model_code,temperature,max_iteration_per_run,timeout_seconds,published_at,system_prompt,output_schema_json,runtime_config_json from agent_profile_version where agent_profile_id=? order by version_no desc",(rs,n)->{Long v=rs.getLong(1);List<Long> skills=jdbc.query("select skill_id from agent_profile_version_skill where agent_profile_version_id=? order by sort_order",(x,m)->x.getLong(1),v);List<ToolBinding> tools=jdbc.query("select tool_code,enabled,permission_mode,config_json from agent_profile_version_tool where agent_profile_version_id=? order by tool_code",(x,m)->new ToolBinding(x.getString(1),x.getBoolean(2),x.getString(3),x.getString(4)),v);return new VersionView(v,rs.getInt(2),rs.getString(3),rs.getString(4),rs.getObject(5,Double.class),rs.getInt(6),rs.getInt(7),rs.getTimestamp(8)==null?null:rs.getTimestamp(8).toInstant(),rs.getString(9),rs.getString(10),rs.getString(11),skills,tools);},id);}
    private VersionView version(Long id,int no){return versions(id).stream().filter(v->v.versionNo()==no).findFirst().orElseThrow();}
    private Long projectId(String key){return projects.findByProjectKey(key).map(x->x.getId()).orElseThrow(()->error("PROJECT_NOT_FOUND","Project not found",HttpStatus.NOT_FOUND));}
    private void assertMember(Long p,Long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project_member where project_id=? and user_id=? and status='ACTIVE' and membership_type in ('OWNER','MEMBER')",Integer.class,p,u);if(n==null||n==0)throw error("PROJECT_ACCESS_FORBIDDEN","Project membership required",HttpStatus.FORBIDDEN);}
    private BusinessException error(String c,String m,HttpStatus s){return new BusinessException(c,m,s);}
    public record ProfileCommand(String code,String name,String category,String description){} public record VersionCommand(String systemPrompt,String modelCode,Double temperature,Integer maxIterationPerRun,Integer timeoutSeconds,String outputSchemaJson,String runtimeConfigJson,String changelog,List<Long> skillIds,List<ToolBinding> tools){} public record ToolBinding(String toolCode,boolean enabled,String permissionMode,String configJson){} public record RunCommand(String workflowCode,int workflowVersion,List<Long> profileVersionIds){} public record InterventionCommand(String type,String content){}
    private record EdgeView(String nextNode,boolean incrementsLoop,String type,String field,String operator,String value){}
    public record ProfileView(Long id,String code,String name,String category,String description,String status,String maintainer,List<VersionView> versions){} public record VersionView(Long id,int versionNo,String status,String modelCode,Double temperature,int maxIterationPerRun,int timeoutSeconds,Instant publishedAt,String systemPrompt,String outputSchemaJson,String runtimeConfigJson,List<Long> skillIds,List<ToolBinding> tools){} public record RunView(Long id,Long projectId,String workflowCode,int workflowVersion,String status,Object startedAt,Object completedAt,List<StageView> stages){} public record StageView(Long id,String key,String name,String status,String currentAgent,int loopCount,int maxLoopCount,boolean attention,List<AgentNodeView> agents){} public record AgentNodeView(Long id,String key,String name,String status,String nodeType,String profileCode){} public record InterventionView(Long id,String type,String status){}
}
