package com.company.skillplatform.agentworkflow.application;

import com.company.skillplatform.agentworkflow.infrastructure.entity.AgentProfileEntity;
import com.company.skillplatform.agentworkflow.infrastructure.repository.AgentProfileRepository;
import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.project.infrastructure.repository.VirtualProjectRepository;
import java.time.Instant;
import java.util.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AgentWorkflowService {
    private final JdbcTemplate jdbc; private final AgentProfileRepository profiles; private final VirtualProjectRepository projects; private final ObjectMapper json; private final StageCompletionEvaluator completion;
    public AgentWorkflowService(JdbcTemplate jdbc,AgentProfileRepository profiles,VirtualProjectRepository projects,ObjectMapper json,StageCompletionEvaluator completion){this.jdbc=jdbc;this.profiles=profiles;this.projects=projects;this.json=json;this.completion=completion;}
    @Transactional(readOnly=true) public List<ProfileView> profiles(){return profiles.findByProjectIdIsNullOrderByCode().stream().map(this::profileView).toList();}
    @Transactional(readOnly=true) public ProfileView profile(String code){return profileView(profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND)));}
    private ProfileView profileView(AgentProfileEntity p){return new ProfileView(p.getId(),p.getCode(),p.getName(),p.getCategory(),p.getDescription(),p.getStatus(),p.getMaintainer(),p.getSourceType(),p.getOwnerUserId(),p.isSystemLocked(),p.getDerivedFromProfileVersionId(),versions(p.getId()));}
    @Transactional public ProfileView createProfile(ProfileCommand c,String actor){if(profiles.findByCode(c.code()).isPresent()) throw error("AGENT_PROFILE_EXISTS","Profile code already exists",HttpStatus.CONFLICT); AgentProfileEntity p=new AgentProfileEntity(c.code(),c.name(),c.category(),c.description(),actor);p.assignOwner(Long.valueOf(actor));p=profiles.save(p);return profileView(p);}
    @Transactional public ProfileView fork(String code,Long actor,String newCode,String newName,Integer versionNo){AgentProfileEntity source=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND));if(newCode==null||newCode.isBlank()||newName==null||newName.isBlank())throw error("AGENT_FORK_INVALID","New code and name are required",HttpStatus.BAD_REQUEST);if(profiles.findByCode(newCode).isPresent())throw error("AGENT_PROFILE_EXISTS","Profile code already exists",HttpStatus.CONFLICT);Long sourceVersion=versionNo==null?jdbc.queryForObject("select id from agent_profile_version where agent_profile_id=? and status='PUBLISHED' order by version_no desc limit 1",Long.class,source.getId()):jdbc.queryForObject("select id from agent_profile_version where agent_profile_id=? and version_no=? and status='PUBLISHED'",Long.class,source.getId(),versionNo);AgentProfileEntity p=new AgentProfileEntity(newCode,newName,source.getCategory(),source.getDescription(),String.valueOf(actor));p.assignOwner(actor);p=profiles.save(p);jdbc.update("update agent_profile set derived_from_profile_version_id=? where id=?",sourceVersion,p.getId());Map<String,Object> v=jdbc.queryForMap("select system_prompt,model_code,temperature,max_iteration_per_run,timeout_seconds,output_schema_json,runtime_config_json from agent_profile_version where id=?",sourceVersion);jdbc.update("insert into agent_profile_version(time_created,time_updated,agent_profile_id,version_no,system_prompt,model_code,temperature,max_iteration_per_run,timeout_seconds,output_schema_json,runtime_config_json,status,changelog) values(now(3),now(3),?,1,?,?,?,?,?,?,?,'DRAFT','Forked from published version')",p.getId(),v.get("system_prompt"),v.get("model_code"),v.get("temperature"),v.get("max_iteration_per_run"),v.get("timeout_seconds"),v.get("output_schema_json"),v.get("runtime_config_json"));Long nv=jdbc.queryForObject("select id from agent_profile_version where agent_profile_id=? and version_no=1 order by id desc limit 1",Long.class,p.getId());jdbc.update("insert into agent_profile_version_skill(time_created,time_updated,agent_profile_version_id,skill_id,version_policy,fixed_skill_version_id,required,sort_order) select now(3),now(3),?,skill_id,version_policy,fixed_skill_version_id,required,sort_order from agent_profile_version_skill where agent_profile_version_id=?",nv,sourceVersion);jdbc.update("insert into agent_profile_version_tool(time_created,time_updated,agent_profile_version_id,tool_code,enabled,permission_mode,config_json) select now(3),now(3),?,tool_code,enabled,permission_mode,config_json from agent_profile_version_tool where agent_profile_version_id=?",nv,sourceVersion);return profile(newCode);}
    @Transactional public VersionView createVersion(String code,VersionCommand c,String actor){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND));assertCanMaintain(p,Long.valueOf(actor));Integer n=jdbc.queryForObject("select coalesce(max(version_no),0)+1 from agent_profile_version where agent_profile_id=?",Integer.class,p.getId());if(c.systemPrompt()==null||c.systemPrompt().isBlank()||c.modelCode()==null||c.modelCode().isBlank())throw error("AGENT_VERSION_INVALID","System prompt and model are required",HttpStatus.BAD_REQUEST);validateSkillBindings(c.skills());jdbc.update("insert into agent_profile_version(time_created,time_updated,agent_profile_id,version_no,system_prompt,model_code,temperature,max_iteration_per_run,timeout_seconds,output_schema_json,runtime_config_json,status,changelog) values(now(3),now(3),?,?,?,?,?,?,?,?,?,'DRAFT',?)",p.getId(),n,c.systemPrompt(),c.modelCode(),c.temperature(),c.maxIterationPerRun(),c.timeoutSeconds(),c.outputSchemaJson(),c.runtimeConfigJson(),c.changelog()); Long v=jdbc.queryForObject("select id from agent_profile_version where agent_profile_id=? and version_no=?",Long.class,p.getId(),n); if(c.skills()!=null) for(SkillBinding s:c.skills())jdbc.update("insert into agent_profile_version_skill(time_created,time_updated,agent_profile_version_id,skill_id,version_policy,fixed_skill_version_id,required,sort_order) values(now(3),now(3),?,?,?,?,?,?)",v,s.skillId(),s.versionPolicy(),s.fixedSkillVersionId(),s.required(),s.sortOrder());if(c.tools()!=null) for(ToolBinding t:c.tools()) jdbc.update("insert into agent_profile_version_tool(time_created,time_updated,agent_profile_version_id,tool_code,enabled,permission_mode,config_json) values(now(3),now(3),?,?,?,?,?)",v,t.toolCode(),t.enabled(),t.permissionMode(),t.configJson());return version(p.getId(),n);}
    @Transactional public VersionView publish(String code,int no,String actor){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND));assertCanMaintain(p,Long.valueOf(actor));Map<String,Object> draft=jdbc.queryForMap("select id,system_prompt,model_code from agent_profile_version where agent_profile_id=? and version_no=?",p.getId(),no);if(String.valueOf(draft.get("system_prompt")).isBlank()||String.valueOf(draft.get("model_code")).isBlank())throw error("AGENT_VERSION_INVALID","System prompt and model are required",HttpStatus.BAD_REQUEST);int invalid=jdbc.queryForObject("select count(*) from agent_profile_version_skill b left join skill_version v on v.id=b.fixed_skill_version_id where b.agent_profile_version_id=? and (b.version_policy not in ('FIXED','LATEST_PUBLISHED') or (b.version_policy='FIXED' and (v.id is null or v.skill_id<>b.skill_id or v.lifecycle_status not in ('PUBLISHED','DEPRECATED'))))",Integer.class,draft.get("id"));if(invalid>0)throw error("AGENT_SKILL_INVALID","Skill binding cannot be published",HttpStatus.BAD_REQUEST);int n=jdbc.update("update agent_profile_version set status='PUBLISHED',published_by=?,published_at=now(3),time_updated=now(3) where agent_profile_id=? and version_no=? and status='DRAFT'",actor,p.getId(),no);if(n==0)throw error("AGENT_VERSION_IMMUTABLE","Only a DRAFT version can be published",HttpStatus.CONFLICT);return version(p.getId(),no);}
    @Transactional public RunView start(String projectKey,Long actor,RunCommand c){Long projectId=projectId(projectKey); assertMember(projectId,actor); Long existing=latestRunId(projectId); if(existing!=null) return run(existing,actor); if(c.initialRequest()==null||c.initialRequest().isBlank())throw error("INITIAL_REQUEST_REQUIRED","Initial request is required",HttpStatus.BAD_REQUEST); String commandId=UUID.randomUUID().toString(); jdbc.update("insert into workflow_run(time_created,time_updated,project_id,workflow_code,workflow_version,status,started_by,started_at,initial_request,context_snapshot_json) values(now(3),now(3),?,?,?,'RUNNING',?,now(3),?,?)",projectId,c.workflowCode(),c.workflowVersion(),actor,c.initialRequest().trim(),jsonOrEmpty(c.contextSnapshotJson())); Long runId=jdbc.queryForObject("select id from workflow_run where project_id=? and started_by=? order by id desc limit 1",Long.class,projectId,actor); createRequirementStage(runId,c,commandId); return run(runId,actor);}
    @Transactional public void freezeStartContext(Long runId, RunCommand c){jdbc.update("update workflow_run set initial_request=?,context_snapshot_json=?,time_updated=now(3) where id=?",c.initialRequest(),jsonOrEmpty(c.contextSnapshotJson()),runId);}
    @Transactional public RunView startConfigured(String projectKey,Long actor,String initialRequest,String contextSnapshotJson){Long projectId=projectId(projectKey);assertMember(projectId,actor);Map<String,Object> c=jdbc.queryForMap("select id,workflow_template_version_id,config_hash,status from project_agent_configuration where project_id=? order by version_no desc limit 1",projectId);if(!"READY".equals(c.get("status")))throw error("AGENT_CONFIG_NOT_READY","Project agent configuration must be READY",HttpStatus.CONFLICT);Map<String,Object> w=jdbc.queryForMap("select t.code,v.version_no from workflow_template_version v join workflow_template t on t.id=v.workflow_template_id where v.id=?",c.get("workflow_template_version_id"));Map<String,Long> bindings=configurationBindings(((Number)c.get("id")).longValue());if(bindings.keySet().stream().noneMatch(k->k.startsWith("REQUIREMENT/")))throw error("AGENT_CONFIG_EMPTY","No Requirement agents configured",HttpStatus.CONFLICT);String selectedContext=contextSnapshot(((Number)c.get("id")).longValue());jdbc.update("update project_agent_configuration set status='LOCKED',confirmed_by=coalesce(confirmed_by,?),confirmed_at=coalesce(confirmed_at,now(3)),time_updated=now(3) where id=?",actor,c.get("id"));RunView run=start(projectKey,actor,new RunCommand(String.valueOf(w.get("code")),((Number)w.get("version_no")).intValue(),bindings,initialRequest,selectedContext==null?contextSnapshotJson:selectedContext));freezeSkillVersions(run.id(),new LinkedHashSet<>(bindings.values()));freezeContextRows(run.id(),((Number)c.get("id")).longValue());jdbc.update("update workflow_run set project_agent_configuration_id=?,config_snapshot_json=?,config_hash=?,time_updated=now(3) where id=?",c.get("id"),snapshot(c.get("id")),c.get("config_hash"),run.id());return run(run.id(),actor);}
    private String contextSnapshot(long configurationId){List<Map<String,Object>> rows=jdbc.queryForList("select context_kind,wiki_document_id,wiki_revision_no,feishu_doc_id,feishu_doc_type,title from project_agent_configuration_context where configuration_id=? order by sort_order,id",configurationId);if(rows.isEmpty())return null;return writeJson(Map.of("contexts",rows));}
    private void freezeContextRows(long runId,long configurationId){jdbc.update("insert into workflow_run_context_snapshot(time_created,workflow_run_id,context_kind,wiki_document_id,wiki_revision_no,feishu_doc_id,feishu_doc_type,title) select now(3),?,c.context_kind,c.wiki_document_id,coalesce(drev.revision_no,c.wiki_revision_no),c.feishu_doc_id,c.feishu_doc_type,c.title from project_agent_configuration_context c left join wiki_document d on d.id=c.wiki_document_id left join wiki_document_revision drev on drev.id=d.current_revision_id where c.configuration_id=?",runId,configurationId);}
    private String snapshot(Object configId){Map<String,Object> config=jdbc.queryForMap("select workflow_template_version_id,source_type,source_preset_version_id,source_project_id,version_no from project_agent_configuration where id=?",configId);return writeJson(Map.of("workflowTemplateVersionId",config.get("workflow_template_version_id"),"sourceType",config.get("source_type"),"sourcePresetVersionId",Objects.toString(config.get("source_preset_version_id"),""),"sourceProjectId",Objects.toString(config.get("source_project_id"),""),"configurationVersion",config.get("version_no"),"nodes",jdbc.queryForList("select stage_key stageKey,node_key nodeKey,agent_profile_version_id agentProfileVersionId from project_agent_configuration_node where configuration_id=? order by stage_key,node_key",configId)));}

    private void createRequirementStage(Long runId,RunCommand c,String commandId){Integer runNo=jdbc.queryForObject("select coalesce(max(run_no),0)+1 from stage_run where workflow_run_id=? and stage_key='REQUIREMENT'",Integer.class,runId);jdbc.update("insert into stage_run(time_created,time_updated,workflow_run_id,stage_key,status,run_no,started_at) values(now(3),now(3),?,?,'RUNNING',?,now(3))",runId,"REQUIREMENT",runNo); Long stageId=jdbc.queryForObject("select id from stage_run where workflow_run_id=? and stage_key='REQUIREMENT' and run_no=?",Long.class,runId,runNo); List<String> nodes=jdbc.query("select n.node_key from stage_agent_node_def n join workflow_stage_def d on d.id=n.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' order by n.sort_order",(rs,n)->rs.getString(1),c.workflowCode(),c.workflowVersion()); if(nodes.isEmpty()) throw error("WORKFLOW_DEFINITION_EMPTY","Published workflow has no Requirement nodes",HttpStatus.CONFLICT); for(int i=0;i<nodes.size();i++){String node=nodes.get(i);Long profileVersion=c.profileBindings().get("REQUIREMENT/"+node);if(profileVersion==null)profileVersion=jdbc.queryForObject("select n.agent_profile_version_id from stage_agent_node_def n join workflow_stage_def d on d.id=n.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' and n.node_key=?",Long.class,c.workflowCode(),c.workflowVersion(),node); jdbc.update("insert into agent_workflow_session(time_created,time_updated,stage_run_id,node_key,profile_version_id,status) values(now(3),now(3),?,?,?,'ACTIVE')",stageId,node,profileVersion); if(i==0) enqueue(runId,stageId,node,profileVersion,commandId); }}

    private Map<String,Long> configurationBindings(Long configurationId){Map<String,Long> bindings=new HashMap<>();jdbc.query("select stage_key,node_key,agent_profile_version_id from project_agent_configuration_node where configuration_id=?",rs->{bindings.put(rs.getString(1)+"/"+rs.getString(2),rs.getLong(3));},configurationId);return bindings;}

    private void validateSkillBindings(List<SkillBinding> bindings){if(bindings==null)return;for(SkillBinding b:bindings){if(b.skillId()==null)throw error("AGENT_SKILL_REQUIRED","Skill id is required",HttpStatus.BAD_REQUEST);if(!Set.of("FIXED","LATEST_PUBLISHED").contains(b.versionPolicy()))throw error("AGENT_SKILL_POLICY_INVALID","Unsupported Skill version policy",HttpStatus.BAD_REQUEST);if("FIXED".equals(b.versionPolicy())&&b.fixedSkillVersionId()==null)throw error("AGENT_SKILL_FIXED_VERSION_REQUIRED","FIXED Skill requires a version",HttpStatus.BAD_REQUEST);if("FIXED".equals(b.versionPolicy())){Integer valid=jdbc.queryForObject("select count(*) from skill_version where id=? and skill_id=? and lifecycle_status in ('PUBLISHED','DEPRECATED')",Integer.class,b.fixedSkillVersionId(),b.skillId());if(valid==0)throw error("AGENT_SKILL_FIXED_VERSION_INVALID","Fixed Skill version is invalid",HttpStatus.BAD_REQUEST);}}}
    private void freezeSkillVersions(Long runId,Set<Long> profileVersionIds){for(Long profileVersionId:profileVersionIds){List<Map<String,Object>> rows=jdbc.queryForList("select b.skill_id,b.version_policy,b.fixed_skill_version_id,b.required,b.sort_order,s.latest_published_version_id from agent_profile_version_skill b join skill s on s.id=b.skill_id where b.agent_profile_version_id=?",profileVersionId);for(Map<String,Object> row:rows){String policy=String.valueOf(row.get("version_policy"));Object resolved="FIXED".equals(policy)?row.get("fixed_skill_version_id"):"LATEST_PUBLISHED".equals(policy)?row.get("latest_published_version_id"):null;if(!(resolved instanceof Number version)){if(Boolean.TRUE.equals(row.get("required")))throw error("AGENT_SKILL_UNRESOLVED","Required Skill cannot be resolved",HttpStatus.CONFLICT);continue;}Integer valid=jdbc.queryForObject("select count(*) from skill_version where id=? and skill_id=? and lifecycle_status in ('PUBLISHED','DEPRECATED')",Integer.class,version.longValue(),row.get("skill_id"));if(valid==0)throw error("AGENT_SKILL_UNRESOLVED","Skill version cannot be frozen",HttpStatus.CONFLICT);jdbc.update("insert into workflow_run_skill_snapshot(time_created,workflow_run_id,agent_profile_version_id,skill_id,skill_version_id,required,sort_order) values(now(3),?,?,?,?,?,?)",runId,profileVersionId,row.get("skill_id"),version.longValue(),row.get("required"),row.get("sort_order"));}}}
    private void assertCanMaintain(AgentProfileEntity profile,Long actor){if(Objects.equals(profile.getOwnerUserId(),actor))return;Integer admin=jdbc.queryForObject("select count(*) from iam_user_role ur join iam_role r on r.id=ur.role_id where ur.user_id=? and r.role_key='ADMIN' and r.status='ACTIVE'",Integer.class,actor);if(admin==null||admin==0)throw error("AGENT_PROFILE_READ_ONLY","Only the owner or an administrator can change this Agent",HttpStatus.FORBIDDEN);}

    private void enqueue(Long workflowId,Long stageId,String node,Long profileVersion,String commandId){Long session=jdbc.queryForObject("select id from agent_workflow_session where stage_run_id=? and node_key=?",Long.class,stageId,node); Integer next=jdbc.queryForObject("select coalesce(max(execution_no),0)+1 from agent_workflow_run where session_id=?",Integer.class,session); jdbc.update("insert into agent_workflow_run(time_created,time_updated,stage_run_id,session_id,node_key,profile_version_id,status,execution_no) values(now(3),now(3),?,?,?,?,'QUEUED',?)",stageId,session,node,profileVersion,next); Long ar=jdbc.queryForObject("select id from agent_workflow_run where session_id=? and execution_no=?",Long.class,session,next); jdbc.update("insert into runtime_command(time_created,time_updated,command_id,command_type,aggregate_type,aggregate_id,payload_json,status) values(now(3),now(3),?,'START_AGENT','AGENT_RUN',?,'{}','PENDING')",commandId+"-"+node+"-"+next,ar);}

    @Transactional public RunView ingestEvent(Long runId, String eventId, String node, String executionStatus, String resultCode, String resultJson, Long actor){return ingestEvent0(runId,eventId,node,executionStatus,resultCode,resultJson,actor);}
    @Transactional public void ingestEventInternal(Long runId, String eventId, String node, String executionStatus, String resultCode, String resultJson){ingestEvent0(runId,eventId,node,executionStatus,resultCode,resultJson,null);}
    private RunView ingestEvent0(Long runId,String eventId,String node,String executionStatus,String resultCode,String resultJson,Long actor){
        Map<String,Object> base=jdbc.queryForMap("select project_id,workflow_code,workflow_version from workflow_run where id=?",runId);
        if(actor!=null)assertMember(((Number)base.get("project_id")).longValue(),actor);
        if(eventId==null||eventId.isBlank())throw error("RUNTIME_EVENT_ID_REQUIRED","Runtime event id is required",HttpStatus.BAD_REQUEST);
        if(jdbc.update("insert ignore into runtime_event_index(time_created,time_updated,provider,event_id,workflow_run_id,event_type) values(now(3),now(3),'OPENHANDS',?,?,?)",eventId,runId,"AGENT_RUN_COMPLETED")==0)return actor==null?null:run(runId,actor);
        Map<String,Object> stage=jdbc.queryForMap("select id,loop_count from stage_run where workflow_run_id=? and stage_key='REQUIREMENT' and status in ('RUNNING','PROVISIONING') order by run_no desc limit 1",runId);
        Long stageId=((Number)stage.get("id")).longValue();
        Long agentRunId=jdbc.queryForObject("select id from agent_workflow_run where stage_run_id=? and node_key=? and status in ('QUEUED','STARTING','RUNNING') order by execution_no desc limit 1",Long.class,stageId,node);
        String finalStatus="SUCCESS".equals(executionStatus)?"SUCCEEDED":"FAILED";
        jdbc.update("update agent_workflow_run set status=?,result_code=?,result_json=?,completed_at=now(3),time_updated=now(3) where id=?",finalStatus,resultCode,resultJson,agentRunId);
        if(!"SUCCESS".equals(executionStatus)){requireHuman(stageId);return actor==null?null:run(runId,actor);}
        JsonNode envelope=parseResult(resultJson);
        requireEnvelope(envelope);
        if("writer".equals(node)) bindOutputArtifacts(runId,stageId,agentRunId,((Number)base.get("project_id")).longValue(),envelope);
        if("reviewer".equals(node)) {
            Long latest=latestRequirementRevision(runId,stageId);
            bindReviewTargets(runId,stageId,agentRunId,envelope);
            if ("APPROVED".equals(resultCode) && ((Number) stage.get("loop_count")).intValue() == 0) {
                if (!envelope.path("issues").isArray() || envelope.path("issues").isEmpty()) {
                    requireHuman(stageId);
                    jdbc.update("update agent_workflow_run set result_code='PREMATURE_APPROVAL',status='FAILED',time_updated=now(3) where id=?",agentRunId);
                    return actor==null?null:run(runId,actor);
                }
                resultCode = "REVISION_REQUIRED";
                jdbc.update("update agent_workflow_run set result_code='REVISION_REQUIRED',time_updated=now(3) where id=?", agentRunId);
            }
            if("APPROVED".equals(resultCode)&&!completion.requirementApproved(envelope,latest)){requireHuman(stageId);jdbc.update("update agent_workflow_run set result_code='INVALID_REVIEW_TARGET',status='FAILED',time_updated=now(3) where id=?",agentRunId);return actor==null?null:run(runId,actor);}
        }
        List<EdgeView> edges=jdbc.query("select target.node_key,e.increments_loop,json_unquote(json_extract(e.condition_json,'$.type')),json_unquote(json_extract(e.condition_json,'$.field')),coalesce(json_unquote(json_extract(e.condition_json,'$.operator')),'EQ'),json_unquote(json_extract(e.condition_json,'$.value')) from stage_agent_edge_def e join stage_agent_node_def source on source.id=e.from_node_id left join stage_agent_node_def target on target.id=e.to_node_id join workflow_stage_def d on d.id=e.stage_def_id join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT' and source.node_key=? order by e.priority",(rs,n)->new EdgeView(rs.getString(1),rs.getBoolean(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)),base.get("workflow_code"),base.get("workflow_version"),node);
        String evaluatedResultCode = resultCode;
        EdgeView matched=edges.stream().filter(e->StructuredEdgeEvaluator.matches(e.type(),e.field(),e.operator(),e.value(),evaluatedResultCode,finalStatus)).findFirst().orElse(null);
        if(matched==null){requireHuman(stageId);return actor==null?null:run(runId,actor);}
        int loopCount=((Number)stage.get("loop_count")).intValue()+(matched.incrementsLoop()?1:0);
        Integer maxLoop=jdbc.queryForObject("select d.max_loop_count from workflow_stage_def d join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id where t.code=? and v.version_no=? and d.stage_key='REQUIREMENT'",Integer.class,base.get("workflow_code"),base.get("workflow_version"));
        if(matched.incrementsLoop()&&loopCount>(maxLoop==null?0:maxLoop)){jdbc.update("update stage_run set loop_count=?,status='HUMAN_REQUIRED',time_updated=now(3) where id=?",loopCount,stageId);return actor==null?null:run(runId,actor);}
        if(matched.nextNode()==null){Long latest=latestRequirementRevision(runId,stageId);if(!completion.requirementApproved(envelope,latest)){requireHuman(stageId);return actor==null?null:run(runId,actor);}jdbc.update("update stage_run set loop_count=?,status='COMPLETED',completed_at=now(3),time_updated=now(3) where id=?",loopCount,stageId);jdbc.update("update workflow_run set status='WAITING_DESIGN_ACCEPTANCE',time_updated=now(3) where id=?",runId);}
        else {jdbc.update("update stage_run set loop_count=?,status='RUNNING',time_updated=now(3) where id=?",loopCount,stageId);Long pv=jdbc.queryForObject("select profile_version_id from agent_workflow_session where stage_run_id=? and node_key=?",Long.class,stageId,matched.nextNode());enqueue(runId,stageId,matched.nextNode(),pv,UUID.randomUUID().toString());}
        return actor==null?null:run(runId,actor);
    }
    private void requireHuman(Long stageId){jdbc.update("update stage_run set status='HUMAN_REQUIRED',time_updated=now(3) where id=?",stageId);}
    private JsonNode parseResult(String value){try{return json.readTree(value==null?"{}":value);}catch(Exception failure){throw error("AGENT_RESULT_INVALID","Agent result is not valid JSON",HttpStatus.UNPROCESSABLE_ENTITY);}}
    private void requireEnvelope(JsonNode value){for(String field:List.of("executionStatus","resultCode","summary","artifacts","reviewedArtifactRevisionIds","issues","blockingIssues","metrics"))if(!value.has(field))throw error("AGENT_RESULT_SCHEMA_INVALID","Agent result is missing "+field,HttpStatus.UNPROCESSABLE_ENTITY);}
    private void bindOutputArtifacts(Long workflowId,Long stageId,Long agentRunId,Long projectId,JsonNode envelope){for(JsonNode artifact:envelope.path("artifacts")){if(!"REQUIREMENT".equalsIgnoreCase(artifact.path("artifactType").asText()))continue;long documentId=artifact.path("documentId").asLong();long revisionId=artifact.path("revisionId").asLong();Integer valid=jdbc.queryForObject("select count(*) from project_document_revision r join project_document d on d.id=r.document_id where r.id=? and d.id=? and d.project_id=? and d.document_type='REQUIREMENT'",Integer.class,revisionId,documentId,projectId);if(valid==null||valid==0)throw error("ARTIFACT_REVISION_INVALID","Requirement artifact revision does not belong to this project",HttpStatus.UNPROCESSABLE_ENTITY);jdbc.update("insert ignore into workflow_artifact_binding(time_created,workflow_run_id,stage_run_id,agent_run_id,artifact_kind,project_document_id,project_document_revision_id,relation_type) values(now(3),?,?,?,?,?,?, 'OUTPUT')",workflowId,stageId,agentRunId,"REQUIREMENT",documentId,revisionId);}}
    private void bindReviewTargets(Long workflowId,Long stageId,Long agentRunId,JsonNode envelope){for(JsonNode revision:envelope.path("reviewedArtifactRevisionIds")){if(!revision.canConvertToLong())continue;Long revisionId=revision.asLong();List<Map<String,Object>> target=jdbc.queryForList("select project_document_id from workflow_artifact_binding where workflow_run_id=? and stage_run_id=? and artifact_kind='REQUIREMENT' and project_document_revision_id=? and relation_type='OUTPUT'",workflowId,stageId,revisionId);if(target.isEmpty())throw error("REVIEW_TARGET_INVALID","Reviewer target is not a generated Requirement revision",HttpStatus.UNPROCESSABLE_ENTITY);jdbc.update("insert ignore into workflow_artifact_binding(time_created,workflow_run_id,stage_run_id,agent_run_id,artifact_kind,project_document_id,project_document_revision_id,relation_type) values(now(3),?,?,?,?,?,?,'REVIEW_TARGET')",workflowId,stageId,agentRunId,"REQUIREMENT",target.get(0).get("project_document_id"),revisionId);}}
    private Long latestRequirementRevision(Long workflowId,Long stageId){List<Long> values=jdbc.query("select b.project_document_revision_id from workflow_artifact_binding b join project_document_revision r on r.id=b.project_document_revision_id where b.workflow_run_id=? and b.stage_run_id=? and b.artifact_kind='REQUIREMENT' and b.relation_type='OUTPUT' order by r.revision_no desc,b.id desc limit 1",(rs,n)->rs.getLong(1),workflowId,stageId);return values.isEmpty()?null:values.get(0);}
    @Transactional(readOnly=true) public RunView run(Long id,Long actor){Map<String,Object> r=jdbc.queryForMap("select id,project_id,workflow_code,workflow_version,status,started_at,completed_at,initial_request from workflow_run where id=?",id);Long projectId=((Number)r.get("project_id")).longValue();assertMember(projectId,actor);String workflowCode=String.valueOf(r.get("workflow_code"));int workflowVersion=((Number)r.get("workflow_version")).intValue();List<StageView> stages=jdbc.query("select sr.id,sr.stage_key,coalesce(d.name,sr.stage_key),sr.status,sr.loop_count,coalesce(d.max_loop_count,0) from stage_run sr left join workflow_template t on t.code=? left join workflow_template_version v on v.workflow_template_id=t.id and v.version_no=? left join workflow_stage_def d on d.workflow_version_id=v.id and d.stage_key=sr.stage_key where sr.workflow_run_id=? and sr.run_no=(select max(x.run_no) from stage_run x where x.workflow_run_id=sr.workflow_run_id and x.stage_key=sr.stage_key) order by sr.id",(rs,n)->stage(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6)),workflowCode,workflowVersion,id);return new RunView(id,projectId,workflowCode,workflowVersion,String.valueOf(r.get("status")),String.valueOf(r.get("initial_request")),r.get("started_at"),r.get("completed_at"),stages);}
    private StageView stage(Long id,String key,String name,String status,int loopCount,int maxLoopCount){List<AgentNodeView> agents=jdbc.query("select s.id,s.node_key,coalesce(n.name,s.node_key),coalesce((select r.status from agent_workflow_run r where r.session_id=s.id order by r.execution_no desc limit 1),s.status),n.node_type,p.code,(select r.id from agent_workflow_run r where r.session_id=s.id order by r.execution_no desc limit 1),(select r.execution_no from agent_workflow_run r where r.session_id=s.id order by r.execution_no desc limit 1) from agent_workflow_session s left join stage_agent_node_def n on n.stage_def_id=(select d.id from workflow_stage_def d join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id join workflow_run wr on wr.workflow_code=t.code and wr.workflow_version=v.version_no join stage_run sr on sr.workflow_run_id=wr.id and sr.stage_key=d.stage_key where sr.id=s.stage_run_id) and n.node_key=s.node_key left join agent_profile_version v on v.id=s.profile_version_id left join agent_profile p on p.id=v.agent_profile_id where s.stage_run_id=? order by n.sort_order",(rs,n)->new AgentNodeView(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getObject(7,Long.class),rs.getObject(8,Integer.class)),id);String current=agents.stream().filter(a->Set.of("QUEUED","STARTING","RUNNING","WAITING_HUMAN","PAUSED").contains(a.status())).map(AgentNodeView::name).findFirst().orElse(null);List<ArtifactView> artifacts=jdbc.query("select b.project_document_id,b.project_document_revision_id,d.title,r.revision_no,d.status from workflow_artifact_binding b join project_document d on d.id=b.project_document_id join project_document_revision r on r.id=b.project_document_revision_id where b.stage_run_id=? and b.relation_type='OUTPUT' order by r.revision_no desc",(rs,n)->new ArtifactView(rs.getLong(1),rs.getString(3),rs.getInt(4),rs.getLong(2),rs.getString(5),reviewIssues(id,rs.getLong(2))),id);List<StageEdgeView> edges=stageEdges(id);return new StageView(id,key,name,status,current,loopCount,maxLoopCount,"HUMAN_REQUIRED".equals(status),agents,artifacts,edges);}
    /** 阶段内 agent 协作边（含顺序与 reviewer→writer 驳回返工环），来自 stage_agent_edge_def 权威定义；to=null 表示该边使阶段完成（如 reviewer APPROVED）。 */
    private List<StageEdgeView> stageEdges(Long stageRunId){return jdbc.query("select source.node_key,target.node_key,e.edge_type,e.increments_loop,json_unquote(json_extract(e.condition_json,'$.value')) from stage_agent_edge_def e join stage_agent_node_def source on source.id=e.from_node_id left join stage_agent_node_def target on target.id=e.to_node_id where e.stage_def_id=(select d.id from workflow_stage_def d join workflow_template_version v on v.id=d.workflow_version_id join workflow_template t on t.id=v.workflow_template_id join workflow_run wr on wr.workflow_code=t.code and wr.workflow_version=v.version_no join stage_run sr on sr.workflow_run_id=wr.id and sr.stage_key=d.stage_key where sr.id=?) order by e.priority,e.id",(rs,n)->new StageEdgeView(rs.getString(1),rs.getString(2),rs.getString(3),rs.getBoolean(4),rs.getString(5)),stageRunId);}
    private List<String> reviewIssues(Long stageId,Long revisionId){List<String> results=jdbc.query("select ar.result_json from agent_workflow_run ar join workflow_artifact_binding b on b.agent_run_id=ar.id and b.relation_type='REVIEW_TARGET' where ar.stage_run_id=? and b.project_document_revision_id=? order by ar.id desc limit 1",(rs,n)->rs.getString(1),stageId,revisionId);if(results.isEmpty())return List.of();JsonNode issues=parseResult(results.get(0)).path("issues");List<String> values=new ArrayList<>();for(JsonNode issue:issues)values.add(issue.path("message").asText(issue.toString()));return values;}
    /** 每个项目组只允许一个工作流 run：返回该项目当前（最新一个）run，不存在则 404。 */
    @Transactional(readOnly=true) public RunView current(String projectKey,Long actor){Long projectId=projectId(projectKey); assertMember(projectId,actor); Long runId=latestRunId(projectId); if(runId==null) throw error("WORKFLOW_RUN_NOT_FOUND","Project has no workflow run yet",HttpStatus.NOT_FOUND); return run(runId,actor);}
    /** 项目唯一 run 的 id；永远只有一次 run，取最新一条（历史数据可能有多条，新逻辑保证只会有一个）。 */
    private Long latestRunId(Long projectId){List<Long> ids=jdbc.query("select id from workflow_run where project_id=? order by id desc limit 1",(rs,n)->rs.getLong(1),projectId);return ids.isEmpty()?null:ids.get(0);}
    @Transactional public InterventionView intervene(Long runId,Long actor,InterventionCommand c){Map<String,Object> r=jdbc.queryForMap("select project_id from workflow_run where id=?",runId);assertMember(((Number)r.get("project_id")).longValue(),actor);jdbc.update("insert into human_intervention(time_created,time_updated,workflow_run_id,user_id,intervention_type,content,status) values(now(3),now(3),?,?,?,?,'CREATED')",runId,actor,c.type(),c.content());Long id=jdbc.queryForObject("select id from human_intervention where workflow_run_id=? and user_id=? order by id desc limit 1",Long.class,runId,actor);return new InterventionView(id,c.type(),"CREATED");}
    @Transactional public RunView accept(Long runId,Long actor,String decision,String comment){return designAcceptance(runId,actor,"ACCEPTED".equals(decision)?"ACCEPT":"REWORK","REQUIREMENT",comment);}
    @Transactional public RunView designAcceptance(Long runId,Long actor,String decision,String targetStageKey,String comment){Map<String,Object> r=jdbc.queryForMap("select project_id,status,workflow_code,workflow_version,initial_request,context_snapshot_json,project_agent_configuration_id from workflow_run where id=?",runId);assertMember(((Number)r.get("project_id")).longValue(),actor);if(!Set.of("ACCEPT","REWORK").contains(decision))throw error("ACCEPTANCE_DECISION_INVALID","Decision must be ACCEPT or REWORK",HttpStatus.BAD_REQUEST);if("ACCEPT".equals(decision)&&!"WAITING_DESIGN_ACCEPTANCE".equals(r.get("status")))throw error("WORKFLOW_NOT_READY_FOR_ACCEPTANCE","Requirement must be approved by the Agent reviewer first",HttpStatus.CONFLICT);jdbc.update("insert into workflow_final_acceptance(time_created,time_updated,workflow_run_id,accepted_by,decision,comment) values(now(3),now(3),?,?,?,?) on duplicate key update accepted_by=values(accepted_by),decision=values(decision),comment=values(comment),time_updated=now(3)",runId,actor,decision,comment);if("ACCEPT".equals(decision)){jdbc.update("update workflow_run set status='DESIGN_COMPLETED',completed_at=now(3),time_updated=now(3) where id=?",runId);}else{if(targetStageKey!=null&&!"REQUIREMENT".equalsIgnoreCase(targetStageKey))throw error("REWORK_STAGE_INVALID","P1 only supports Requirement rework",HttpStatus.BAD_REQUEST);jdbc.update("update workflow_run set status='RUNNING',completed_at=null,time_updated=now(3) where id=?",runId);Long configurationId=(Long)r.get("project_agent_configuration_id");Map<String,Long> bindings=configurationId==null?Map.of():configurationBindings(configurationId);createRequirementStage(runId,new RunCommand(String.valueOf(r.get("workflow_code")),((Number)r.get("workflow_version")).intValue(),bindings,String.valueOf(r.get("initial_request")),String.valueOf(r.get("context_snapshot_json"))),UUID.randomUUID().toString());}return run(runId,actor);}
    private List<VersionView> versions(Long id){return jdbc.query("select id,version_no,status,model_code,temperature,max_iteration_per_run,timeout_seconds,published_at,system_prompt,output_schema_json,runtime_config_json from agent_profile_version where agent_profile_id=? order by version_no desc",(rs,n)->{Long v=rs.getLong(1);List<SkillBindingView> skills=jdbc.query("select b.skill_id,s.skill_key,s.display_name,b.version_policy,b.fixed_skill_version_id,coalesce(fv.version,lv.version),b.required,b.sort_order from agent_profile_version_skill b join skill s on s.id=b.skill_id left join skill_version fv on fv.id=b.fixed_skill_version_id left join skill_version lv on lv.id=s.latest_published_version_id where b.agent_profile_version_id=? order by b.sort_order",(x,m)->new SkillBindingView(x.getLong(1),x.getString(2),x.getString(3),x.getString(4),x.getObject(5,Long.class),x.getString(6),x.getBoolean(7),x.getInt(8)),v);List<ToolBinding> tools=jdbc.query("select tool_code,enabled,permission_mode,config_json from agent_profile_version_tool where agent_profile_version_id=? order by tool_code",(x,m)->new ToolBinding(x.getString(1),x.getBoolean(2),x.getString(3),x.getString(4)),v);return new VersionView(v,rs.getInt(2),rs.getString(3),rs.getString(4),rs.getObject(5,Double.class),rs.getInt(6),rs.getInt(7),rs.getTimestamp(8)==null?null:rs.getTimestamp(8).toInstant(),rs.getString(9),rs.getString(10),rs.getString(11),skills,tools);},id);}
    private VersionView version(Long id,int no){return versions(id).stream().filter(v->v.versionNo()==no).findFirst().orElseThrow();}
    @Transactional public InterventionView interveneWithCommand(Long runId,Long actor,InterventionCommand c){Map<String,Object> workflow=jdbc.queryForMap("select project_id from workflow_run where id=?",runId);assertMember(((Number)workflow.get("project_id")).longValue(),actor);String commandType=switch(c.type()){case "ASK"->"ASK_AGENT";case "CORRECT","PROVIDE_INFO"->"SEND_MESSAGE";case "PAUSE"->"PAUSE_AGENT";case "RESUME"->"RESUME_AGENT";case "CANCEL"->"CANCEL_AGENT";case "RETRY"->"START_AGENT";default->throw error("INTERVENTION_TYPE_INVALID","Unsupported intervention type",HttpStatus.BAD_REQUEST);};List<Map<String,Object>> candidates=jdbc.queryForList("select ar.id agent_run_id,ar.stage_run_id,ar.session_id,ar.node_key,ar.profile_version_id from agent_workflow_run ar join stage_run sr on sr.id=ar.stage_run_id where sr.workflow_run_id=? and (? is null or sr.id=?) and (? is null or ar.session_id=?) and (? is null or ar.id=?) order by ar.id desc limit 1",runId,c.stageRunId(),c.stageRunId(),c.agentSessionId(),c.agentSessionId(),c.agentRunId(),c.agentRunId());if(candidates.isEmpty())throw error("INTERVENTION_TARGET_NOT_FOUND","Target Agent run was not found",HttpStatus.NOT_FOUND);Map<String,Object> target=candidates.get(0);Long stageId=((Number)target.get("stage_run_id")).longValue(),sessionId=((Number)target.get("session_id")).longValue(),agentRunId=((Number)target.get("agent_run_id")).longValue();jdbc.update("insert into human_intervention(time_created,time_updated,workflow_run_id,stage_run_id,agent_session_id,agent_run_id,user_id,intervention_type,content,status) values(now(3),now(3),?,?,?,?,?,?,?,'CREATED')",runId,stageId,sessionId,agentRunId,actor,c.type(),c.content());Long iid=jdbc.queryForObject("select id from human_intervention where workflow_run_id=? and user_id=? order by id desc limit 1",Long.class,runId,actor);String commandId=UUID.randomUUID().toString();if("RETRY".equals(c.type())){jdbc.update("update stage_run set status='RUNNING',time_updated=now(3) where id=?",stageId);jdbc.update("update workflow_run set status='RUNNING',time_updated=now(3) where id=?",runId);jdbc.update("update agent_workflow_session set runtime_conversation_id=null,time_updated=now(3) where id=?",sessionId);enqueue(runId,stageId,String.valueOf(target.get("node_key")),((Number)target.get("profile_version_id")).longValue(),commandId);}else{jdbc.update("insert into runtime_command(time_created,time_updated,command_id,command_type,aggregate_type,aggregate_id,payload_json,status) values(now(3),now(3),?,?,'AGENT_RUN',?,?, 'PENDING')",commandId,commandType,agentRunId,writeJson(Map.of("interventionId",iid,"content",c.content()==null?"":c.content())));}Long commandDbId=jdbc.queryForObject("select id from runtime_command where command_id like ? order by id desc limit 1",Long.class,commandId+"%");jdbc.update("update human_intervention set runtime_command_id=? where id=?",commandDbId,iid);return new InterventionView(iid,c.type(),"CREATED");}
    @Transactional public VersionView updateDraft(String code,int no,VersionCommand c,Long actor){AgentProfileEntity p=profiles.findByCode(code).orElseThrow(()->error("AGENT_PROFILE_NOT_FOUND","Agent profile not found",HttpStatus.NOT_FOUND));assertCanMaintain(p,actor);Map<String,Object> row=jdbc.queryForMap("select id,status from agent_profile_version where agent_profile_id=? and version_no=?",p.getId(),no);if(!"DRAFT".equals(row.get("status")))throw error("AGENT_VERSION_IMMUTABLE","Only a DRAFT version can be edited",HttpStatus.CONFLICT);if(c.systemPrompt()==null||c.systemPrompt().isBlank()||c.modelCode()==null||c.modelCode().isBlank())throw error("AGENT_VERSION_INVALID","System prompt and model are required",HttpStatus.BAD_REQUEST);Long id=((Number)row.get("id")).longValue();jdbc.update("update agent_profile_version set system_prompt=?,model_code=?,temperature=?,max_iteration_per_run=?,timeout_seconds=?,output_schema_json=?,runtime_config_json=?,changelog=?,time_updated=now(3) where id=?",c.systemPrompt(),c.modelCode(),c.temperature(),c.maxIterationPerRun(),c.timeoutSeconds(),c.outputSchemaJson(),c.runtimeConfigJson(),c.changelog(),id);jdbc.update("delete from agent_profile_version_skill where agent_profile_version_id=?",id);if(c.skills()!=null)for(SkillBinding s:c.skills())jdbc.update("insert into agent_profile_version_skill(time_created,time_updated,agent_profile_version_id,skill_id,version_policy,fixed_skill_version_id,required,sort_order) values(now(3),now(3),?,?,?,?,?,?)",id,s.skillId(),s.versionPolicy(),s.fixedSkillVersionId(),s.required(),s.sortOrder());jdbc.update("delete from agent_profile_version_tool where agent_profile_version_id=?",id);if(c.tools()!=null)for(ToolBinding t:c.tools())jdbc.update("insert into agent_profile_version_tool(time_created,time_updated,agent_profile_version_id,tool_code,enabled,permission_mode,config_json) values(now(3),now(3),?,?,?,?,?)",id,t.toolCode(),t.enabled(),t.permissionMode(),t.configJson());return version(p.getId(),no);}
    private Long projectId(String key){return projects.findByProjectKey(key).map(x->x.getId()).orElseThrow(()->error("PROJECT_NOT_FOUND","Project not found",HttpStatus.NOT_FOUND));}
    private String jsonOrEmpty(String value){if(value==null||value.isBlank())return "[]";try{json.readTree(value);return value;}catch(Exception failure){throw error("CONTEXT_SNAPSHOT_INVALID","Context snapshot must be valid JSON",HttpStatus.BAD_REQUEST);}}
    private String writeJson(Object value){try{return json.writeValueAsString(value);}catch(Exception failure){throw new IllegalStateException("Cannot serialize workflow payload",failure);}}
    private void assertMember(Long p,Long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project_member where project_id=? and user_id=? and status='ACTIVE' and membership_type in ('OWNER','MEMBER')",Integer.class,p,u);if(n==null||n==0)throw error("PROJECT_ACCESS_FORBIDDEN","Project membership required",HttpStatus.FORBIDDEN);}
    private BusinessException error(String c,String m,HttpStatus s){return new BusinessException(c,m,s);}
    public record ProfileCommand(String code,String name,String category,String description){} public record SkillBinding(Long skillId,String versionPolicy,Long fixedSkillVersionId,boolean required,int sortOrder){} public record VersionCommand(String systemPrompt,String modelCode,Double temperature,Integer maxIterationPerRun,Integer timeoutSeconds,String outputSchemaJson,String runtimeConfigJson,String changelog,List<SkillBinding> skills,List<ToolBinding> tools){} public record ToolBinding(String toolCode,boolean enabled,String permissionMode,String configJson){} public record RunCommand(String workflowCode,int workflowVersion,Map<String,Long> profileBindings,String initialRequest,String contextSnapshotJson){} public record InterventionCommand(String type,String content,Long stageRunId,Long agentSessionId,Long agentRunId){}
    private record EdgeView(String nextNode,boolean incrementsLoop,String type,String field,String operator,String value){}
    public record ProfileView(Long id,String code,String name,String category,String description,String status,String maintainer,String sourceType,Long ownerUserId,boolean systemLocked,Long derivedFromProfileVersionId,List<VersionView> versions){} public record SkillBindingView(Long skillId,String skillKey,String name,String versionPolicy,Long fixedSkillVersionId,String version,boolean required,int sortOrder){} public record VersionView(Long id,int versionNo,String status,String modelCode,Double temperature,int maxIterationPerRun,int timeoutSeconds,Instant publishedAt,String systemPrompt,String outputSchemaJson,String runtimeConfigJson,List<SkillBindingView> skills,List<ToolBinding> tools){} public record RunView(Long id,Long projectId,String workflowCode,int workflowVersion,String status,String initialRequest,Object startedAt,Object completedAt,List<StageView> stages){} public record StageView(Long id,String key,String name,String status,String currentAgent,int loopCount,int maxLoopCount,boolean attention,List<AgentNodeView> agents,List<ArtifactView> artifacts,List<StageEdgeView> edges){} public record StageEdgeView(String from,String to,String edgeType,boolean incrementsLoop,String conditionValue){} public record AgentNodeView(Long id,String key,String name,String status,String nodeType,String profileCode,Long agentRunId,Integer executionNo){} public record ArtifactView(Long id,String name,int revision,Long revisionId,String status,List<String> reviewIssues){} public record InterventionView(Long id,String type,String status){}
}
