package com.company.skillplatform.agentworkflow.application;

import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.project.infrastructure.repository.VirtualProjectRepository;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ProjectAgentConfigurationService {
 private final JdbcTemplate jdbc; private final VirtualProjectRepository projects;
 public ProjectAgentConfigurationService(JdbcTemplate jdbc,VirtualProjectRepository projects){this.jdbc=jdbc;this.projects=projects;}
 @Transactional public ConfigurationView get(String projectKey,Long actor){Long p=project(projectKey);read(p,actor);List<Map<String,Object>> rows=jdbc.queryForList("select id,status,source_type,config_hash,version_no,workflow_template_version_id from project_agent_configuration where project_id=?",p);if(rows.isEmpty()){Long preset=jdbc.queryForObject("select id from agent_team_preset_version where status='PUBLISHED' order by id limit 1",Long.class);apply0(p,actor,preset);rows=jdbc.queryForList("select id,status,source_type,config_hash,version_no,workflow_template_version_id from project_agent_configuration where project_id=?",p);}return view(rows.get(0),p);}
 @Transactional public ConfigurationView applyPreset(String projectKey,Long actor,Long preset){Long p=project(projectKey);write(p,actor);apply0(p,actor,preset);return get(projectKey,actor);}
 @Transactional public ValidationView validate(String projectKey,Long actor){Long p=project(projectKey);write(p,actor);Map<String,Object> c=config(p);List<Map<String,Object>> nodes=jdbc.queryForList("select n.stage_key,n.node_key,v.status,n.agent_profile_version_id from project_agent_configuration_node n join agent_profile_version v on v.id=n.agent_profile_version_id where n.configuration_id=?",c.get("id"));List<String> errors=new ArrayList<>();for(Map<String,Object> n:nodes)if(!"PUBLISHED".equals(n.get("status")))errors.add(n.get("stage_key")+"/"+n.get("node_key")+" must use PUBLISHED profile");if(nodes.isEmpty())errors.add("No agent nodes configured");if(errors.isEmpty())jdbc.update("update project_agent_configuration set status='READY',config_hash=?,time_updated=now(3) where id=?",hash(nodes),c.get("id"));return new ValidationView(errors,List.of(),errors.isEmpty());}
 @Transactional public ConfigurationView confirm(String projectKey,Long actor){Long p=project(projectKey);write(p,actor);Map<String,Object> c=config(p);if(!"READY".equals(c.get("status")))throw error("AGENT_CONFIG_NOT_READY","Validate configuration before confirming",HttpStatus.CONFLICT);jdbc.update("update project_agent_configuration set status='LOCKED',confirmed_by=?,confirmed_at=now(3),updated_by=?,time_updated=now(3) where id=?",actor,actor,c.get("id"));return get(projectKey,actor);}
 @Transactional public ConfigurationView copy(String target,String source,Long actor){Long tp=project(target),sp=project(source);write(tp,actor);read(sp,actor);Map<String,Object> sc=config(sp);if(!Set.of("READY","LOCKED").contains(sc.get("status")))throw error("SOURCE_CONFIG_NOT_READY","Source configuration is not reusable",HttpStatus.CONFLICT);Long preset=jdbc.queryForObject("select id from agent_team_preset_version where id=?",Long.class,sc.get("source_preset_version_id"));apply0(tp,actor,preset);return get(target,actor);}
 private void apply0(Long p,Long actor,Long preset){Map<String,Object> pv=jdbc.queryForMap("select id,workflow_template_version_id from agent_team_preset_version where id=? and status='PUBLISHED'",preset);List<Map<String,Object>> old=jdbc.queryForList("select id from project_agent_configuration where project_id=?",p);Long id;if(!old.isEmpty()&&"LOCKED".equals(jdbc.queryForObject("select status from project_agent_configuration where id=?",String.class,old.get(0).get("id")) )){jdbc.update("update project_agent_configuration set status='DRAFT',version_no=version_no+1,updated_by=?,time_updated=now(3) where id=?",actor,old.get(0).get("id"));id=((Number)old.get(0).get("id")).longValue();jdbc.update("delete from project_agent_configuration_node where configuration_id=?",id);}else if(old.isEmpty()){jdbc.update("insert into project_agent_configuration(time_created,time_updated,project_id,workflow_template_version_id,source_type,source_preset_version_id,status,created_by,updated_by) values(now(3),now(3),?,?,?,'SYSTEM_PRESET','DRAFT',?,?)",p,pv.get("workflow_template_version_id"),preset,actor,actor);id=jdbc.queryForObject("select id from project_agent_configuration where project_id=?",Long.class,p);}else{id=((Number)old.get(0).get("id")).longValue();jdbc.update("delete from project_agent_configuration_node where configuration_id=?",id);}jdbc.update("insert into project_agent_configuration_node(time_created,time_updated,configuration_id,stage_key,node_key,agent_profile_version_id) select now(3),now(3),?,?,node_key,agent_profile_version_id from agent_team_preset_node_binding where preset_version_id=?",id,"REQUIREMENT",preset);}
 private ConfigurationView view(Map<String,Object> c,Long p){List<NodeView> nodes=jdbc.query("select stage_key,node_key,agent_profile_version_id from project_agent_configuration_node where configuration_id=? order by stage_key,node_key",(r,n)->new NodeView(r.getString(1),r.getString(2),r.getLong(3)),c.get("id"));return new ConfigurationView(((Number)c.get("id")).longValue(),p,String.valueOf(c.get("status")),String.valueOf(c.get("source_type")),(String)c.get("config_hash"),((Number)c.get("version_no")).intValue(),nodes);}
 private Map<String,Object> config(Long p){return jdbc.queryForMap("select id,status,source_type,source_preset_version_id,config_hash,version_no from project_agent_configuration where project_id=?",p);}
 private Long project(String k){return projects.findByProjectKey(k).map(x->x.getId()).orElseThrow(()->error("PROJECT_NOT_FOUND","Project not found",HttpStatus.NOT_FOUND));}
 private void read(Long p,Long u){member(p,u);}
 private void write(Long p,Long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project_member where project_id=? and user_id=? and status='ACTIVE' and membership_type='OWNER'",Integer.class,p,u);if(n==null||n==0)throw error("PROJECT_CONFIG_WRITE_FORBIDDEN","Only project OWNER can configure agents",HttpStatus.FORBIDDEN);}
 private void member(Long p,Long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project_member where project_id=? and user_id=? and status='ACTIVE'",Integer.class,p,u);if(n==null||n==0)throw error("PROJECT_ACCESS_FORBIDDEN","Project membership required",HttpStatus.FORBIDDEN);}
 private String hash(List<Map<String,Object>> n){try{String s=n.stream().sorted(Comparator.comparing(x->x.get("stage_key")+"/"+x.get("node_key"))).map(x->x.get("stage_key")+"/"+x.get("node_key")+"/"+x.get("agent_profile_version_id")).reduce("",String::concat);byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder o=new StringBuilder();for(byte x:b)o.append(String.format("%02x",x));return o.toString();}catch(Exception e){throw new IllegalStateException(e);}}
 private BusinessException error(String c,String m,HttpStatus s){return new BusinessException(c,m,s);}
 public record ConfigurationView(Long id,Long projectId,String status,String sourceType,String configHash,int versionNo,List<NodeView> nodes){} public record NodeView(String stageKey,String nodeKey,Long agentProfileVersionId){} public record ValidationView(List<String> errors,List<String> warnings,boolean valid){}
}
