package com.company.skillplatform.agentworkflow.application;
import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.project.infrastructure.repository.VirtualProjectRepository;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ProjectAgentConfigurationService {
 private final JdbcTemplate jdbc;private final VirtualProjectRepository projects;private final ResolvedSkillService resolvedSkills;public ProjectAgentConfigurationService(JdbcTemplate j,VirtualProjectRepository p,ResolvedSkillService r){jdbc=j;projects=p;resolvedSkills=r;}
 @Transactional public ConfigurationView get(String k,Long u){long p=project(k);read(p,u);List<Map<String,Object>> x=jdbc.queryForList("select id from project_agent_configuration where project_id=? order by version_no desc limit 1",p);if(x.isEmpty()){createFromPreset(p,u,jdbc.queryForObject("select v.id from agent_team_preset_version v join agent_team_preset t on t.id=v.preset_id where v.status='PUBLISHED' and t.status='ACTIVE' order by t.is_default desc,v.version_no desc limit 1",Long.class));}return view(config(p),p);}
 @Transactional public ConfigurationView applyPreset(String k,Long u,Long preset){long p=project(k);write(p,u);createFromPreset(p,u,preset);return view(config(p),p);}
 @Transactional public ValidationView validate(String k,Long u){long p=project(k);write(p,u);Map<String,Object> c=config(p);List<Map<String,Object>> n=nodes(c.get("id"));List<String> e=new ArrayList<>();for(Map<String,Object> z:n){String key=z.get("stage_key")+"/"+z.get("node_key");if(!"PUBLISHED".equals(z.get("status")))e.add(key+" is not PUBLISHED");if(!"ACTIVE".equals(z.get("profile_status")))e.add(key+" profile is not ACTIVE");if(String.valueOf(z.get("system_prompt")).isBlank()||String.valueOf(z.get("model_code")).isBlank())e.add(key+" prompt/model is missing");try{resolvedSkills.resolve(((Number)z.get("agent_profile_version_id")).longValue());}catch(RuntimeException failure){e.add(key+" skills cannot be resolved: "+failure.getMessage());}}Integer missing=jdbc.queryForObject("select count(*) from workflow_stage_def d join stage_agent_node_def nd on nd.stage_def_id=d.id where d.workflow_version_id=? and not exists(select 1 from project_agent_configuration_node cn where cn.configuration_id=? and cn.stage_key=d.stage_key and cn.node_key=nd.node_key)",Integer.class,c.get("workflow_template_version_id"),c.get("id"));if(missing!=null&&missing>0)e.add(missing+" required workflow nodes are not configured");if(n.isEmpty())e.add("No agent nodes configured");if(e.isEmpty())jdbc.update("update project_agent_configuration set status='READY',config_hash=?,time_updated=now(3) where id=?",hash(c.get("workflow_template_version_id"),n),c.get("id"));return new ValidationView(e.isEmpty(),e,List.of(new CheckView("所有 Workflow Node 已配置",missing!=null&&missing==0),new CheckView("所有 Agent Version 已发布",e.stream().noneMatch(x->x.contains("PUBLISHED"))),new CheckView("所有 Skill 可解析",e.stream().noneMatch(x->x.contains("skills cannot be resolved")))));}
 @Transactional public ConfigurationView confirm(String k,Long u){long p=project(k);write(p,u);Map<String,Object> c=config(p);if(!"READY".equals(c.get("status")))throw error("AGENT_CONFIG_NOT_READY","Configuration must be READY",HttpStatus.CONFLICT);jdbc.update("update project_agent_configuration set confirmed_by=?,confirmed_at=now(3),updated_by=?,time_updated=now(3) where id=? and status='READY'",u,u,c.get("id"));return view(config(p),p);}
 @Transactional public ConfigurationView copy(String target,String source,Long u){long tp=project(target),sp=project(source);write(tp,u);read(sp,u);Map<String,Object> s=config(sp);if(!Set.of("READY","LOCKED").contains(s.get("status")))throw error("SOURCE_CONFIG_NOT_READY","Source configuration is not reusable",HttpStatus.CONFLICT);Long id=newDraft(tp,u,((Number)s.get("workflow_template_version_id")).longValue(),"PROJECT_COPY",null,sp);cloneNodes(s.get("id"),id);return view(config(tp),tp);}
 @Transactional public ConfigurationView replaceNode(String k,Long u,String stage,String node,Long profile){long p=project(k);write(p,u);Map<String,Object> c=config(p);if("LOCKED".equals(c.get("status"))){Long id=newDraft(p,u,((Number)c.get("workflow_template_version_id")).longValue(),"CUSTOM",null,null);cloneNodes(c.get("id"),id);c=configById(id);}else if("READY".equals(c.get("status")))jdbc.update("update project_agent_configuration set status='DRAFT',config_hash=null,confirmed_by=null,confirmed_at=null,time_updated=now(3) where id=?",c.get("id"));jdbc.update("delete from project_agent_configuration_node where configuration_id=? and stage_key=? and node_key=?",c.get("id"),stage,node);jdbc.update("insert into project_agent_configuration_node(time_created,time_updated,configuration_id,stage_key,node_key,agent_profile_version_id) values(now(3),now(3),?,?,?,?)",c.get("id"),stage,node,profile);return view(config(p),p);}
 @Transactional(readOnly=true) public List<ReusableProject> reusable(Long u){return jdbc.query("select p.project_key,p.project_name,c.status,c.config_hash,c.version_no from virtual_project p join virtual_project_member m on m.project_id=p.id and m.user_id=? and m.status='ACTIVE' join project_agent_configuration c on c.project_id=p.id and c.version_no=(select max(x.version_no) from project_agent_configuration x where x.project_id=p.id) where c.status in ('READY','LOCKED') order by p.project_name",(r,n)->new ReusableProject(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5)),u);}
 @Transactional(readOnly=true) public List<PresetView> presets(){return jdbc.query("select p.code,p.name,v.id,v.version_no,p.is_default from agent_team_preset p join agent_team_preset_version v on v.preset_id=p.id where p.status='ACTIVE' and v.status='PUBLISHED' order by p.is_default desc,p.code,v.version_no desc",(r,n)->new PresetView(r.getString(1),r.getString(2),r.getLong(3),r.getInt(4),r.getBoolean(5)));}
 private void createFromPreset(long p,long u,long preset){Map<String,Object> v=jdbc.queryForMap("select workflow_template_version_id from agent_team_preset_version where id=? and status='PUBLISHED'",preset);Long id=newDraft(p,u,((Number)v.get("workflow_template_version_id")).longValue(),"SYSTEM_PRESET",preset,null);jdbc.update("insert into project_agent_configuration_node(time_created,time_updated,configuration_id,stage_key,node_key,agent_profile_version_id) select now(3),now(3),?,stage_key,node_key,agent_profile_version_id from agent_team_preset_node_binding where preset_version_id=?",id,preset);}
 private Long newDraft(long p,long u,long w,String source,Long preset,Long sourceProject){List<Map<String,Object>> old=jdbc.queryForList("select version_no from project_agent_configuration where project_id=? order by version_no desc limit 1",p);int v=old.isEmpty()?1:((Number)old.get(0).get("version_no")).intValue()+1;jdbc.update("insert into project_agent_configuration(time_created,time_updated,project_id,workflow_template_version_id,source_type,source_preset_version_id,source_project_id,status,created_by,updated_by,version_no) values(now(3),now(3),?,?,?,?,?,'DRAFT',?,?,?)",p,w,source,preset,sourceProject,u,u,v);return jdbc.queryForObject("select id from project_agent_configuration where project_id=? and version_no=?",Long.class,p,v);}
 private void cloneNodes(Object sourceId,Long targetId){jdbc.update("insert into project_agent_configuration_node(time_created,time_updated,configuration_id,stage_key,node_key,agent_profile_version_id) select now(3),now(3),?,stage_key,node_key,agent_profile_version_id from project_agent_configuration_node where configuration_id=?",targetId,sourceId);}
 private Map<String,Object> config(long p){return jdbc.queryForMap("select id,status,source_type,source_preset_version_id,source_project_id,config_hash,version_no,workflow_template_version_id from project_agent_configuration where project_id=? order by version_no desc limit 1",p);}private Map<String,Object> configById(long id){return jdbc.queryForMap("select id,status,source_type,source_preset_version_id,source_project_id,config_hash,version_no,workflow_template_version_id from project_agent_configuration where id=?",id);}private List<Map<String,Object>> nodes(Object id){return jdbc.queryForList("select n.stage_key,n.node_key,v.status,n.agent_profile_version_id,p.status profile_status,v.system_prompt,v.model_code from project_agent_configuration_node n join agent_profile_version v on v.id=n.agent_profile_version_id join agent_profile p on p.id=v.agent_profile_id where n.configuration_id=? order by n.stage_key,n.node_key",id);}
 private ConfigurationView view(Map<String,Object> c,long p){Map<String,Object> project=jdbc.queryForMap("select project_key from virtual_project where id=?",p);String sourceProjectKey=c.get("source_project_id")==null?null:jdbc.queryForObject("select project_key from virtual_project where id=?",String.class,c.get("source_project_id"));return new ConfigurationView(((Number)c.get("id")).longValue(),String.valueOf(project.get("project_key")),String.valueOf(c.get("status")),String.valueOf(c.get("source_type")),(String)c.get("config_hash"),((Number)c.get("version_no")).intValue(),((Number)c.get("workflow_template_version_id")).longValue(),(Long)c.get("source_preset_version_id"),sourceProjectKey,jdbc.query("select n.stage_key,n.node_key,n.agent_profile_version_id,p.code,p.name from project_agent_configuration_node n join agent_profile_version v on v.id=n.agent_profile_version_id join agent_profile p on p.id=v.agent_profile_id where n.configuration_id=? order by n.stage_key,n.node_key",(r,n)->new NodeView(r.getString(1),r.getString(2),r.getLong(3),r.getString(4),r.getString(5)),c.get("id")));}
 private String hash(Object w,List<Map<String,Object>> n){try{String s=w+"|"+n.stream().map(x->x.get("stage_key")+"/"+x.get("node_key")+"/"+x.get("agent_profile_version_id")).sorted().reduce("",String::concat);byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder o=new StringBuilder();for(byte x:b)o.append(String.format("%02x",x));return o.toString();}catch(Exception e){throw new IllegalStateException(e);}}
 private long project(String k){return projects.findByProjectKey(k).map(x->x.getId()).orElseThrow(()->error("PROJECT_NOT_FOUND","Project not found",HttpStatus.NOT_FOUND));}private void read(long p,long u){member(p,u);}private void member(long p,long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project_member where project_id=? and user_id=? and status='ACTIVE'",Integer.class,p,u);if(n==null||n==0)throw error("PROJECT_ACCESS_FORBIDDEN","Project membership required",HttpStatus.FORBIDDEN);}private void write(long p,long u){Integer n=jdbc.queryForObject("select count(*) from virtual_project p where p.id=? and (p.created_by=? or exists(select 1 from virtual_project_member m where m.project_id=p.id and m.user_id=? and m.status='ACTIVE' and m.membership_type='OWNER'))",Integer.class,p,u,u);if(n==null||n==0)throw error("PROJECT_CONFIG_WRITE_FORBIDDEN","Only OWNER can configure agents",HttpStatus.FORBIDDEN);}private BusinessException error(String c,String m,HttpStatus s){return new BusinessException(c,m,s);}
 public record ConfigurationView(Long id,String projectKey,String status,String sourceType,String configHash,int versionNo,Long workflowTemplateVersionId,Long sourcePresetVersionId,String sourceProjectKey,List<NodeView> nodes){}public record NodeView(String stageKey,String nodeKey,Long agentProfileVersionId,String agentProfileCode,String nodeName){}public record CheckView(String label,boolean passed){}public record ValidationView(boolean valid,List<String> issues,List<CheckView> checks){}public record ReusableProject(String projectKey,String name,String status,String configHash,int versionNo){}public record PresetView(String code,String name,Long versionId,int versionNo,boolean isDefault){}
}
