package com.company.skillplatform.skill.application;

import com.company.skillplatform.compatibility.infrastructure.entity.SkillVersionCompatibilityEntity;
import com.company.skillplatform.audit.application.AuditService;import com.company.skillplatform.common.application.BusinessException;import com.company.skillplatform.skill.domain.*;import com.company.skillplatform.skill.infrastructure.entity.*;import com.company.skillplatform.skill.infrastructure.repository.*;import com.company.skillplatform.user.infrastructure.entity.IamUserEntity;import com.company.skillplatform.user.infrastructure.repository.IamUserRepository;import com.company.skillplatform.version.domain.*;import com.company.skillplatform.version.infrastructure.entity.*;import com.company.skillplatform.version.infrastructure.repository.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class SkillService{
 private static final String KEY_PATTERN="^[a-z0-9]+(-[a-z0-9]+)*$";
 private final SkillRepository skills;private final SkillCategoryRepository categories;private final SkillTagRepository tags;private final SkillOwnerRepository owners;private final SkillTagRelationRepository tagRelations;private final SkillVersionRepository versions;private final SkillSourceRevisionRepository revisions;private final IamUserRepository users;private final AuditService audit;
 public SkillService(SkillRepository s,SkillCategoryRepository c,SkillTagRepository t,SkillOwnerRepository o,SkillTagRelationRepository tr,SkillVersionRepository v,SkillSourceRevisionRepository rev,IamUserRepository u,AuditService a){skills=s;categories=c;tags=t;owners=o;tagRelations=tr;versions=v;revisions=rev;users=u;audit=a;}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public Page<SkillView> search(String keyword,Pageable pageable){Specification<SkillEntity> spec=(root,q,cb)->keyword==null||keyword.isBlank()?cb.conjunction():cb.or(cb.like(root.get("skillKey"),"%"+keyword+"%"),cb.like(root.get("displayName"),"%"+keyword+"%"));return skills.findAll(spec,pageable).map(this::view);}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public Page<SkillView> search(String keyword,Long categoryId,String tag,String platform,String osType,String lifecycleStatus,Long ownerId,Pageable pageable){Specification<SkillEntity> spec=(root,q,cb)->{List<jakarta.persistence.criteria.Predicate> p=new ArrayList<>();if(keyword!=null&&!keyword.isBlank())p.add(cb.or(cb.like(root.get("skillKey"),"%"+keyword+"%"),cb.like(root.get("displayName"),"%"+keyword+"%")));if(categoryId!=null)p.add(cb.equal(root.get("category").get("id"),categoryId));if(lifecycleStatus!=null&&!lifecycleStatus.isBlank())p.add(cb.equal(root.get("latestPublishedVersion").get("lifecycleStatus"),LifecycleStatus.valueOf(lifecycleStatus.toUpperCase())));if(ownerId!=null){var sq=q.subquery(Long.class);var o=sq.from(SkillOwnerEntity.class);sq.select(o.get("skill").get("id")).where(cb.equal(o.get("user").get("id"),ownerId));p.add(root.get("id").in(sq));}if(tag!=null&&!tag.isBlank()){var sq=q.subquery(Long.class);var tr=sq.from(SkillTagRelationEntity.class);sq.select(tr.get("skill").get("id")).where(cb.equal(tr.get("tag").get("tagKey"),tag));p.add(root.get("id").in(sq));}if((platform!=null&&!platform.isBlank())||(osType!=null&&!osType.isBlank())){var sq=q.subquery(Long.class);var c=sq.from(SkillVersionCompatibilityEntity.class);List<jakarta.persistence.criteria.Predicate> cp=new ArrayList<>();cp.add(cb.equal(c.get("version").get("id"),root.get("latestPublishedVersion").get("id")));if(platform!=null&&!platform.isBlank())cp.add(cb.equal(c.get("platform").get("platformKey"),platform.toUpperCase()));if(osType!=null&&!osType.isBlank())cp.add(cb.equal(c.get("osType"),com.company.skillplatform.compatibility.domain.OsType.valueOf(osType.toUpperCase())));sq.select(c.get("version").get("skill").get("id")).where(cb.and(cp.toArray(jakarta.persistence.criteria.Predicate[]::new)));p.add(cb.exists(sq));}return cb.and(p.toArray(jakarta.persistence.criteria.Predicate[]::new));};return skills.findAll(spec,pageable).map(this::view);}
 @PreAuthorize("hasAuthority('skill:upload')")@Transactional public SkillView create(CreateCommand c,Long actorId,String requestId){if(c.skillKey()==null||!c.skillKey().matches(KEY_PATTERN))throw bad("INVALID_SKILL_KEY","Invalid skill key");if(skills.existsBySkillKey(c.skillKey()))throw bad("SKILL_KEY_EXISTS","Skill key already exists",HttpStatus.CONFLICT);IamUserEntity actor=user(actorId);List<Long> requested=c.ownerUserIds()==null||c.ownerUserIds().isEmpty()?List.of(actorId):c.ownerUserIds();if(!hasAdminAuthority()&&requested.stream().anyMatch(id->!Objects.equals(id,actorId)))throw bad("OWNER_ASSIGNMENT_FORBIDDEN","Only administrators may assign other skill owners",HttpStatus.FORBIDDEN);SkillCategoryEntity category=category(c.categoryId());SkillEntity skill=skills.save(new SkillEntity(c.skillKey(),c.displayName(),c.description(),category,actor));int index=0;for(Long id:new LinkedHashSet<>(requested))owners.save(new SkillOwnerEntity(skill,user(id),index++==0?OwnerType.PRIMARY:OwnerType.MAINTAINER));replaceTags(skill,c.tagIds());audit.success("SKILL_CREATED",actor,"SKILL",skill.getId(),requestId,null,Map.of("skillKey",skill.getSkillKey()),Map.of());return view(skill);}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public SkillView get(String key){return view(skill(key));}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public VersionView getVersion(Long id){return versionView(version(id));}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<CategoryView> categories(){return categories.findByStatusOrderBySortOrderAscCategoryNameAsc("ACTIVE").stream().map(c->new CategoryView(c.getId(),c.getCategoryKey(),c.getCategoryName(),c.getParent()==null?null:c.getParent().getId(),c.getSortOrder())).toList();}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<TagView> tags(String keyword){List<SkillTagEntity> found=keyword==null||keyword.isBlank()?tags.findTop50ByOrderByTagNameAsc():tags.findTop50ByTagKeyContainingIgnoreCaseOrTagNameContainingIgnoreCaseOrderByTagNameAsc(keyword,keyword);return found.stream().map(t->new TagView(t.getId(),t.getTagKey(),t.getTagName())).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public SkillView update(String key,UpdateCommand c,Long actorId,String requestId){SkillEntity s=skill(key);owned(s,actorId);check(s.getVersionNo(),c.versionNo());IamUserEntity actor=user(actorId);s.update(c.displayName(),c.description(),category(c.categoryId()),actor);replaceTags(s,c.tagIds());audit.success("SKILL_UPDATED",actor,"SKILL",s.getId(),requestId,null,Map.of("skillKey",key),Map.of());return view(s);}
 @PreAuthorize("hasAuthority('skill:edit') or hasAuthority('admin:identity')")@Transactional public SkillView replaceOwners(String key,List<Long> ownerIds,Long primaryId,int versionNo,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));if(!hasAdminAuthority()&&!owners.existsBySkillIdAndUserIdAndOwnerType(s.getId(),actorId,OwnerType.PRIMARY))throw bad("PRIMARY_OWNER_REQUIRED","Only the primary owner or an administrator may maintain owners",HttpStatus.FORBIDDEN);check(s.getVersionNo(),versionNo);if(ownerIds==null||ownerIds.isEmpty())throw bad("SKILL_OWNER_REQUIRED","At least one owner is required");LinkedHashSet<Long> unique=new LinkedHashSet<>(ownerIds);if(primaryId==null||!unique.contains(primaryId))throw bad("PRIMARY_OWNER_INVALID","Primary owner must be included in ownerUserIds");List<IamUserEntity> selected=users.findAllById(unique);if(selected.size()!=unique.size()||selected.stream().anyMatch(u->u.getStatus()!=com.company.skillplatform.user.domain.UserStatus.ACTIVE))throw bad("OWNER_USER_INVALID","All owners must be active users");owners.deleteBySkillId(s.getId());for(IamUserEntity selectedUser:selected)owners.save(new SkillOwnerEntity(s,selectedUser,Objects.equals(selectedUser.getId(),primaryId)?OwnerType.PRIMARY:OwnerType.MAINTAINER));s.update(s.getDisplayName(),s.getDescription(),s.getCategory(),user(actorId));skills.saveAndFlush(s);audit.success("SKILL_OWNERS_REPLACED",user(actorId),"SKILL",s.getId(),requestId,null,Map.of("ownerUserIds",unique,"primaryOwnerUserId",primaryId),Map.of());return view(s);}
 @PreAuthorize("hasAuthority('skill:edit') or hasAuthority('admin:identity')")@Transactional public SkillView archive(String key,int versionNo,String reason,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));assertPrimaryOrAdmin(s,actorId);check(s.getVersionNo(),versionNo);if(s.getStatus()==SkillStatus.ARCHIVED)return view(s);if(s.getActiveDraftVersion()!=null)throw bad("ACTIVE_DRAFT_EXISTS","Cancel the active draft before archiving",HttpStatus.CONFLICT);s.archive(user(actorId));skills.saveAndFlush(s);audit.success("SKILL_ARCHIVED",user(actorId),"SKILL",s.getId(),requestId,null,Map.of("reason",reason),Map.of());return view(s);}
 @PreAuthorize("hasAuthority('skill:edit') or hasAuthority('admin:identity')")@Transactional public SkillView unarchive(String key,int versionNo,String reason,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));assertPrimaryOrAdmin(s,actorId);check(s.getVersionNo(),versionNo);if(s.getStatus()==SkillStatus.ACTIVE)return view(s);s.unarchive(user(actorId));skills.saveAndFlush(s);audit.success("SKILL_UNARCHIVED",user(actorId),"SKILL",s.getId(),requestId,null,Map.of("reason",reason),Map.of());return view(s);}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<VersionView> versions(String key){SkillEntity s=skill(key);return versions.findBySkillIdOrderByTimeCreatedDesc(s.getId()).stream().map(this::versionView).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public VersionView openDraft(String key,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));owned(s,actorId);if(s.getStatus()==SkillStatus.ARCHIVED)throw bad("SKILL_ARCHIVED","Archived skills cannot open drafts",HttpStatus.CONFLICT);if(s.getActiveDraftVersion()!=null)return versionView(s.getActiveDraftVersion());IamUserEntity actor=user(actorId);SkillVersionEntity base=s.getLatestPublishedVersion();SkillVersionEntity draft=versions.save(new SkillVersionEntity(s,base,base==null?ChangeType.INITIAL:ChangeType.ONLINE_EDIT,actor));s.setActiveDraftVersion(draft,actor);audit.success("SKILL_DRAFT_OPENED",actor,"SKILL_VERSION",draft.getId(),requestId,null,Map.of("skillKey",key),Map.of());return versionView(draft);}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public VersionView draft(String key){SkillVersionEntity draft=skill(key).getActiveDraftVersion();if(draft==null)throw notFound("ACTIVE_DRAFT_NOT_FOUND");return versionView(draft);}
 @PreAuthorize("hasAuthority('skill:upload')")@Transactional public VersionView markUpload(String key,String changeLog,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));owned(s,actorId);SkillVersionEntity draft=s.getActiveDraftVersion();if(draft==null){draft=versions.save(new SkillVersionEntity(s,s.getLatestPublishedVersion(),s.getLatestPublishedVersion()==null?ChangeType.INITIAL:ChangeType.ZIP_REUPLOAD,user(actorId)));s.setActiveDraftVersion(draft,user(actorId));}if(draft.getSourceRevision()==0&&draft.getChangeType()==ChangeType.INITIAL)draft.markSourceChanged(changeLog,user(actorId));else draft.markUploaded(changeLog,user(actorId));revisions.save(new SkillSourceRevisionEntity(draft,draft.getSourceRevision(),changeLog,user(actorId)));audit.success("SKILL_DRAFT_UPLOAD_REGISTERED",user(actorId),"SKILL_VERSION",draft.getId(),requestId,null,Map.of("sourceRevision",draft.getSourceRevision()),Map.of("storageStatus","PENDING"));return versionView(draft);}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public void cancelDraft(String key,int versionNo,Long actorId,String requestId){SkillEntity s=skills.findBySkillKeyForUpdate(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));owned(s,actorId);SkillVersionEntity draft=s.getActiveDraftVersion();if(draft==null)throw notFound("ACTIVE_DRAFT_NOT_FOUND");check(draft.getVersionNo(),versionNo);draft.cancel(user(actorId));s.clearDraft(user(actorId));audit.success("SKILL_DRAFT_CANCELLED",user(actorId),"SKILL_VERSION",draft.getId(),requestId,null,Map.of(),Map.of());}
 public void assertOwner(SkillVersionEntity version,Long userId){owned(version.getSkill(),userId);}
 public SkillVersionEntity version(Long id){return versions.findById(id).orElseThrow(()->notFound("SKILL_VERSION_NOT_FOUND"));}
 public void saveVersion(SkillVersionEntity version){versions.saveAndFlush(version);}
 private void owned(SkillEntity s,Long userId){if(hasAdminAuthority())return;if(!owners.existsBySkillIdAndUserId(s.getId(),userId))throw bad("SKILL_OWNER_REQUIRED","Only a skill owner may modify it",HttpStatus.FORBIDDEN);}
 private void assertPrimaryOrAdmin(SkillEntity s,Long userId){if(!hasAdminAuthority()&&!owners.existsBySkillIdAndUserIdAndOwnerType(s.getId(),userId,OwnerType.PRIMARY))throw bad("PRIMARY_OWNER_REQUIRED","Only the primary owner or an administrator may perform this action",HttpStatus.FORBIDDEN);}
 private boolean hasAdminAuthority(){Authentication authentication=SecurityContextHolder.getContext().getAuthentication();return authentication!=null&&authentication.getAuthorities().stream().anyMatch(a->"admin:identity".equals(a.getAuthority()));}
 private void replaceTags(SkillEntity s,List<Long> ids){if(ids==null)return;List<SkillTagEntity> selected=tags.findAllByIdIn(ids);if(selected.size()!=ids.stream().distinct().count())throw notFound("TAG_NOT_FOUND");tagRelations.deleteBySkillId(s.getId());tagRelations.saveAll(selected.stream().map(t->new SkillTagRelationEntity(s,t)).toList());}
 private SkillCategoryEntity category(Long id){if(id==null)return null;return categories.findById(id).orElseThrow(()->notFound("CATEGORY_NOT_FOUND"));}private IamUserEntity user(Long id){return users.findById(id).orElseThrow(()->notFound("USER_NOT_FOUND"));}private SkillEntity skill(String key){return skills.findBySkillKey(key).orElseThrow(()->notFound("SKILL_NOT_FOUND"));}
 private void check(int actual,int expected){if(actual!=expected)throw bad("OPTIMISTIC_LOCK_CONFLICT","Resource version is stale",HttpStatus.CONFLICT);}private BusinessException notFound(String code){return bad(code,code,HttpStatus.NOT_FOUND);}private BusinessException bad(String c,String m){return bad(c,m,HttpStatus.BAD_REQUEST);}private BusinessException bad(String c,String m,HttpStatus s){return new BusinessException(c,m,s);}
 private SkillView view(SkillEntity s){CategoryView category=s.getCategory()==null?null:new CategoryView(s.getCategory().getId(),s.getCategory().getCategoryKey(),s.getCategory().getCategoryName(),s.getCategory().getParent()==null?null:s.getCategory().getParent().getId(),s.getCategory().getSortOrder());List<OwnerView> ownerViews=owners.findBySkillId(s.getId()).stream().map(o->new OwnerView(o.getUser().getId(),o.getUser().getUsername(),o.getUser().getDisplayName(),o.getOwnerType())).toList();List<TagView> tagViews=tagRelations.findBySkillId(s.getId()).stream().map(r->new TagView(r.getTag().getId(),r.getTag().getTagKey(),r.getTag().getTagName())).toList();return new SkillView(s.getId(),s.getSkillKey(),s.getDisplayName(),s.getDescription(),s.getCategory()==null?null:s.getCategory().getId(),category,tagViews,ownerViews,s.getStatus(),s.getVersionNo(),s.getLatestPublishedVersion()==null?null:s.getLatestPublishedVersion().getVersion(),s.getActiveDraftVersion()==null?null:s.getActiveDraftVersion().getId());}
 public VersionView versionView(SkillVersionEntity v){return new VersionView(v.getId(),v.getSkill().getSkillKey(),v.getChangeType(),v.getLifecycleStatus(),v.getCandidateVersion(),v.getVersion(),v.getSourceRevision(),v.getVersionNo(),v.getBaseVersion()==null?null:v.getBaseVersion().getVersion(),v.getReplacementVersion()==null?null:v.getReplacementVersion().getId(),v.getReplacementVersion()==null?null:v.getReplacementVersion().getVersion());}
 public record CreateCommand(String skillKey,String displayName,String description,Long categoryId,List<Long> ownerUserIds,List<Long>tagIds){}public record UpdateCommand(String displayName,String description,Long categoryId,List<Long>tagIds,int versionNo){}public record SkillView(Long id,String skillKey,String displayName,String description,Long categoryId,CategoryView category,List<TagView> tags,List<OwnerView> owners,SkillStatus status,int versionNo,String latestPublishedVersion,Long activeDraftVersionId){}public record VersionView(Long id,String skillKey,ChangeType changeType,LifecycleStatus lifecycleStatus,String candidateVersion,String version,int sourceRevision,int versionNo,String baseVersion,Long replacementVersionId,String replacementVersion){}public record CategoryView(Long id,String key,String name,Long parentId,int sortOrder){}public record TagView(Long id,String key,String name){}public record OwnerView(Long userId,String username,String displayName,OwnerType ownerType){}
}
