package com.company.skillplatform.dependency.application;

import com.company.skillplatform.common.application.BusinessException;import com.company.skillplatform.dependency.domain.DependencyType;import com.company.skillplatform.dependency.infrastructure.entity.SkillVersionDependencyEntity;import com.company.skillplatform.dependency.infrastructure.repository.SkillVersionDependencyRepository;import com.company.skillplatform.skill.application.SkillService;import com.company.skillplatform.skill.infrastructure.entity.SkillEntity;import com.company.skillplatform.skill.infrastructure.repository.SkillRepository;import com.company.skillplatform.version.domain.*;import com.company.skillplatform.version.infrastructure.entity.SkillVersionEntity;import com.company.skillplatform.version.infrastructure.repository.SkillVersionRepository;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class DependencyService{
 private final SkillVersionDependencyRepository dependencies;private final SkillVersionRepository versions;private final SkillRepository skills;private final SkillService skillService;private final SemanticVersionPolicy semver;
 public DependencyService(SkillVersionDependencyRepository d,SkillVersionRepository v,SkillRepository s,SkillService ss,SemanticVersionPolicy p){dependencies=d;versions=v;skills=s;skillService=ss;semver=p;}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<DependencyView> list(Long versionId){skillService.version(versionId);return dependencies.findByVersionIdOrderBySortOrder(versionId).stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public List<DependencyView> replace(Long versionId,int versionNo,List<DependencyCommand> commands,Long actorId){SkillVersionEntity version=skillService.version(versionId);skillService.assertOwner(version,actorId);if(version.getLifecycleStatus()!=LifecycleStatus.DRAFT)throw conflict("VERSION_NOT_EDITABLE");List<SkillVersionDependencyEntity> next=new ArrayList<>();int order=0;for(DependencyCommand c:commands){SkillEntity target=skills.findBySkillKey(c.skillKey()).orElseThrow(()->notFound("DEPENDENCY_SKILL_NOT_FOUND"));if(target.getId().equals(version.getSkill().getId()))throw conflict("SELF_DEPENDENCY");validateConstraint(c.versionConstraint());if(reaches(target.getId(),version.getSkill().getId(),new HashSet<>()))throw conflict("DEPENDENCY_CYCLE");next.add(new SkillVersionDependencyEntity(version,target,c.versionConstraint(),c.dependencyType()==null?DependencyType.RUNTIME:c.dependencyType(),c.required(),order++));}if(versions.incrementVersion(versionId,versionNo)!=1)throw conflict("OPTIMISTIC_LOCK_CONFLICT");dependencies.deleteByVersionId(versionId);dependencies.saveAll(next);return next.stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional(readOnly=true)public ResolveView resolve(Long versionId){SkillVersionEntity root=skillService.version(versionId);List<ResolvedItem> items=new ArrayList<>();resolve(root,0,root.getSkill().getSkillKey(),items,new HashSet<>());return new ResolveView(items,List.of());}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<DependentView> dependents(Long versionId){SkillVersionEntity version=skillService.version(versionId);return dependencies.findByDependencySkillId(version.getSkill().getId()).stream().map(d->new DependentView(d.getVersion().getSkill().getSkillKey(),d.getVersion().getId(),d.getVersionConstraint())).toList();}
 private void resolve(SkillVersionEntity version,int depth,String path,List<ResolvedItem> out,Set<Long> seen){if(!seen.add(version.getSkill().getId()))throw conflict("DEPENDENCY_CYCLE");for(SkillVersionDependencyEntity d:dependencies.findByVersionIdOrderBySortOrder(version.getId())){SkillVersionEntity selected=versions.findFirstBySkillIdAndLifecycleStatusInOrderByPublishedAtDesc(d.getDependencySkill().getId(),List.of(LifecycleStatus.PUBLISHED,LifecycleStatus.DEPRECATED)).filter(v->matches(v.getVersion(),d.getVersionConstraint())).orElseThrow(()->new BusinessException("DEPENDENCY_UNRESOLVED","No published version satisfies dependency",HttpStatus.UNPROCESSABLE_ENTITY));out.add(new ResolvedItem(selected.getSkill().getSkillKey(),selected.getVersion(),depth+1,path+" -> "+selected.getSkill().getSkillKey()));resolve(selected,depth+1,path+" -> "+selected.getSkill().getSkillKey(),out,seen);}seen.remove(version.getSkill().getId());}
 private boolean reaches(Long fromSkill,Long target,Set<Long> seen){if(fromSkill.equals(target))return true;if(!seen.add(fromSkill))return false;Optional<SkillVersionEntity> v=versions.findFirstBySkillIdAndLifecycleStatusInOrderByPublishedAtDesc(fromSkill,List.of(LifecycleStatus.PUBLISHED,LifecycleStatus.DEPRECATED));if(v.isEmpty())return false;return dependencies.findByVersionIdOrderBySortOrder(v.get().getId()).stream().anyMatch(d->reaches(d.getDependencySkill().getId(),target,seen));}
 private boolean matches(String version,String constraint){if(constraint==null||constraint.isBlank()||constraint.equals("*"))return true;for(String part:constraint.trim().split("\\s+")){if(part.startsWith(">=")&&semver.compare(version,part.substring(2))<0)return false;if(part.startsWith("<")&&!part.startsWith("<=")&&semver.compare(version,part.substring(1))>=0)return false;if(Character.isDigit(part.charAt(0))&&semver.compare(version,part)!=0)return false;}return true;}
 private void validateConstraint(String value){try{matches("1.0.0",value);}catch(RuntimeException ex){throw new BusinessException("INVALID_VERSION_CONSTRAINT","Invalid SemVer constraint",HttpStatus.BAD_REQUEST);}}
 private DependencyView view(SkillVersionDependencyEntity d){return new DependencyView(d.getDependencySkill().getSkillKey(),d.getVersionConstraint(),d.getDependencyType(),d.isRequired(),d.getSortOrder());}private BusinessException conflict(String c){return new BusinessException(c,c,HttpStatus.CONFLICT);}private BusinessException notFound(String c){return new BusinessException(c,c,HttpStatus.NOT_FOUND);}
 public record DependencyCommand(String skillKey,String versionConstraint,DependencyType dependencyType,boolean required){}public record DependencyView(String skillKey,String versionConstraint,DependencyType dependencyType,boolean required,int sortOrder){}public record ResolvedItem(String skillKey,String version,int depth,String requiredByPath){}public record ResolveView(List<ResolvedItem>items,List<String>conflicts){}public record DependentView(String skillKey,Long versionId,String versionConstraint){}
}
