package com.company.skillplatform.compatibility.application;
import com.company.skillplatform.adapter.application.AdapterRegistry;
import com.company.skillplatform.common.application.BusinessException;import com.company.skillplatform.common.logging.LogContext;import com.company.skillplatform.compatibility.domain.*;import com.company.skillplatform.compatibility.infrastructure.entity.*;import com.company.skillplatform.compatibility.infrastructure.repository.*;import com.company.skillplatform.skill.application.SkillService;import com.company.skillplatform.version.domain.LifecycleStatus;import com.company.skillplatform.version.infrastructure.entity.SkillVersionEntity;import com.company.skillplatform.version.infrastructure.repository.SkillVersionRepository;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CompatibilityService{
 private static final org.slf4j.Logger log=org.slf4j.LoggerFactory.getLogger(CompatibilityService.class);
 private final SkillVersionCompatibilityRepository compatibilities;private final PlatformRepository platforms;private final PlatformAgentRepository agents;private final PlatformAdapterRepository adapters;private final SkillVersionRepository versions;private final SkillService skills;private final Clock clock;private AdapterRegistry adapterRegistry;
 public CompatibilityService(SkillVersionCompatibilityRepository c,PlatformRepository p,PlatformAgentRepository a,PlatformAdapterRepository pa,SkillVersionRepository v,SkillService s){compatibilities=c;platforms=p;agents=a;adapters=pa;versions=v;skills=s;clock=Clock.systemUTC();}
 @org.springframework.beans.factory.annotation.Autowired public void setAdapterRegistry(AdapterRegistry registry){this.adapterRegistry=registry;}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<CompatibilityView> list(Long versionId){skills.version(versionId);return compatibilities.findByVersionId(versionId).stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public List<CompatibilityView> replace(Long versionId,int versionNo,List<CompatibilityCommand> commands,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);if(v.getLifecycleStatus()!=LifecycleStatus.DRAFT)throw conflict("VERSION_NOT_EDITABLE");List<SkillVersionCompatibilityEntity> next=new ArrayList<>();for(CompatibilityCommand c:commands){PlatformEntity p=platforms.findByPlatformKey(c.platform()).orElseThrow(()->notFound("PLATFORM_NOT_FOUND"));PlatformAgentEntity a=c.agent()==null?null:agents.findByPlatformIdAndAgentKey(p.getId(),c.agent()).orElseThrow(()->notFound("PLATFORM_AGENT_NOT_FOUND"));next.add(new SkillVersionCompatibilityEntity(v,p,a,c.osType(),c.required(),c.declaredStatus(),c.minPlatformVersion(),c.maxPlatformVersion(),c.overlayPath()));}if(versions.incrementVersion(versionId,versionNo)!=1)throw conflict("OPTIMISTIC_LOCK_CONFLICT");compatibilities.deleteByVersionId(versionId);compatibilities.saveAll(next);return next.stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public List<CompatibilityView> validate(Long versionId,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);List<SkillVersionCompatibilityEntity> list=compatibilities.findByVersionId(versionId);list.forEach(i->{i.validate(clock.instant());if(adapterRegistry!=null)try{adapterRegistry.forPlatform(i.getPlatform().getPlatformKey());}catch(IllegalArgumentException ex){i.validationFailed(clock.instant(),"ADAPTER_NOT_REGISTERED");log.warn("event=compatibility.validate.failed requestId={} actorId={} versionId={} platform={} osType={} errorCode={}",LogContext.requestId(),actorId,versionId,i.getPlatform().getPlatformKey(),i.getOsType(),"ADAPTER_NOT_REGISTERED");}});log.info("event=compatibility.validate.completed requestId={} actorId={} versionId={} checkedCount={} failedCount={}",LogContext.requestId(),actorId,versionId,list.size(),list.stream().filter(i->i.getValidatedStatus()==CompatibilityStatus.VALIDATION_FAILED).count());return list.stream().map(this::view).toList();}
 @Transactional(readOnly=true) public void assertPublishable(Long versionId){List<SkillVersionCompatibilityEntity> list=compatibilities.findByVersionId(versionId);for(SkillVersionCompatibilityEntity item:list)if(item.isRequired()&&(item.getValidatedStatus()==CompatibilityStatus.UNSUPPORTED||item.getValidatedStatus()==CompatibilityStatus.VALIDATION_FAILED||item.getDeclaredStatus()==CompatibilityStatus.UNSUPPORTED)){log.warn("event=compatibility.publish.blocked requestId={} versionId={} platform={} osType={} declaredStatus={} validatedStatus={} errorCode={}",LogContext.requestId(),versionId,item.getPlatform().getPlatformKey(),item.getOsType(),item.getDeclaredStatus(),item.getValidatedStatus(),"COMPATIBILITY_NOT_PUBLISHABLE");throw new BusinessException("COMPATIBILITY_NOT_PUBLISHABLE","Required compatibility is not satisfied",HttpStatus.UNPROCESSABLE_ENTITY);}}
 @PreAuthorize("hasAuthority('skill:browse')")@Transactional(readOnly=true)public List<PlatformView> platforms(){return platforms.findAll().stream().map(p->new PlatformView(p.getId(),p.getPlatformKey(),p.getPlatformName(),p.getStatus(),adapters.findByPlatformId(p.getId()).stream().map(a->new AdapterView(a.getAdapterVersion(),a.getImplementationKey())).toList())).toList();}
 private CompatibilityView view(SkillVersionCompatibilityEntity c){return new CompatibilityView(c.getPlatform().getPlatformKey(),c.getAgent()==null?null:c.getAgent().getAgentKey(),c.getOsType(),c.isRequired(),c.getDeclaredStatus(),c.getValidatedStatus(),c.getMinPlatformVersion(),c.getMaxPlatformVersion(),c.getOverlayPath());}private BusinessException conflict(String c){return new BusinessException(c,c,HttpStatus.CONFLICT);}private BusinessException notFound(String c){return new BusinessException(c,c,HttpStatus.NOT_FOUND);}
 public record CompatibilityCommand(String platform,String agent,OsType osType,boolean required,CompatibilityStatus declaredStatus,String minPlatformVersion,String maxPlatformVersion,String overlayPath){}public record CompatibilityView(String platform,String agent,OsType osType,boolean required,CompatibilityStatus declaredStatus,CompatibilityStatus validatedStatus,String minPlatformVersion,String maxPlatformVersion,String overlayPath){}public record AdapterView(String adapterVersion,String implementationKey){}public record PlatformView(Long id,String platformKey,String platformName,String status,List<AdapterView>adapters){}
}
