package com.company.skillplatform.workflow.interfaces;import com.company.skillplatform.skill.application.SkillService;import com.company.skillplatform.workflow.application.WorkflowService;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.List;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/v1")public class WorkflowController{private final WorkflowService service;public WorkflowController(WorkflowService s){service=s;}
 @PostMapping("/skill-versions/{id}:submit-review")WorkflowService.SubmitView submit(@PathVariable Long id,@Valid@RequestBody VersionAction r,Authentication a,HttpServletRequest h){return service.submit(id,r.versionNo,r.comment,(Long)a.getPrincipal(),h.getRequestId());}
 @GetMapping("/reviews")List<WorkflowService.ReviewView> reviews(){return service.reviews();}@GetMapping("/reviews/{id}")WorkflowService.ReviewView review(@PathVariable Long id){return service.review(id);}
 @PostMapping("/reviews/{id}:approve")WorkflowService.ReviewView approve(@PathVariable Long id,@Valid@RequestBody CommentRequest r,Authentication a,HttpServletRequest h){return service.approve(id,r.comment,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/reviews/{id}:reject")WorkflowService.ReviewView reject(@PathVariable Long id,@Valid@RequestBody CommentRequest r,Authentication a,HttpServletRequest h){return service.reject(id,r.comment,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/skill-versions/{id}:withdraw")SkillService.VersionView withdraw(@PathVariable Long id,@Valid@RequestBody VersionAction r,Authentication a,HttpServletRequest h){return service.withdraw(id,r.versionNo,r.comment,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/skill-versions/{id}:publish")ResponseEntity<WorkflowService.BuildTaskView> publish(@PathVariable Long id,@RequestHeader("Idempotency-Key")String key,Authentication a,HttpServletRequest h){return ResponseEntity.accepted().body(service.publish(id,key,(Long)a.getPrincipal(),h.getRequestId()));}
 @GetMapping("/build-tasks/{id}")WorkflowService.BuildTaskView task(@PathVariable Long id){return service.task(id);}
 @PostMapping("/skill-versions/{id}:deprecate")SkillService.VersionView deprecate(@PathVariable Long id,@RequestBody(required=false)DeprecateRequest r,Authentication a,HttpServletRequest h){return service.deprecate(id,r==null?null:r.replacementVersionId,(Long)a.getPrincipal(),h.getRequestId());}
 @PostMapping("/skill-versions/{id}:offline-impact")WorkflowService.ImpactView impact(@PathVariable Long id){return service.impact(id);}
 @PostMapping("/skill-versions/{id}:offline")SkillService.VersionView offline(@PathVariable Long id,@Valid@RequestBody OfflineRequest r,Authentication a,HttpServletRequest h){return service.offline(id,r.force,r.reason,(Long)a.getPrincipal(),h.getRequestId());}
 public record VersionAction(@NotNull Integer versionNo,@NotBlank String comment){}public record CommentRequest(@NotBlank String comment){}public record DeprecateRequest(Long replacementVersionId){}public record OfflineRequest(boolean force,@NotBlank String reason){}
}
