package com.company.skillplatform.version.application;

import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.skill.application.SkillService;
import com.company.skillplatform.skill.infrastructure.entity.SkillEntity;
import com.company.skillplatform.skill.infrastructure.repository.SkillOwnerRepository;
import com.company.skillplatform.user.infrastructure.entity.IamUserEntity;
import com.company.skillplatform.user.infrastructure.repository.IamUserRepository;
import com.company.skillplatform.version.infrastructure.entity.*;
import com.company.skillplatform.version.infrastructure.repository.*;
import com.company.skillplatform.storage.domain.ObjectStoragePort;
import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;

@Service
public class SkillFileService {
    private static final Set<String> EDITABLE=Set.of("md","yaml","yml","json","txt","java","xml","properties","ps1","sh","js","ts","py");
    private final SkillService skills; private final SkillFileIndexRepository indexes; private final SkillSourceRevisionRepository revisions; private final IamUserRepository users; private final SkillOwnerRepository owners; private final ZipSecurityValidator validator; private final StandardConfigService configs; private final ObjectStoragePort storage; private final Map<Long,Map<String,byte[]>> workspaces=new java.util.concurrent.ConcurrentHashMap<>();
    public SkillFileService(SkillService skills,SkillFileIndexRepository indexes,SkillSourceRevisionRepository revisions,IamUserRepository users,SkillOwnerRepository owners,ZipSecurityValidator validator,StandardConfigService configs,ObjectStoragePort storage){this.skills=skills;this.indexes=indexes;this.revisions=revisions;this.users=users;this.owners=owners;this.validator=validator;this.configs=configs;this.storage=storage;}
    @PreAuthorize("hasAuthority('skill:upload')") @Transactional
    public UploadView upload(String key,MultipartFile multipart,String changeLog,Long actorId,String requestId){
        if(multipart==null||multipart.isEmpty())throw new BusinessException("ZIP_REQUIRED","A non-empty ZIP file is required",HttpStatus.BAD_REQUEST);
        SkillService.VersionView opened=skills.openDraft(key,actorId,requestId); SkillVersionEntity version=skills.version(opened.id());
        ZipSecurityValidator.ValidatedArchive archive; try{archive=validator.validate(multipart.getInputStream());}catch(IOException ex){throw new BusinessException("ZIP_READ_FAILED","Unable to read ZIP",HttpStatus.BAD_REQUEST);}
        IamUserEntity actor=users.findById(actorId).orElseThrow(); if(version.getSourceRevision()==0&&version.getChangeType()==com.company.skillplatform.version.domain.ChangeType.INITIAL)version.markSourceChanged(changeLog,actor);else version.markUploaded(changeLog,actor);
        Map<String,byte[]> generated=configs.generated(key); Map<String,byte[]> files=new LinkedHashMap<>(archive.files()); generated.forEach(files::putIfAbsent);
        workspaces.put(version.getId(),new LinkedHashMap<>(files));
        byte[] source=serialize(files); String digest=sha256(source); String objectKey="skills/"+key+"/revisions/"+version.getSourceRevision()+"/source.zip"; storage.put(objectKey,new ByteArrayInputStream(source),source.length,"application/zip");
        version.storeSource(objectKey,digest,source.length,Map.of("storageStatus","READY","fileCount",files.size()));
        SkillSourceRevisionEntity revision=revisions.save(new SkillSourceRevisionEntity(version,version.getSourceRevision(),changeLog,actor));revision.complete(objectKey,digest,source.length);
        indexes.deleteByVersionId(version.getId()); List<SkillFileIndexEntity> rows=files.entrySet().stream().map(e->new SkillFileIndexEntity(version,version.getSourceRevision(),e.getKey(),type(e.getKey()),media(e.getKey()),e.getValue().length,editable(e.getKey()),generated.containsKey(e.getKey())?"GENERATED":"UPLOADED")).toList(); indexes.saveAll(rows);
        return new UploadView(version.getId(),version.getSourceRevision(),version.getLifecycleStatus().name(),version.getChangeType().name(),version.getBaseVersion()==null?null:version.getBaseVersion().getVersion(),version.getCandidateVersion(),rows.stream().map(f->new FileView(f.getRelativePath(),f.getFileSource(),f.isEditable(),f.getSizeBytes())).toList(),List.of());
    }
    @PreAuthorize("hasAuthority('skill:browse')") @Transactional(readOnly=true) public List<FileView> files(Long versionId){SkillVersionEntity v=skills.version(versionId);return indexes.findByVersionIdAndSourceRevision(versionId,v.getSourceRevision()).stream().map(f->new FileView(f.getRelativePath(),f.getFileSource(),f.isEditable(),f.getSizeBytes())).toList();}
    @PreAuthorize("hasAuthority('skill:browse')") @Transactional(readOnly=true) public String content(Long versionId,String path){SkillVersionEntity v=skills.version(versionId);if(!editable(path))throw bad("FILE_NOT_EDITABLE");byte[] value=workspaces.getOrDefault(versionId,Map.of()).get(path);if(value==null)throw bad("FILE_NOT_FOUND");return new String(value,StandardCharsets.UTF_8);}
    @PreAuthorize("hasAuthority('skill:edit')") @Transactional public List<FileView> saveContent(Long versionId,String path,String content,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);if(v.getLifecycleStatus()!=com.company.skillplatform.version.domain.LifecycleStatus.DRAFT||!editable(path)||content==null||content.getBytes(StandardCharsets.UTF_8).length>1024*1024)throw bad("FILE_NOT_EDITABLE");Map<String,byte[]> files=workspace(versionId);files.put(path,content.getBytes(StandardCharsets.UTF_8));return persist(v,files,actorId,"online file edit");}
    public List<FileView> saveContent(Long versionId,String path,String content,int versionNo,Long actorId){SkillVersionEntity v=skills.version(versionId);if(v.getVersionNo()!=versionNo)throw new BusinessException("OPTIMISTIC_LOCK_CONFLICT","Resource is stale",HttpStatus.CONFLICT);return saveContent(versionId,path,content,actorId);}
    public List<FileView> deleteContent(Long versionId,String path,int versionNo,Long actorId){checkVersion(versionId,versionNo);return deleteContent(versionId,path,actorId);}
    public List<FileView> uploadResource(Long versionId,String path,MultipartFile file,int versionNo,Long actorId){checkVersion(versionId,versionNo);return uploadResource(versionId,path,file,actorId);}
    public List<FileView> resetStandardConfig(Long versionId,int versionNo,Long actorId){checkVersion(versionId,versionNo);return resetStandardConfig(versionId,actorId);}
    @PreAuthorize("hasAuthority('skill:edit')") @Transactional public List<FileView> deleteContent(Long versionId,String path,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);if(path.equals("skill.yaml")||path.startsWith("overlays/"))throw bad("GENERATED_FILE_REQUIRED");Map<String,byte[]> files=workspace(versionId);if(files.remove(path)==null)throw bad("FILE_NOT_FOUND");return persist(v,files,actorId,"file deleted");}
    @PreAuthorize("hasAuthority('skill:edit')") @Transactional public List<FileView> uploadResource(Long versionId,String path,MultipartFile file,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);if(v.getLifecycleStatus()!=com.company.skillplatform.version.domain.LifecycleStatus.DRAFT||file==null||file.isEmpty()||path==null||path.isBlank()||path.startsWith("/")||path.contains("..")||path.startsWith("overlays/")||path.equals("skill.yaml"))throw bad("FILE_PATH_INVALID");try{Map<String,byte[]> files=workspace(versionId);files.put(path,file.getBytes());return persist(v,files,actorId,"resource uploaded");}catch(IOException ex){throw bad("FILE_READ_FAILED");}}
    @PreAuthorize("hasAuthority('skill:edit')") @Transactional public List<FileView> resetStandardConfig(Long versionId,Long actorId){SkillVersionEntity v=skills.version(versionId);skills.assertOwner(v,actorId);Map<String,byte[]> files=workspace(versionId);configs.generated(v.getSkill().getSkillKey()).forEach(files::put);return persist(v,files,actorId,"standard config reset");}
    @PreAuthorize("hasAuthority('skill:edit')") @Transactional(readOnly=true) public List<String> validate(Long versionId){SkillVersionEntity v=skills.version(versionId);Map<String,byte[]> files=workspace(versionId);List<String> warnings=new ArrayList<>();if(!files.containsKey("SKILL.md"))warnings.add("SKILL_MD_REQUIRED");if(!files.containsKey("skill.yaml"))warnings.add("STANDARD_CONFIG_REQUIRED");return warnings;}
    public Map<String,byte[]> snapshot(Long versionId){return Map.copyOf(workspace(versionId));}
    public SkillVersionEntity version(Long versionId){return skills.version(versionId);}
    private Map<String,byte[]> workspace(Long id){Map<String,byte[]> files=workspaces.get(id);if(files!=null)return files;SkillVersionEntity v=skills.version(id);if(v.getSourceObjectKey()==null||v.getSourceObjectKey().equals("pending"))throw bad("WORKSPACE_NOT_FOUND");try{Map<String,byte[]> loaded=new LinkedHashMap<>();try(java.util.zip.ZipInputStream zip=new java.util.zip.ZipInputStream(storage.get(v.getSourceObjectKey()))){java.util.zip.ZipEntry entry;byte[] buf=new byte[8192];while((entry=zip.getNextEntry())!=null){if(entry.isDirectory())continue;ByteArrayOutputStream out=new ByteArrayOutputStream();int n;while((n=zip.read(buf))>=0)out.write(buf,0,n);loaded.put(entry.getName(),out.toByteArray());}}workspaces.put(id,loaded);return loaded;}catch(IOException ex){throw bad("WORKSPACE_NOT_FOUND");}}
    private List<FileView> persist(SkillVersionEntity v,Map<String,byte[]> files,Long actorId,String summary){IamUserEntity actor=users.findById(actorId).orElseThrow();v.markSourceChanged(summary,actor);byte[] source=serialize(files);String digest=sha256(source);String key="skills/"+v.getSkill().getSkillKey()+"/revisions/"+v.getSourceRevision()+"/source.zip";storage.put(key,new ByteArrayInputStream(source),source.length,"application/zip");v.storeSource(key,digest,source.length,Map.of("storageStatus","READY","fileCount",files.size()));SkillSourceRevisionEntity revision=revisions.save(new SkillSourceRevisionEntity(v,v.getSourceRevision(),summary,actor));revision.complete(key,digest,source.length);indexes.deleteByVersionId(v.getId());List<SkillFileIndexEntity> rows=files.entrySet().stream().map(e->new SkillFileIndexEntity(v,v.getSourceRevision(),e.getKey(),type(e.getKey()),media(e.getKey()),e.getValue().length,editable(e.getKey()),e.getKey().startsWith("overlays/")||e.getKey().equals("skill.yaml")?"GENERATED":"UPLOADED")).toList();indexes.saveAll(rows);return rows.stream().map(f->new FileView(f.getRelativePath(),f.getFileSource(),f.isEditable(),f.getSizeBytes())).toList();}
    private boolean editable(String path){int dot=path.lastIndexOf('.');return dot>0&&EDITABLE.contains(path.substring(dot+1).toLowerCase(Locale.ROOT));} private String type(String path){return path.contains("/")?path.substring(0,path.indexOf('/')):"file";} private String media(String path){return path.endsWith(".md")?"text/markdown":path.endsWith(".yaml")||path.endsWith(".yml")?"text/yaml":"application/octet-stream";}
    private byte[] serialize(Map<String,byte[]> files){try{ByteArrayOutputStream out=new ByteArrayOutputStream();java.util.zip.ZipOutputStream zip=new java.util.zip.ZipOutputStream(out);for(var e:files.entrySet()){zip.putNextEntry(new java.util.zip.ZipEntry(e.getKey()));zip.write(e.getValue());zip.closeEntry();}zip.finish();return out.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
    private String sha256(byte[] bytes){try{returnHex: {return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}}catch(Exception e){throw new IllegalStateException(e);}}
    private BusinessException bad(String code){return new BusinessException(code,code,HttpStatus.BAD_REQUEST);}
    private void checkVersion(Long id,int expected){if(skills.version(id).getVersionNo()!=expected)throw new BusinessException("OPTIMISTIC_LOCK_CONFLICT","Resource is stale",HttpStatus.CONFLICT);}
    public record UploadView(Long versionId,int sourceRevision,String status,String changeType,String baseVersion,String suggestedVersion,List<FileView> files,List<String>warnings){} public record FileView(String path,String source,boolean editable,long sizeBytes){}
}
