package com.company.skillplatform.skill.application;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import com.company.skillplatform.audit.application.AuditService;import com.company.skillplatform.skill.infrastructure.entity.*;import com.company.skillplatform.skill.infrastructure.repository.*;import com.company.skillplatform.user.domain.IdentityProviderType;import com.company.skillplatform.user.infrastructure.entity.IamUserEntity;import com.company.skillplatform.user.infrastructure.repository.IamUserRepository;import com.company.skillplatform.version.infrastructure.entity.SkillVersionEntity;import com.company.skillplatform.version.infrastructure.repository.*;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.data.domain.*;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.test.util.ReflectionTestUtils;
class SkillServiceTest{
 SkillRepository skills=mock(SkillRepository.class);SkillCategoryRepository categories=mock(SkillCategoryRepository.class);SkillTagRepository tags=mock(SkillTagRepository.class);SkillOwnerRepository owners=mock(SkillOwnerRepository.class);SkillTagRelationRepository relations=mock(SkillTagRelationRepository.class);SkillVersionRepository versions=mock(SkillVersionRepository.class);SkillSourceRevisionRepository revisions=mock(SkillSourceRevisionRepository.class);IamUserRepository users=mock(IamUserRepository.class);AuditService audit=mock(AuditService.class);SkillService service;IamUserEntity user;
 @BeforeEach void setup(){service=new SkillService(skills,categories,tags,owners,relations,versions,revisions,users,audit);user=new IamUserEntity(IdentityProviderType.MOCK,"u","u","h","U",null);ReflectionTestUtils.setField(user,"id",1L);when(users.findById(1L)).thenReturn(Optional.of(user));when(skills.save(any())).thenAnswer(i->{SkillEntity s=i.getArgument(0);ReflectionTestUtils.setField(s,"id",10L);return s;});when(versions.save(any())).thenAnswer(i->{SkillVersionEntity v=i.getArgument(0);ReflectionTestUtils.setField(v,"id",20L);return v;});when(tags.findAllByIdIn(any())).thenReturn(List.of());}
 @AfterEach void clearSecurity(){SecurityContextHolder.clearContext();}
 @Test void createsSearchesUpdatesAndReadsSkill(){SkillService.SkillView created=service.create(new SkillService.CreateCommand("java-tdd","Java TDD","desc",null,List.of(),List.of()),1L,"r");assertThat(created.skillKey()).isEqualTo("java-tdd");when(skills.findBySkillKey("java-tdd")).thenAnswer(i->{SkillEntity s=new SkillEntity("java-tdd","Java TDD","desc",null,user);ReflectionTestUtils.setField(s,"id",10L);return Optional.of(s);});when(owners.existsBySkillIdAndUserId(10L,1L)).thenReturn(true);assertThat(service.get("java-tdd").displayName()).isEqualTo("Java TDD");assertThat(service.update("java-tdd",new SkillService.UpdateCommand("Updated","new",null,List.of(),0),1L,"r").displayName()).isEqualTo("Updated");when(skills.findAll(any(org.springframework.data.jpa.domain.Specification.class),any(Pageable.class))).thenReturn(new PageImpl<>(List.of(new SkillEntity("other","Other","d",null,user))));assertThat(service.search("oth",Pageable.unpaged())).hasSize(1);}
 @Test void opensUploadsReadsAndCancelsDraft(){SkillEntity s=new SkillEntity("java-tdd","Java TDD","d",null,user);ReflectionTestUtils.setField(s,"id",10L);when(skills.findBySkillKeyForUpdate("java-tdd")).thenReturn(Optional.of(s));when(skills.findBySkillKey("java-tdd")).thenReturn(Optional.of(s));when(owners.existsBySkillIdAndUserId(10L,1L)).thenReturn(true);SkillService.VersionView opened=service.openDraft("java-tdd",1L,"r");assertThat(opened.lifecycleStatus().name()).isEqualTo("DRAFT");assertThat(service.draft("java-tdd").id()).isEqualTo(20L);assertThat(service.markUpload("java-tdd","zip",1L,"r").sourceRevision()).isEqualTo(1);service.cancelDraft("java-tdd",0,1L,"r");assertThat(s.getActiveDraftVersion()).isNull();}
 @Test void rejectsInvalidKeyAndNonOwner(){assertThatThrownBy(()->service.create(new SkillService.CreateCommand("Bad Key","x","d",null,List.of(),List.of()),1L,"r")).isInstanceOf(RuntimeException.class);SkillEntity s=new SkillEntity("x","X","d",null,user);ReflectionTestUtils.setField(s,"id",3L);when(skills.findBySkillKey("x")).thenReturn(Optional.of(s));assertThatThrownBy(()->service.update("x",new SkillService.UpdateCommand("X","d",null,List.of(),0),2L,"r")).isInstanceOf(RuntimeException.class);}
 @Test void searchesWithStructuredFilters(){when(skills.findAll(any(org.springframework.data.jpa.domain.Specification.class),any(Pageable.class))).thenReturn(Page.empty());assertThat(service.search(null,null,null,null,null,null,null,Pageable.unpaged())).isEmpty();}
 @Test void nonAdminCannotAssignOtherOwner(){assertThatThrownBy(()->service.create(new SkillService.CreateCommand("owned-skill","Owned","d",null,List.of(2L),List.of()),1L,"r")).isInstanceOf(com.company.skillplatform.common.application.BusinessException.class).hasMessageContaining("Only administrators");verify(skills,never()).save(any());}
 @Test void adminMayAssignOwnersAndEditNonOwnedSkill(){SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(1L,"n",List.of(()->"admin:identity")));IamUserEntity other=new IamUserEntity(IdentityProviderType.MOCK,"o","o","h","O",null);ReflectionTestUtils.setField(other,"id",2L);when(users.findById(2L)).thenReturn(Optional.of(other));assertThat(service.create(new SkillService.CreateCommand("admin-owned","Admin","d",null,List.of(2L),List.of()),1L,"r").skillKey()).isEqualTo("admin-owned");SkillEntity skill=new SkillEntity("other-skill","Other","d",null,other);ReflectionTestUtils.setField(skill,"id",30L);when(skills.findBySkillKey("other-skill")).thenReturn(Optional.of(skill));assertThat(service.update("other-skill",new SkillService.UpdateCommand("Changed","d",null,List.of(),0),1L,"r").displayName()).isEqualTo("Changed");verify(owners,never()).existsBySkillIdAndUserId(30L,1L);}
}
