package com.company.skillplatform.workflow.application;

import com.company.skillplatform.audit.application.AuditService;
import com.company.skillplatform.common.application.BusinessException;
import com.company.skillplatform.common.logging.LogContext;
import com.company.skillplatform.compatibility.application.CompatibilityService;
import com.company.skillplatform.dependency.application.DependencyService;
import com.company.skillplatform.dependency.infrastructure.repository.SkillVersionDependencyRepository;
import com.company.skillplatform.notification.application.NotificationService;
import com.company.skillplatform.skill.application.SkillService;
import com.company.skillplatform.skill.infrastructure.entity.SkillEntity;
import com.company.skillplatform.skill.infrastructure.repository.SkillRepository;
import com.company.skillplatform.user.infrastructure.entity.IamUserEntity;
import com.company.skillplatform.user.infrastructure.repository.IamUserRepository;
import com.company.skillplatform.version.domain.*;
import com.company.skillplatform.version.infrastructure.entity.SkillVersionEntity;
import com.company.skillplatform.workflow.domain.*;
import com.company.skillplatform.workflow.infrastructure.entity.*;
import com.company.skillplatform.workflow.infrastructure.repository.*;
import java.time.*;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class WorkflowService {
 private static final org.slf4j.Logger log=org.slf4j.LoggerFactory.getLogger(WorkflowService.class);
 private final SkillReviewRepository reviews;private final SkillStatusHistoryRepository histories;private final ArtifactBuildTaskRepository tasks;private final SkillRepository skills;private final SkillVersionDependencyRepository dependencies;private final SkillService skillService;private final DependencyService resolver;private final SemanticVersionPolicy versionPolicy;private final IamUserRepository users;private final PublicationPort publication;private final AuditService audit;private final Clock clock;private CompatibilityService compatibility;private NotificationService notifications;
 @org.springframework.beans.factory.annotation.Autowired public WorkflowService(SkillReviewRepository r,SkillStatusHistoryRepository h,ArtifactBuildTaskRepository t,SkillRepository s,SkillVersionDependencyRepository d,SkillService ss,DependencyService resolver,SemanticVersionPolicy vp,IamUserRepository u,PublicationPort p,AuditService a){this(r,h,t,s,d,ss,resolver,vp,u,p,a,Clock.systemUTC());}
 WorkflowService(SkillReviewRepository r,SkillStatusHistoryRepository h,ArtifactBuildTaskRepository t,SkillRepository s,SkillVersionDependencyRepository d,SkillService ss,DependencyService resolver,SemanticVersionPolicy vp,IamUserRepository u,PublicationPort p,AuditService a,Clock c){reviews=r;histories=h;tasks=t;skills=s;dependencies=d;skillService=ss;this.resolver=resolver;versionPolicy=vp;users=u;publication=p;audit=a;clock=c;}
 @org.springframework.beans.factory.annotation.Autowired public void setCompatibility(CompatibilityService compatibility){this.compatibility=compatibility;}
 @org.springframework.beans.factory.annotation.Autowired public void setNotifications(NotificationService notifications){this.notifications=notifications;}

 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public SubmitView submit(Long versionId,int versionNo,String comment,Long actorId,String requestId){SkillVersionEntity initial=skillService.version(versionId);skillService.assertOwner(initial,actorId);SkillEntity skill=skills.findBySkillKeyForUpdate(initial.getSkill().getSkillKey()).orElseThrow(()->notFound("SKILL_NOT_FOUND"));SkillVersionEntity v=skillService.version(versionId);check(v.getVersionNo(),versionNo);if(v.getBaseVersion()!=skill.getLatestPublishedVersion()){log.warn("event=skill.review.submit.failed requestId={} actorId={} skillKey={} versionId={} errorCode={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,"VERSION_BASE_CHANGED");throw conflict("VERSION_BASE_CHANGED");}validateGates(versionId);String latest=skill.getLatestPublishedVersion()==null?null:skill.getLatestPublishedVersion().getVersion();String candidate=v.getCandidateVersion()==null||v.getChangeType()==ChangeType.ZIP_REUPLOAD?versionPolicy.candidate(v.getChangeType(),latest):v.getCandidateVersion();LifecycleStatus from=v.getLifecycleStatus();v.submit(candidate,user(actorId));SkillReviewEntity review=reviews.save(new SkillReviewEntity(v,(int)reviews.countByVersionId(versionId)+1,user(actorId),comment,clock.instant()));history(v,from,"Submitted for review",actorId);audit("SKILL_VERSION_SUBMITTED",v,actorId,requestId);if(notifications!=null)notifications.reviewSubmitted(v,review.getId());log.info("event=skill.review.submitted requestId={} actorId={} skillKey={} versionId={} candidateVersion={} reviewId={} fromStatus={} toStatus={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,candidate,review.getId(),from,v.getLifecycleStatus());return new SubmitView(v.getId(),candidate,v.getChangeType(),latest,v.getLifecycleStatus(),review.getId());}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional(readOnly=true)public List<ReviewView> reviews(){return reviews.findByStatusOrderBySubmittedAtAsc(ReviewStatus.PENDING).stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional(readOnly=true)public Page<ReviewView> reviews(ReviewStatus status,String keyword,Pageable pageable){Specification<SkillReviewEntity> spec=(root,q,cb)->{List<jakarta.persistence.criteria.Predicate> p=new ArrayList<>();if(status!=null)p.add(cb.equal(root.get("status"),status));if(keyword!=null&&!keyword.isBlank())p.add(cb.or(cb.like(root.get("version").get("skill").get("skillKey"),"%"+keyword+"%"),cb.like(root.get("version").get("skill").get("displayName"),"%"+keyword+"%")));return cb.and(p.toArray(jakarta.persistence.criteria.Predicate[]::new));};return reviews.findAll(spec,pageable).map(this::view);}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional(readOnly=true)public ReviewView review(Long id){return view(anyReview(id));}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional public ReviewView approve(Long id,String comment,Long actorId,String requestId){SkillReviewEntity r=pendingReview(id);LifecycleStatus from=r.getVersion().getLifecycleStatus();r.getVersion().approve(user(actorId));r.approve(user(actorId),comment,clock.instant());history(r.getVersion(),from,comment,actorId);audit("SKILL_REVIEW_APPROVED",r.getVersion(),actorId,requestId);if(notifications!=null)notifications.reviewCompleted(r.getVersion(),r.getId(),true,r.getSubmitter().getId(),comment);log.info("event=skill.review.approved requestId={} actorId={} skillKey={} versionId={} reviewId={} fromStatus={} toStatus={}",requestId,actorId,r.getVersion().getSkill().getSkillKey(),r.getVersion().getId(),id,from,r.getVersion().getLifecycleStatus());return view(r);}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional public ReviewView reject(Long id,String comment,Long actorId,String requestId){SkillReviewEntity r=pendingReview(id);LifecycleStatus from=r.getVersion().getLifecycleStatus();r.getVersion().reject(user(actorId));r.reject(user(actorId),comment,clock.instant());history(r.getVersion(),from,comment,actorId);audit("SKILL_REVIEW_REJECTED",r.getVersion(),actorId,requestId);if(notifications!=null)notifications.reviewCompleted(r.getVersion(),r.getId(),false,r.getSubmitter().getId(),comment);log.info("event=skill.review.rejected requestId={} actorId={} skillKey={} versionId={} reviewId={} fromStatus={} toStatus={}",requestId,actorId,r.getVersion().getSkill().getSkillKey(),r.getVersion().getId(),id,from,r.getVersion().getLifecycleStatus());return view(r);}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public SkillService.VersionView withdraw(Long versionId,int versionNo,String reason,Long actorId,String requestId){SkillVersionEntity v=skillService.version(versionId);skillService.assertOwner(v,actorId);check(v.getVersionNo(),versionNo);LifecycleStatus from=v.getLifecycleStatus();v.withdraw(user(actorId));history(v,from,reason,actorId);audit("SKILL_VERSION_WITHDRAWN",v,actorId,requestId);log.info("event=skill.version.withdrawn requestId={} actorId={} skillKey={} versionId={} fromStatus={} toStatus={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,from,v.getLifecycleStatus());return skillService.versionView(v);}

 @PreAuthorize("hasAuthority('skill:publish')")@Transactional public BuildTaskView publish(Long versionId,String key,Long actorId,String requestId){Optional<ArtifactBuildTaskEntity> existing=tasks.findByIdempotencyKey(key);if(existing.isPresent()){log.info("event=skill.publish.idempotent_hit requestId={} actorId={} versionId={} taskId={} idempotencyKey={}",requestId,actorId,versionId,existing.get().getId(),key);return taskView(existing.get());}SkillVersionEntity v=skillService.version(versionId);if(v.getLifecycleStatus()!=LifecycleStatus.APPROVED){log.warn("event=skill.publish.failed requestId={} actorId={} skillKey={} versionId={} errorCode={} lifecycleStatus={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,"VERSION_NOT_APPROVED",v.getLifecycleStatus());throw conflict("VERSION_NOT_APPROVED");}if(tasks.existsByVersionIdAndStatusIn(versionId,List.of("PENDING","RUNNING"))){log.warn("event=skill.publish.failed requestId={} actorId={} skillKey={} versionId={} errorCode={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,"BUILD_TASK_ALREADY_RUNNING");throw conflict("BUILD_TASK_ALREADY_RUNNING");}validateGates(versionId);ArtifactBuildTaskEntity task=tasks.saveAndFlush(new ArtifactBuildTaskEntity(v,key,user(actorId),clock.instant()));LogContext.putTask(String.valueOf(task.getId()),1);if(tasks.claim(task.getId(),clock.instant())!=1){log.warn("event=skill.publish.failed requestId={} actorId={} versionId={} taskId={} errorCode={}",requestId,actorId,versionId,task.getId(),"BUILD_TASK_CLAIM_FAILED");throw conflict("BUILD_TASK_CLAIM_FAILED");}log.info("event=skill.build.claimed requestId={} actorId={} skillKey={} versionId={} taskId={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,task.getId());try{publication.build(versionId);LifecycleStatus from=v.getLifecycleStatus();IamUserEntity publisher=user(actorId);v.publish(clock.instant(),publisher);skillService.saveVersion(v);v.getSkill().publish(v,publisher);skills.saveAndFlush(v.getSkill());task.complete(null,null,0,"application/zip",clock.instant());tasks.save(task);history(v,from,"Published",actorId);audit("SKILL_VERSION_PUBLISHED",v,actorId,requestId);if(notifications!=null)notifications.publishCompleted(v,task.getId(),actorId,true,null);log.info("event=skill.version.published requestId={} actorId={} skillKey={} versionId={} version={} taskId={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,v.getVersion(),task.getId());}catch(RuntimeException ex){task.fail("ARTIFACT_BUILD_FAILED",ex.getMessage(),clock.instant());tasks.save(task);if(notifications!=null)notifications.publishCompleted(v,task.getId(),actorId,false,"ARTIFACT_BUILD_FAILED");log.error("event=skill.build.failed requestId={} actorId={} skillKey={} versionId={} taskId={} errorCode={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,task.getId(),"ARTIFACT_BUILD_FAILED",ex);}LogContext.clearTask();return taskView(task);}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional(readOnly=true)public BuildTaskView task(Long id){return taskView(tasks.findById(id).orElseThrow(()->notFound("BUILD_TASK_NOT_FOUND")));}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional(readOnly=true)public Page<BuildTaskView> tasks(Long versionId,Pageable pageable){skillService.version(versionId);return tasks.findByVersionIdOrderByTimeCreatedDesc(versionId,pageable).map(this::taskView);}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional public SkillService.VersionView deprecate(Long versionId,Long replacementId,Long actorId,String requestId){SkillVersionEntity v=skillService.version(versionId);SkillVersionEntity replacement=replacementId==null?null:validatedReplacement(v,replacementId);LifecycleStatus from=v.getLifecycleStatus();v.deprecate(replacement,user(actorId));history(v,from,"Deprecated",actorId);audit("SKILL_VERSION_DEPRECATED",v,actorId,requestId);if(notifications!=null)notifications.lifecycleChanged(v,"SKILL_DEPRECATED");log.info("event=skill.version.deprecated requestId={} actorId={} skillKey={} versionId={} version={} replacementVersionId={} fromStatus={} toStatus={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,v.getVersion(),replacementId,from,v.getLifecycleStatus());return skillService.versionView(v);}
 @PreAuthorize("hasAuthority('skill:offline')")@Transactional(readOnly=true)public ImpactView impact(Long versionId){SkillVersionEntity v=skillService.version(versionId);List<DependentView> affected=dependencies.findByDependencySkillId(v.getSkill().getId()).stream().filter(d->d.getVersion().getLifecycleStatus()==LifecycleStatus.PUBLISHED||d.getVersion().getLifecycleStatus()==LifecycleStatus.DEPRECATED).map(d->new DependentView(d.getVersion().getSkill().getSkillKey(),d.getVersion().getSkill().getDisplayName(),d.getVersion().getId(),d.getVersion().getVersion(),d.getVersion().getLifecycleStatus(),d.getVersionConstraint())).toList();return new ImpactView(affected.size(),!affected.isEmpty(),affected);}
 @PreAuthorize("hasAuthority('skill:offline')")@Transactional public SkillService.VersionView offline(Long versionId,boolean force,String reason,Long actorId,String requestId){ImpactView impact=impact(versionId);if(impact.blocked()&&!force){log.warn("event=skill.offline.failed requestId={} actorId={} versionId={} errorCode={} publishedDependents={}",requestId,actorId,versionId,"DEPENDENCY_IMPACT",impact.publishedDependents());throw conflict("DEPENDENCY_IMPACT");}SkillVersionEntity v=skillService.version(versionId);LifecycleStatus from=v.getLifecycleStatus();v.offline(clock.instant(),user(actorId));history(v,from,reason,actorId);audit("SKILL_VERSION_OFFLINE",v,actorId,requestId);if(notifications!=null)notifications.lifecycleChanged(v,"SKILL_OFFLINE");log.info("event=skill.version.offline requestId={} actorId={} skillKey={} versionId={} version={} force={} publishedDependents={} fromStatus={} toStatus={}",requestId,actorId,v.getSkill().getSkillKey(),versionId,v.getVersion(),force,impact.publishedDependents(),from,v.getLifecycleStatus());return skillService.versionView(v);}

 private SkillVersionEntity validatedReplacement(SkillVersionEntity source,Long replacementId){if(Objects.equals(source.getId(),replacementId))throw conflict("INVALID_REPLACEMENT_VERSION");SkillVersionEntity replacement=skillService.version(replacementId);if(!Objects.equals(source.getSkill().getId(),replacement.getSkill().getId()))throw conflict("REPLACEMENT_VERSION_SKILL_MISMATCH");if(replacement.getLifecycleStatus()!=LifecycleStatus.PUBLISHED)throw conflict("REPLACEMENT_VERSION_NOT_PUBLISHED");for(SkillVersionEntity cursor=replacement;cursor!=null;cursor=cursor.getReplacementVersion())if(Objects.equals(cursor.getId(),source.getId()))throw conflict("REPLACEMENT_VERSION_CYCLE");return replacement;}
 private void history(SkillVersionEntity v,LifecycleStatus from,String reason,Long actor){histories.save(new SkillStatusHistoryEntity(v,from,v.getLifecycleStatus(),reason,user(actor)));}private void audit(String event,SkillVersionEntity v,Long actor,String request){audit.success(event,user(actor),"SKILL_VERSION",v.getId(),request,null,Map.of("status",v.getLifecycleStatus().name()),Map.of());}
 private SkillReviewEntity anyReview(Long id){return reviews.findById(id).orElseThrow(()->notFound("REVIEW_NOT_FOUND"));}private SkillReviewEntity pendingReview(Long id){SkillReviewEntity r=anyReview(id);if(r.getStatus()!=ReviewStatus.PENDING)throw conflict("REVIEW_NOT_PENDING");return r;}private IamUserEntity user(Long id){return users.findById(id).orElseThrow(()->notFound("USER_NOT_FOUND"));}private void check(int a,int e){if(a!=e)throw conflict("OPTIMISTIC_LOCK_CONFLICT");}private BusinessException conflict(String c){return new BusinessException(c,c,HttpStatus.CONFLICT);}private BusinessException notFound(String c){return new BusinessException(c,c,HttpStatus.NOT_FOUND);}
 private ReviewView view(SkillReviewEntity r){return new ReviewView(r.getId(),r.getVersion().getId(),r.getVersion().getSkill().getSkillKey(),r.getVersion().getSkill().getDisplayName(),r.getReviewNo(),r.getStatus(),r.getVersion().getCandidateVersion(),r.getSubmitter().getId(),r.getSubmitter().getDisplayName(),r.getSubmittedAt(),r.getReviewer()==null?null:r.getReviewer().getId(),r.getReviewer()==null?null:r.getReviewer().getDisplayName(),r.getReviewedAt(),r.getSubmitComment(),r.getReviewComment());}private BuildTaskView taskView(ArtifactBuildTaskEntity t){return new BuildTaskView(t.getId(),t.getVersion().getId(),t.getStatus(),t.getIdempotencyKey(),t.getStartedAt(),t.getFinishedAt(),t.getErrorCode(),t.getErrorMessage());}
 private void validateGates(Long versionId){DependencyService.ResolveView resolved=resolver.resolve(versionId);if(resolved!=null&&!resolved.conflicts().isEmpty())throw new BusinessException("DEPENDENCY_VALIDATION_FAILED","Dependency validation failed",HttpStatus.UNPROCESSABLE_ENTITY);if(compatibility!=null)compatibility.assertPublishable(versionId);}
 public record SubmitView(Long versionId,String candidateVersion,ChangeType changeType,String baseVersion,LifecycleStatus lifecycleStatus,Long reviewId){}public record ReviewView(Long reviewId,Long versionId,String skillKey,String skillName,int reviewNo,ReviewStatus status,String candidateVersion,Long submitterId,String submitterName,Instant submittedAt,Long reviewerId,String reviewerName,Instant reviewedAt,String submitComment,String reviewComment){}public record BuildTaskView(Long taskId,Long versionId,String status,String idempotencyKey,Instant startedAt,Instant finishedAt,String errorCode,String errorMessage){}public record DependentView(String skillKey,String displayName,Long versionId,String version,LifecycleStatus lifecycleStatus,String versionConstraint){}public record ImpactView(long publishedDependents,boolean blocked,List<DependentView> dependents){}
}
