package com.company.skillplatform.workflow.application;

import com.company.skillplatform.audit.application.AuditService;import com.company.skillplatform.common.application.BusinessException;import com.company.skillplatform.dependency.application.DependencyService;import com.company.skillplatform.dependency.infrastructure.repository.SkillVersionDependencyRepository;import com.company.skillplatform.skill.application.SkillService;import com.company.skillplatform.skill.infrastructure.entity.SkillEntity;import com.company.skillplatform.skill.infrastructure.repository.SkillRepository;import com.company.skillplatform.user.infrastructure.entity.IamUserEntity;import com.company.skillplatform.user.infrastructure.repository.IamUserRepository;import com.company.skillplatform.version.domain.*;import com.company.skillplatform.version.infrastructure.entity.SkillVersionEntity;import com.company.skillplatform.workflow.domain.*;import com.company.skillplatform.workflow.infrastructure.entity.*;import com.company.skillplatform.workflow.infrastructure.repository.*;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class WorkflowService{
 private final SkillReviewRepository reviews;private final SkillStatusHistoryRepository histories;private final ArtifactBuildTaskRepository tasks;private final SkillRepository skills;private final SkillVersionDependencyRepository dependencies;private final SkillService skillService;private final DependencyService resolver;private final SemanticVersionPolicy versionPolicy;private final IamUserRepository users;private final PublicationPort publication;private final AuditService audit;private final Clock clock;
 @org.springframework.beans.factory.annotation.Autowired public WorkflowService(SkillReviewRepository r,SkillStatusHistoryRepository h,ArtifactBuildTaskRepository t,SkillRepository s,SkillVersionDependencyRepository d,SkillService ss,DependencyService resolver,SemanticVersionPolicy vp,IamUserRepository u,PublicationPort p,AuditService a){this(r,h,t,s,d,ss,resolver,vp,u,p,a,Clock.systemUTC());}
 WorkflowService(SkillReviewRepository r,SkillStatusHistoryRepository h,ArtifactBuildTaskRepository t,SkillRepository s,SkillVersionDependencyRepository d,SkillService ss,DependencyService resolver,SemanticVersionPolicy vp,IamUserRepository u,PublicationPort p,AuditService a,Clock c){reviews=r;histories=h;tasks=t;skills=s;dependencies=d;skillService=ss;this.resolver=resolver;versionPolicy=vp;users=u;publication=p;audit=a;clock=c;}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public SubmitView submit(Long versionId,int versionNo,String comment,Long actorId,String requestId){SkillVersionEntity initial=skillService.version(versionId);skillService.assertOwner(initial,actorId);SkillEntity skill=skills.findBySkillKeyForUpdate(initial.getSkill().getSkillKey()).orElseThrow(()->notFound("SKILL_NOT_FOUND"));SkillVersionEntity v=skillService.version(versionId);check(v.getVersionNo(),versionNo);if(v.getBaseVersion()!=skill.getLatestPublishedVersion())throw conflict("VERSION_BASE_CHANGED");resolver.resolve(versionId);String latest=skill.getLatestPublishedVersion()==null?null:skill.getLatestPublishedVersion().getVersion();String candidate=v.getCandidateVersion()==null||v.getChangeType()==ChangeType.ZIP_REUPLOAD?versionPolicy.candidate(v.getChangeType(),latest):v.getCandidateVersion();LifecycleStatus from=v.getLifecycleStatus();v.submit(candidate,user(actorId));SkillReviewEntity review=reviews.save(new SkillReviewEntity(v,(int)reviews.countByVersionId(versionId)+1,user(actorId),comment,clock.instant()));history(v,from,"Submitted for review",actorId);audit("SKILL_VERSION_SUBMITTED",v,actorId,requestId);return new SubmitView(v.getId(),candidate,v.getChangeType(),latest,v.getLifecycleStatus(),review.getId());}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional(readOnly=true)public List<ReviewView> reviews(){return reviews.findByStatusOrderBySubmittedAtAsc(ReviewStatus.PENDING).stream().map(this::view).toList();}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional(readOnly=true)public ReviewView review(Long id){return view(reviewEntity(id));}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional public ReviewView approve(Long id,String comment,Long actorId,String requestId){SkillReviewEntity r=reviewEntity(id);LifecycleStatus from=r.getVersion().getLifecycleStatus();r.getVersion().approve(user(actorId));r.approve(user(actorId),comment,clock.instant());history(r.getVersion(),from,comment,actorId);audit("SKILL_REVIEW_APPROVED",r.getVersion(),actorId,requestId);return view(r);}
 @PreAuthorize("hasAuthority('skill:review')")@Transactional public ReviewView reject(Long id,String comment,Long actorId,String requestId){SkillReviewEntity r=reviewEntity(id);LifecycleStatus from=r.getVersion().getLifecycleStatus();r.getVersion().reject(user(actorId));r.reject(user(actorId),comment,clock.instant());history(r.getVersion(),from,comment,actorId);audit("SKILL_REVIEW_REJECTED",r.getVersion(),actorId,requestId);return view(r);}
 @PreAuthorize("hasAuthority('skill:edit')")@Transactional public SkillService.VersionView withdraw(Long versionId,int versionNo,String reason,Long actorId,String requestId){SkillVersionEntity v=skillService.version(versionId);skillService.assertOwner(v,actorId);check(v.getVersionNo(),versionNo);LifecycleStatus from=v.getLifecycleStatus();v.withdraw(user(actorId));history(v,from,reason,actorId);audit("SKILL_VERSION_WITHDRAWN",v,actorId,requestId);return skillService.versionView(v);}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional public BuildTaskView publish(Long versionId,String key,Long actorId,String requestId){Optional<ArtifactBuildTaskEntity> existing=tasks.findByIdempotencyKey(key);if(existing.isPresent())return taskView(existing.get());SkillVersionEntity v=skillService.version(versionId);resolver.resolve(versionId);publication.build(versionId);LifecycleStatus from=v.getLifecycleStatus();v.publish(clock.instant(),user(actorId));v.getSkill().publish(v,user(actorId));ArtifactBuildTaskEntity task=tasks.save(new ArtifactBuildTaskEntity(v,key,user(actorId),clock.instant()));history(v,from,"Published",actorId);audit("SKILL_VERSION_PUBLISHED",v,actorId,requestId);return taskView(task);}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional(readOnly=true)public BuildTaskView task(Long id){return taskView(tasks.findById(id).orElseThrow(()->notFound("BUILD_TASK_NOT_FOUND")));}
 @PreAuthorize("hasAuthority('skill:publish')")@Transactional public SkillService.VersionView deprecate(Long versionId,Long replacementId,Long actorId,String requestId){SkillVersionEntity v=skillService.version(versionId);SkillVersionEntity replacement=replacementId==null?null:skillService.version(replacementId);LifecycleStatus from=v.getLifecycleStatus();v.deprecate(replacement,user(actorId));history(v,from,"Deprecated",actorId);audit("SKILL_VERSION_DEPRECATED",v,actorId,requestId);return skillService.versionView(v);}
 @PreAuthorize("hasAuthority('skill:offline')")@Transactional(readOnly=true)public ImpactView impact(Long versionId){SkillVersionEntity v=skillService.version(versionId);long count=dependencies.findByDependencySkillId(v.getSkill().getId()).stream().filter(d->d.getVersion().getLifecycleStatus()==LifecycleStatus.PUBLISHED||d.getVersion().getLifecycleStatus()==LifecycleStatus.DEPRECATED).count();return new ImpactView(count,count>0);}
 @PreAuthorize("hasAuthority('skill:offline')")@Transactional public SkillService.VersionView offline(Long versionId,boolean force,String reason,Long actorId,String requestId){ImpactView impact=impact(versionId);if(impact.blocked()&&!force)throw conflict("DEPENDENCY_IMPACT");SkillVersionEntity v=skillService.version(versionId);LifecycleStatus from=v.getLifecycleStatus();v.offline(clock.instant(),user(actorId));history(v,from,reason,actorId);audit("SKILL_VERSION_OFFLINE",v,actorId,requestId);return skillService.versionView(v);}
 private void history(SkillVersionEntity v,LifecycleStatus from,String reason,Long actor){histories.save(new SkillStatusHistoryEntity(v,from,v.getLifecycleStatus(),reason,user(actor)));}private void audit(String event,SkillVersionEntity v,Long actor,String request){audit.success(event,user(actor),"SKILL_VERSION",v.getId(),request,null,Map.of("status",v.getLifecycleStatus().name()),Map.of());}
 private SkillReviewEntity reviewEntity(Long id){SkillReviewEntity r=reviews.findById(id).orElseThrow(()->notFound("REVIEW_NOT_FOUND"));if(r.getStatus()!=ReviewStatus.PENDING)throw conflict("REVIEW_NOT_PENDING");return r;}private IamUserEntity user(Long id){return users.findById(id).orElseThrow(()->notFound("USER_NOT_FOUND"));}private void check(int a,int e){if(a!=e)throw conflict("OPTIMISTIC_LOCK_CONFLICT");}private BusinessException conflict(String c){return new BusinessException(c,c,HttpStatus.CONFLICT);}private BusinessException notFound(String c){return new BusinessException(c,c,HttpStatus.NOT_FOUND);}
 private ReviewView view(SkillReviewEntity r){return new ReviewView(r.getId(),r.getVersion().getId(),r.getReviewNo(),r.getStatus(),r.getVersion().getCandidateVersion(),r.getSubmitComment(),r.getReviewComment());}private BuildTaskView taskView(ArtifactBuildTaskEntity t){return new BuildTaskView(t.getId(),t.getVersion().getId(),t.getStatus(),t.getIdempotencyKey());}
 public record SubmitView(Long versionId,String candidateVersion,ChangeType changeType,String baseVersion,LifecycleStatus lifecycleStatus,Long reviewId){}public record ReviewView(Long reviewId,Long versionId,int reviewNo,ReviewStatus status,String candidateVersion,String submitComment,String reviewComment){}public record BuildTaskView(Long taskId,Long versionId,String status,String idempotencyKey){}public record ImpactView(long publishedDependents,boolean blocked){}
}
