CREATE TABLE feishu_bot_binding (
    id BIGINT NOT NULL AUTO_INCREMENT,
    owner_user_id BIGINT NOT NULL,
    scope_key VARCHAR(255) NOT NULL,
    chat_id VARCHAR(128) NOT NULL,
    chat_type VARCHAR(32) NOT NULL,
    thread_key VARCHAR(255) NOT NULL,
    session_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    device_type VARCHAR(32) NOT NULL,
    time_created TIMESTAMP(6) NOT NULL,
    time_updated TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_feishu_bot_binding_scope (owner_user_id, scope_key),
    KEY idx_feishu_bot_binding_session (session_id),
    CONSTRAINT fk_feishu_bot_binding_user FOREIGN KEY (owner_user_id) REFERENCES iam_user(id),
    CONSTRAINT fk_feishu_bot_binding_session FOREIGN KEY (session_id) REFERENCES agent_session(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE feishu_bot_message (
    id BIGINT NOT NULL AUTO_INCREMENT,
    message_id VARCHAR(128) NOT NULL,
    event_request_id VARCHAR(128) NULL,
    owner_user_id BIGINT NULL,
    chat_id VARCHAR(128) NOT NULL,
    chat_type VARCHAR(32) NOT NULL,
    thread_key VARCHAR(255) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    user_agent VARCHAR(512) NULL,
    device_type VARCHAR(32) NOT NULL,
    binding_id BIGINT NULL,
    agent_session_key CHAR(36) NULL,
    agent_run_key CHAR(36) NULL,
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(64) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    reply_message_id VARCHAR(128) NULL,
    next_retry_at TIMESTAMP(6) NULL,
    time_created TIMESTAMP(6) NOT NULL,
    time_updated TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_feishu_bot_message_id (message_id),
    KEY idx_feishu_bot_message_status (status, next_retry_at),
    KEY idx_feishu_bot_message_run (agent_run_key),
    CONSTRAINT fk_feishu_bot_message_user FOREIGN KEY (owner_user_id) REFERENCES iam_user(id),
    CONSTRAINT fk_feishu_bot_message_binding FOREIGN KEY (binding_id) REFERENCES feishu_bot_binding(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
