CREATE TABLE agent_mcp_audit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    run_key CHAR(36) NOT NULL,
    session_key CHAR(36) NOT NULL,
    actor_user_id BIGINT NULL,
    tool_name VARCHAR(128) NOT NULL,
    call_id VARCHAR(128) NOT NULL,
    source_channel VARCHAR(32) NOT NULL,
    knowledge_scope VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    duration_ms BIGINT NULL,
    error_code VARCHAR(128) NULL,
    arguments_summary VARCHAR(2000) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_mcp_audit_call UNIQUE (run_key, call_id),
    CONSTRAINT fk_agent_mcp_audit_actor FOREIGN KEY (actor_user_id) REFERENCES iam_user (id) ON DELETE SET NULL,
    INDEX idx_agent_mcp_audit_time (time_created),
    INDEX idx_agent_mcp_audit_tool (tool_name, time_created),
    INDEX idx_agent_mcp_audit_actor (actor_user_id, time_created),
    INDEX idx_agent_mcp_audit_session (session_key, time_created)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
