INSERT INTO skill_category (category_key,category_name,parent_id,sort_order,status,version_no,time_created,time_updated) VALUES
('requirement','需求',NULL,100,'ACTIVE',0,NOW(6),NOW(6)),('product','产品',NULL,200,'ACTIVE',0,NOW(6),NOW(6)),
('architecture','架构设计',NULL,300,'ACTIVE',0,NOW(6),NOW(6)),('ui','UI设计',NULL,400,'ACTIVE',0,NOW(6),NOW(6)),
('backend','后端编码',NULL,500,'ACTIVE',0,NOW(6),NOW(6)),('frontend','前端编码',NULL,600,'ACTIVE',0,NOW(6),NOW(6)),
('security','安全审核',NULL,700,'ACTIVE',0,NOW(6),NOW(6)),('testing','测试',NULL,800,'ACTIVE',0,NOW(6),NOW(6)),
('deployment','部署',NULL,900,'ACTIVE',0,NOW(6),NOW(6))
ON DUPLICATE KEY UPDATE category_name=VALUES(category_name),sort_order=VALUES(sort_order),status='ACTIVE',time_updated=NOW(6);

INSERT INTO skill_category (category_key,category_name,parent_id,sort_order,status,version_no,time_created,time_updated)
SELECT x.category_key,x.category_name,p.id,x.sort_order,'ACTIVE',0,NOW(6),NOW(6) FROM (
SELECT 'requirement.discovery' category_key,'需求发现与澄清' category_name,'requirement' parent_key,101 sort_order UNION ALL SELECT 'requirement.analysis','需求分析与验收标准','requirement',102 UNION ALL SELECT 'requirement.research','技术调研与资料检索','requirement',103 UNION ALL SELECT 'requirement.market','市场与竞品研究','requirement',104 UNION ALL SELECT 'requirement.prototype','可行性与原型验证','requirement',105 UNION ALL SELECT 'requirement.planning','计划拆解与任务编排','requirement',106
UNION ALL SELECT 'product.strategy','产品战略与能力规划','product',201 UNION ALL SELECT 'product.roadmap','路线图与交付管理','product',202 UNION ALL SELECT 'product.knowledge','文档与知识管理','product',203 UNION ALL SELECT 'product.growth','内容、增长与 SEO','product',204 UNION ALL SELECT 'product.operations','企业运营','product',205 UNION ALL SELECT 'product.industry','行业与领域方案','product',206 UNION ALL SELECT 'product.collaboration','协作与沟通','product',207 UNION ALL SELECT 'product.general','综合研发实践','product',208
UNION ALL SELECT 'architecture.system','系统与服务架构','architecture',301 UNION ALL SELECT 'architecture.integration','API、MCP 与系统集成','architecture',302 UNION ALL SELECT 'architecture.data','数据与存储架构','architecture',303 UNION ALL SELECT 'architecture.cloud','分布式、云与网络架构','architecture',304 UNION ALL SELECT 'architecture.ai','Agent、LLM 与推荐架构','architecture',305 UNION ALL SELECT 'architecture.reliability','性能与可靠性设计','architecture',306 UNION ALL SELECT 'architecture.governance','ADR 与架构治理','architecture',307
UNION ALL SELECT 'ui.ux','用户体验与交互设计','ui',401 UNION ALL SELECT 'ui.visual','视觉与设计系统','ui',402 UNION ALL SELECT 'ui.accessibility','无障碍设计','ui',403 UNION ALL SELECT 'ui.motion','动效与多媒体设计','ui',404 UNION ALL SELECT 'ui.dashboard','数据可视化与仪表盘','ui',405 UNION ALL SELECT 'ui.delivery','原型、演示与设计交付','ui',406
UNION ALL SELECT 'backend.jvm','Java 与 JVM','backend',501 UNION ALL SELECT 'backend.python','Python','backend',502 UNION ALL SELECT 'backend.node','Node.js 与 TypeScript','backend',503 UNION ALL SELECT 'backend.go','Go','backend',504 UNION ALL SELECT 'backend.systems','Rust、C 与 C++','backend',505 UNION ALL SELECT 'backend.dotnet','.NET','backend',506 UNION ALL SELECT 'backend.php_perl','PHP 与 Perl','backend',507 UNION ALL SELECT 'backend.database','数据库与缓存','backend',508 UNION ALL SELECT 'backend.async','消息、异步与任务调度','backend',509 UNION ALL SELECT 'backend.api','API 与连接器开发','backend',510 UNION ALL SELECT 'backend.ai_data','AI、ML 与数据工程','backend',511 UNION ALL SELECT 'backend.automation','自动化与数据采集','backend',512
UNION ALL SELECT 'frontend.react','React 与 Next.js','frontend',601 UNION ALL SELECT 'frontend.vue','Vue 与 Nuxt','frontend',602 UNION ALL SELECT 'frontend.angular','Angular','frontend',603 UNION ALL SELECT 'frontend.web','Web 平台、Vite 与 Bun','frontend',604 UNION ALL SELECT 'frontend.ios','iOS 与 SwiftUI','frontend',605 UNION ALL SELECT 'frontend.android','Android 与 Kotlin','frontend',606 UNION ALL SELECT 'frontend.cross_platform','Flutter、Compose 与 React Native','frontend',607 UNION ALL SELECT 'frontend.desktop','桌面与跨平台客户端','frontend',608 UNION ALL SELECT 'frontend.engineering','前端状态、性能与工程化','frontend',609
UNION ALL SELECT 'security.application','应用安全、认证与授权','security',701 UNION ALL SELECT 'security.supply_chain','代码、依赖与供应链安全','security',702 UNION ALL SELECT 'security.cloud','云、容器与网络安全','security',703 UNION ALL SELECT 'security.agent','Agent、MCP 与 LLM 安全','security',704 UNION ALL SELECT 'security.compliance','隐私与合规','security',705 UNION ALL SELECT 'security.vulnerability','漏洞分析与渗透测试','security',706 UNION ALL SELECT 'security.configuration','配置、密钥与权限审计','security',707
UNION ALL SELECT 'testing.unit','单元测试','testing',801 UNION ALL SELECT 'testing.component','组件与 UI 测试','testing',802 UNION ALL SELECT 'testing.integration','集成与 API 测试','testing',803 UNION ALL SELECT 'testing.contract','契约与 Schema 测试','testing',804 UNION ALL SELECT 'testing.web_e2e','Web E2E','testing',805 UNION ALL SELECT 'testing.client_e2e','移动/桌面 E2E','testing',806 UNION ALL SELECT 'testing.performance','性能/负载/基准','testing',807 UNION ALL SELECT 'testing.security','安全测试','testing',808 UNION ALL SELECT 'testing.agent_eval','Agent/LLM 评测','testing',809 UNION ALL SELECT 'testing.regression','回归测试','testing',810 UNION ALL SELECT 'testing.quality_gate','覆盖率/验证循环/质量门禁','testing',811 UNION ALL SELECT 'testing.environment','测试数据/环境/稳定性','testing',812
UNION ALL SELECT 'deployment.cicd','CI/CD 与发布流水线','deployment',901 UNION ALL SELECT 'deployment.git','Git 与版本发布','deployment',902 UNION ALL SELECT 'deployment.docker','Docker 与容器部署','deployment',903 UNION ALL SELECT 'deployment.kubernetes','Kubernetes 与云部署','deployment',904 UNION ALL SELECT 'deployment.infrastructure','基础设施与网络','deployment',905 UNION ALL SELECT 'deployment.configuration','配置、环境与密钥管理','deployment',906 UNION ALL SELECT 'deployment.observability','可观测性','deployment',907 UNION ALL SELECT 'deployment.operations','故障响应与运行维护','deployment',908 UNION ALL SELECT 'deployment.canary','灰度、金丝雀与回滚','deployment',909 UNION ALL SELECT 'deployment.runtime','运行时与开发工具安装','deployment',910
) x JOIN skill_category p ON p.category_key=x.parent_key
ON DUPLICATE KEY UPDATE category_name=VALUES(category_name),parent_id=VALUES(parent_id),sort_order=VALUES(sort_order),status='ACTIVE',time_updated=NOW(6);

UPDATE skill s LEFT JOIN skill_category c ON c.id=s.category_id
SET s.category_id=(SELECT id FROM skill_category WHERE category_key='product.general')
WHERE c.id IS NULL OR c.category_key NOT LIKE '%.%';

UPDATE skill_category SET parent_id=NULL WHERE category_key NOT IN ('requirement','product','architecture','ui','backend','frontend','security','testing','deployment') AND category_key NOT LIKE '%.%';
DELETE FROM skill_category WHERE category_key NOT IN ('requirement','product','architecture','ui','backend','frontend','security','testing','deployment') AND category_key NOT LIKE '%.%';
