CREATE TABLE skill_usage_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    event_uuid VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    skill_version_id BIGINT NULL,
    skill_key_snapshot VARCHAR(128) NOT NULL,
    installation_id VARCHAR(64) NULL,
    feishu_user_id_ciphertext TEXT NOT NULL,
    feishu_open_id_ciphertext TEXT NOT NULL,
    local_directory VARCHAR(2048) NOT NULL,
    client_session_id VARCHAR(256) NOT NULL,
    generation_id VARCHAR(256) NULL,
    client VARCHAR(64) NOT NULL,
    client_version VARCHAR(64) NULL,
    agent_type VARCHAR(64) NULL,
    model VARCHAR(256) NULL,
    invoked_at DATETIME(3) NOT NULL,
    received_at DATETIME(3) NOT NULL,
    conversation_status VARCHAR(32) NOT NULL,
    conversation_error_code VARCHAR(64) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_skill_usage_event_uuid UNIQUE (event_uuid),
    CONSTRAINT fk_skill_usage_user FOREIGN KEY (user_id) REFERENCES iam_user(id) ON DELETE RESTRICT,
    CONSTRAINT fk_skill_usage_skill FOREIGN KEY (skill_id) REFERENCES skill(id) ON DELETE RESTRICT,
    INDEX idx_skill_usage_user_time (user_id, invoked_at),
    INDEX idx_skill_usage_skill_time (skill_id, invoked_at),
    INDEX idx_skill_usage_session (user_id, client_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
