CREATE TABLE wiki_document_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    document_id BIGINT NOT NULL,
    revision_id BIGINT NOT NULL,
    review_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    submitter_id BIGINT NOT NULL,
    reviewer_id BIGINT NULL,
    submit_comment TEXT NULL,
    review_comment TEXT NULL,
    submitted_at DATETIME(3) NOT NULL,
    reviewed_at DATETIME(3) NULL,
    pending_document_id BIGINT GENERATED ALWAYS AS (CASE WHEN status='PENDING' THEN document_id ELSE NULL END) STORED,
    PRIMARY KEY (id),
    CONSTRAINT uk_wiki_review_no UNIQUE (document_id, review_no),
    CONSTRAINT uk_wiki_review_pending UNIQUE (pending_document_id),
    CONSTRAINT fk_wiki_review_document FOREIGN KEY (document_id) REFERENCES wiki_document(id) ON DELETE RESTRICT,
    CONSTRAINT fk_wiki_review_revision FOREIGN KEY (revision_id) REFERENCES wiki_document_revision(id) ON DELETE RESTRICT,
    CONSTRAINT fk_wiki_review_submitter FOREIGN KEY (submitter_id) REFERENCES iam_user(id) ON DELETE RESTRICT,
    CONSTRAINT fk_wiki_review_reviewer FOREIGN KEY (reviewer_id) REFERENCES iam_user(id) ON DELETE RESTRICT,
    INDEX idx_wiki_review_status (status, submitted_at),
    INDEX idx_wiki_review_team (document_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
