CREATE TABLE document_agent_session (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    session_key CHAR(36) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    document_id BIGINT NULL,
    profile_key VARCHAR(64) NOT NULL,
    target_title VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL,
    runtime_session_id VARCHAR(128) NULL,
    conversation_id VARCHAR(128) NULL,
    workspace_id VARCHAR(255) NULL,
    mcp_token_hash CHAR(64) NOT NULL,
    mcp_token_expires_at DATETIME(3) NOT NULL,
    last_activity_at DATETIME(3) NOT NULL,
    closed_at DATETIME(3) NULL,
    version_no INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_document_agent_session_key UNIQUE (session_key),
    CONSTRAINT uk_document_agent_session_idempotency UNIQUE (owner_user_id, project_id, idempotency_key),
    CONSTRAINT fk_document_agent_session_project FOREIGN KEY (project_id) REFERENCES virtual_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_agent_session_owner FOREIGN KEY (owner_user_id) REFERENCES iam_user(id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_agent_session_document FOREIGN KEY (document_id) REFERENCES project_document(id) ON DELETE SET NULL,
    INDEX idx_document_agent_session_owner (owner_user_id, status, last_activity_at),
    INDEX idx_document_agent_session_project (project_id, status, last_activity_at),
    INDEX idx_document_agent_session_token (mcp_token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE document_agent_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    job_key CHAR(36) NOT NULL,
    session_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    instruction MEDIUMTEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    runtime_job_id VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1024) NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    version_no INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_document_agent_job_key UNIQUE (job_key),
    CONSTRAINT uk_document_agent_job_idempotency UNIQUE (session_id, idempotency_key),
    CONSTRAINT uk_document_agent_job_sequence UNIQUE (session_id, sequence_no),
    CONSTRAINT fk_document_agent_job_session FOREIGN KEY (session_id) REFERENCES document_agent_session(id) ON DELETE CASCADE,
    INDEX idx_document_agent_job_status (status, time_updated),
    INDEX idx_document_agent_job_runtime (runtime_job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE document_agent_job_context (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    job_id BIGINT NOT NULL,
    context_kind VARCHAR(32) NOT NULL,
    artifact_id BIGINT NULL,
    artifact_revision_id BIGINT NULL,
    feishu_doc_id VARCHAR(512) NULL,
    feishu_doc_type VARCHAR(32) NULL,
    feishu_title VARCHAR(255) NULL,
    ordinal_no INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_agent_context_job FOREIGN KEY (job_id) REFERENCES document_agent_job(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_agent_context_artifact FOREIGN KEY (artifact_id) REFERENCES project_document(id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_agent_context_revision FOREIGN KEY (artifact_revision_id) REFERENCES project_document_revision(id) ON DELETE RESTRICT,
    CONSTRAINT uk_document_agent_context_feishu UNIQUE (job_id, context_kind, feishu_doc_id, feishu_doc_type),
    INDEX idx_document_agent_context_job (job_id, ordinal_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE document_agent_job_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    job_id BIGINT NOT NULL,
    sequence_no BIGINT NOT NULL,
    runtime_event_id VARCHAR(128) NULL,
    event_type VARCHAR(64) NOT NULL,
    payload JSON NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_agent_event_job FOREIGN KEY (job_id) REFERENCES document_agent_job(id) ON DELETE CASCADE,
    CONSTRAINT uk_document_agent_event_sequence UNIQUE (job_id, sequence_no),
    INDEX idx_document_agent_event_job (job_id, sequence_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
