CREATE TABLE workflow_human_question (
 id BIGINT NOT NULL AUTO_INCREMENT,
 time_created DATETIME(3) NOT NULL,
 time_updated DATETIME(3) NOT NULL,
 workflow_run_id BIGINT NOT NULL,
 stage_run_id BIGINT NOT NULL,
 agent_session_id BIGINT NOT NULL,
 agent_run_id BIGINT NOT NULL,
 question_text TEXT NOT NULL,
 choices_json JSON NULL,
 answer_text TEXT NULL,
 answered_by BIGINT NULL,
 answered_at DATETIME(3) NULL,
 status VARCHAR(30) NOT NULL,
 last_error VARCHAR(2000) NULL,
 runtime_command_id BIGINT NULL,
 PRIMARY KEY(id),
 INDEX idx_human_question_run(workflow_run_id,status,id),
 INDEX idx_human_question_agent(agent_run_id,status,id),
 CONSTRAINT fk_human_question_workflow FOREIGN KEY(workflow_run_id) REFERENCES workflow_run(id),
 CONSTRAINT fk_human_question_stage FOREIGN KEY(stage_run_id) REFERENCES stage_run(id),
 CONSTRAINT fk_human_question_session FOREIGN KEY(agent_session_id) REFERENCES agent_workflow_session(id),
 CONSTRAINT fk_human_question_agent_run FOREIGN KEY(agent_run_id) REFERENCES agent_workflow_run(id),
 CONSTRAINT fk_human_question_answered_by FOREIGN KEY(answered_by) REFERENCES iam_user(id),
 CONSTRAINT fk_human_question_command FOREIGN KEY(runtime_command_id) REFERENCES runtime_command(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
