-- Make the OpenHands completion mechanism explicit and validate each node's
-- result code at the transport boundary. The built-in finish tool is the only
-- terminal channel consumed by the runtime gateway.
UPDATE stage_agent_node_def n
JOIN workflow_stage_def d ON d.id=n.stage_def_id
JOIN workflow_template_version v ON v.id=d.workflow_version_id
JOIN workflow_template t ON t.id=v.workflow_template_id
SET n.protocol_prompt = CASE n.node_key
    WHEN 'clarifier' THEN 'WORKFLOW PROTOCOL (SYSTEM LOCKED): When a blocking answer is required, call workflow_request_human_input with exactly one concise question, stop that turn, and wait for the human answer. After sufficient information exists, complete by calling the built-in finish tool exactly once. The finish message must contain ONLY one JSON object with schemaVersion=1, executionStatus=SUCCESS, resultCode=CLARIFIED, a non-empty summary, artifacts=[], reviewedArtifactRevisionIds=[], issues=[], blockingIssues=[], and metrics={}. Do not wrap the JSON in Markdown, add explanatory text, or use NEEDS_HUMAN as a final result.'
    WHEN 'writer' THEN 'WORKFLOW PROTOCOL (SYSTEM LOCKED): Call save_artifact_draft with artifactType REQUIREMENT and update the existing artifact when one is supplied. Use the exact documentId and revisionId returned by that tool. Then complete by calling the built-in finish tool exactly once. The finish message must contain ONLY one JSON object with schemaVersion=1, executionStatus=SUCCESS, resultCode=DOCUMENT_CREATED, a non-empty summary, artifacts=[{artifactType:REQUIREMENT,documentId,revisionId}], reviewedArtifactRevisionIds=[], issues=[], blockingIssues=[], and metrics={}. Do not wrap the JSON in Markdown, add explanatory text, or invent artifact IDs.'
    WHEN 'reviewer' THEN 'WORKFLOW PROTOCOL (SYSTEM LOCKED): Review exactly the latest Requirement artifact named in the task. Decide by quality: use APPROVED only when it is complete, consistent and actionable; otherwise use REVISION_REQUIRED with concrete issues. Complete by calling the built-in finish tool exactly once. The finish message must contain ONLY one JSON object with schemaVersion=1, executionStatus=SUCCESS, resultCode=APPROVED or REVISION_REQUIRED, a non-empty summary, artifacts=[], reviewedArtifactRevisionIds=[the exact latest reviewed revision ID], issues, blockingIssues, and metrics={}. Do not wrap the JSON in Markdown, add explanatory text, force a first-round rejection, or approve an artifact you did not review.'
    ELSE n.protocol_prompt END,
    n.output_schema_json = CASE n.node_key
    WHEN 'clarifier' THEN '{"type":"object","additionalProperties":false,"required":["schemaVersion","executionStatus","resultCode","summary","artifacts","reviewedArtifactRevisionIds","issues","blockingIssues","metrics"],"properties":{"schemaVersion":{"const":1},"executionStatus":{"const":"SUCCESS"},"resultCode":{"enum":["CLARIFIED"]},"summary":{"type":"string","minLength":1},"artifacts":{"type":"array","maxItems":0},"reviewedArtifactRevisionIds":{"type":"array","maxItems":0},"issues":{"type":"array","maxItems":0},"blockingIssues":{"type":"array","maxItems":0},"metrics":{"type":"object"}}}'
    WHEN 'writer' THEN '{"type":"object","additionalProperties":false,"required":["schemaVersion","executionStatus","resultCode","summary","artifacts","reviewedArtifactRevisionIds","issues","blockingIssues","metrics"],"properties":{"schemaVersion":{"const":1},"executionStatus":{"const":"SUCCESS"},"resultCode":{"enum":["DOCUMENT_CREATED"]},"summary":{"type":"string","minLength":1},"artifacts":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":false,"required":["artifactType","documentId","revisionId"],"properties":{"artifactType":{"const":"REQUIREMENT"},"documentId":{"type":"integer"},"revisionId":{"type":"integer"}}}},"reviewedArtifactRevisionIds":{"type":"array","maxItems":0},"issues":{"type":"array","maxItems":0},"blockingIssues":{"type":"array","maxItems":0},"metrics":{"type":"object"}}}'
    WHEN 'reviewer' THEN '{"type":"object","additionalProperties":false,"required":["schemaVersion","executionStatus","resultCode","summary","artifacts","reviewedArtifactRevisionIds","issues","blockingIssues","metrics"],"properties":{"schemaVersion":{"const":1},"executionStatus":{"const":"SUCCESS"},"resultCode":{"enum":["APPROVED","REVISION_REQUIRED"]},"summary":{"type":"string","minLength":1},"artifacts":{"type":"array","maxItems":0},"reviewedArtifactRevisionIds":{"type":"array","minItems":1,"maxItems":1,"items":{"type":"integer"}},"issues":{"type":"array"},"blockingIssues":{"type":"array","maxItems":0},"metrics":{"type":"object"}}}'
    ELSE n.output_schema_json END,
    n.time_updated=NOW(3)
WHERE t.code='requirement-mvp' AND v.version_no=1 AND d.stage_key='REQUIREMENT'
  AND n.node_key IN ('clarifier','writer','reviewer');
