CREATE TABLE IF NOT EXISTS project_feishu_publish_target (
  id BIGINT NOT NULL AUTO_INCREMENT,
  time_created TIMESTAMP(3) NOT NULL,
  time_updated TIMESTAMP(3) NOT NULL,
  project_id BIGINT NOT NULL,
  source_url VARCHAR(1000) NOT NULL,
  space_id VARCHAR(255) NOT NULL,
  parent_node_token VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL,
  validated_by BIGINT NULL,
  validated_at TIMESTAMP(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_feishu_target_project (project_id),
  CONSTRAINT fk_project_feishu_target_project FOREIGN KEY (project_id) REFERENCES virtual_project(id),
  CONSTRAINT fk_project_feishu_target_user FOREIGN KEY (validated_by) REFERENCES iam_user(id)
);

CREATE TABLE IF NOT EXISTS project_feishu_publication_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  time_created TIMESTAMP(3) NOT NULL,
  time_updated TIMESTAMP(3) NOT NULL,
  project_id BIGINT NOT NULL,
  workflow_run_id BIGINT NULL,
  stage_run_id BIGINT NULL,
  stage_key VARCHAR(64) NOT NULL,
  document_id BIGINT NULL,
  revision_id BIGINT NULL,
  target_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  attempt_count INT NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMP(3) NULL,
  last_error VARCHAR(2000) NULL,
  document_token VARCHAR(255) NULL,
  wiki_node_token VARCHAR(255) NULL,
  document_url VARCHAR(1000) NULL,
  claimed_at TIMESTAMP(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_feishu_publication_revision (target_id, stage_run_id, revision_id),
  KEY ix_project_feishu_publication_due (status, next_attempt_at),
  KEY ix_project_feishu_publication_run (workflow_run_id),
  KEY ix_project_feishu_publication_stage (stage_run_id),
  CONSTRAINT fk_project_feishu_pub_project FOREIGN KEY (project_id) REFERENCES virtual_project(id),
  CONSTRAINT fk_project_feishu_pub_run FOREIGN KEY (workflow_run_id) REFERENCES workflow_run(id),
  CONSTRAINT fk_project_feishu_pub_stage FOREIGN KEY (stage_run_id) REFERENCES stage_run(id),
  CONSTRAINT fk_project_feishu_pub_target FOREIGN KEY (target_id) REFERENCES project_feishu_publish_target(id),
  CONSTRAINT fk_project_feishu_pub_document FOREIGN KEY (document_id) REFERENCES project_document(id),
  CONSTRAINT fk_project_feishu_pub_revision FOREIGN KEY (revision_id) REFERENCES project_document_revision(id)
);
ALTER TABLE user_notification ADD COLUMN target_data JSON NULL;
