CREATE TABLE code_graph_repository_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    logical_repository_key VARCHAR(300) NOT NULL,
    commit_sha CHAR(40) NOT NULL,
    tree_sha CHAR(40) NOT NULL,
    engine_type VARCHAR(32) NOT NULL,
    engine_version VARCHAR(100) NOT NULL,
    adapter_version VARCHAR(100) NOT NULL,
    engine_config_hash CHAR(64) NOT NULL,
    graph_fingerprint CHAR(64) NOT NULL,
    artifact_key VARCHAR(1000) NULL,
    artifact_sha256 CHAR(64) NULL,
    status VARCHAR(24) NOT NULL,
    build_mode VARCHAR(24) NOT NULL,
    base_snapshot_id BIGINT NULL,
    file_count BIGINT NULL,
    symbol_count BIGINT NULL,
    relation_count BIGINT NULL,
    last_error TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_graph_snapshot_fingerprint (graph_fingerprint),
    KEY idx_code_graph_snapshot_reuse (logical_repository_key, tree_sha, engine_type, status),
    CONSTRAINT fk_code_graph_snapshot_base FOREIGN KEY (base_snapshot_id) REFERENCES code_graph_repository_snapshot(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE code_graph_bundle (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    bundle_hash CHAR(64) NOT NULL,
    engine_type VARCHAR(32) NOT NULL,
    engine_bundle_key VARCHAR(128) NOT NULL,
    repository_count INT NOT NULL,
    status VARCHAR(24) NOT NULL,
    artifact_key VARCHAR(1000) NULL,
    artifact_sha256 CHAR(64) NULL,
    last_error TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_graph_bundle_hash (bundle_hash),
    UNIQUE KEY uk_code_graph_engine_bundle_key (engine_bundle_key),
    KEY idx_code_graph_bundle_status (status, time_updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE code_graph_bundle_repository (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    bundle_id BIGINT NOT NULL,
    repository_snapshot_id BIGINT NOT NULL,
    repository_alias VARCHAR(128) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_graph_bundle_snapshot (bundle_id, repository_snapshot_id),
    UNIQUE KEY uk_code_graph_bundle_alias (bundle_id, repository_alias),
    CONSTRAINT fk_code_graph_bundle_repo_bundle FOREIGN KEY (bundle_id) REFERENCES code_graph_bundle(id),
    CONSTRAINT fk_code_graph_bundle_repo_snapshot FOREIGN KEY (repository_snapshot_id) REFERENCES code_graph_repository_snapshot(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE workflow_run_code_graph_binding (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    workflow_run_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    bundle_id BIGINT NULL,
    engine_type VARCHAR(32) NOT NULL,
    engine_bundle_key VARCHAR(128) NOT NULL,
    repository_set_hash CHAR(64) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    semantic_index_status VARCHAR(24) NOT NULL DEFAULT 'DISABLED',
    activated_at DATETIME(3) NULL,
    active_workflow_run_id BIGINT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN workflow_run_id ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_graph_binding_version (workflow_run_id, version_no),
    UNIQUE KEY uk_code_graph_binding_single_active (active_workflow_run_id),
    KEY idx_code_graph_binding_bundle (bundle_id),
    CONSTRAINT fk_code_graph_binding_run FOREIGN KEY (workflow_run_id) REFERENCES workflow_run(id),
    CONSTRAINT fk_code_graph_binding_bundle FOREIGN KEY (bundle_id) REFERENCES code_graph_bundle(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE code_graph_generation_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    time_created DATETIME(3) NOT NULL,
    time_updated DATETIME(3) NOT NULL,
    workflow_run_id BIGINT NOT NULL,
    target_binding_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    reason VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    engine_type VARCHAR(32) NOT NULL,
    engine_job_id VARCHAR(128) NULL,
    reuse_plan_json JSON NOT NULL,
    build_request_json JSON NOT NULL,
    progress INT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    next_attempt_at DATETIME(3) NULL,
    lease_until DATETIME(3) NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message TEXT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_code_graph_job_request (request_id),
    KEY idx_code_graph_job_due (status, next_attempt_at, lease_until),
    KEY idx_code_graph_job_run (workflow_run_id, time_created),
    CONSTRAINT fk_code_graph_job_run FOREIGN KEY (workflow_run_id) REFERENCES workflow_run(id),
    CONSTRAINT fk_code_graph_job_binding FOREIGN KEY (target_binding_id) REFERENCES workflow_run_code_graph_binding(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
